// Buyer-facing copy (zh-CN / zh-TW / en) for the CVS pickup picker, pay-at-pickup and the CVS parts of the
// order page (contracts/taiwan-cvs-logistics-v1.md §5.3, §16.1, §16.2, §16.4, §16.8; owner answers U2, U3, U4).
// Rendered by components/CvsPickup.tsx and components/OrderFlow.tsx; no BFF route of its own.
// Rules encoded here: never "已驗證"/"verified" for a buyer-typed store, never "delivered" before PICKED_UP,
// REQUESTED/UNKNOWN/FAILED/ABANDONED read as one "processing" text (no error detail), chain names per U2.
import type { Locale } from "@live-commerce/i18n";
import type { CvsErrorCode, CvsKind } from "./cvs-contract";

const en = {
  // chain labels (U2)
  chains: {
    cvs_711: "7-ELEVEN",
    cvs_familymart: "FamilyMart",
    cvs_hilife: "Hi-Life",
    cvs_okmart: "OK mart",
  } as Record<CvsKind, string>,
  comingSoon: "Coming soon",
  // section
  title: "Pickup store",
  intro: "Choose the store where you will pick up your parcel.",
  paymentLegend: "Payment",
  payCard: "Credit card",
  payAtPickup: "Pay at pickup",
  payAtPickupNote: "You pay at the store when you collect. No card is charged online.",
  payAtPickupTotal: (amount: string) => `Pay at pickup ${amount}`,
  recipientName: "Recipient name",
  recipientNameReal: "Recipient real name (same as ID)",
  phone: "Mobile",
  phoneReal: "Mobile 09xxxxxxxx",
  recipientRules:
    "Use your real name: no digits or symbols, 4–10 characters wide (Chinese characters count 2). Mobile must be 09 followed by 8 digits.",
  // map mode
  pickStore: "Choose store",
  changeStore: "Change store",
  goingToMap: "Opening the store map…",
  mapNote: "The store map opens in this tab and returns here. Your name and mobile are kept until you return.",
  verifying: "Checking your store…",
  storeChosen: "Store chosen from the chain's map",
  outside: "Outlying island",
  storeName: "Store name",
  storeCode: "Store code",
  storeAddress: "Address",
  // buyer-entered mode
  enteredLabel: "Store you entered",
  enteredIntro:
    "Find your store on the chain's official site, then type its number, name and address here.",
  enteredCode: "Store number",
  enteredName: "Store name",
  enteredAddress: "Store address",
  enteredNote:
    "We only check the format. Make sure the store exists and is open; the seller will check before shipping.",
  searchLink: "Find your store number on the official site",
  codeHint: {
    cvs_711: "6 digits",
    cvs_familymart: "6 digits",
    cvs_hilife: "3–8 digits",
    cvs_okmart: "4 digits",
  } as Record<CvsKind, string>,
  consent: "The recipient's name and mobile are shared with the carrier and store for pickup notices.",
  confirmPickup: "Confirm pickup details",
  confirmedPickup: "Pickup store confirmed. Editing any field requires confirmation again.",
  createCard: "Create unpaid order",
  createPickup: "Place pay-at-pickup order",
  noStoreYet: "Choose or enter a store first.",
  // notices
  retryLater: (seconds: number) =>
    `The store list is busy. Try again in about ${seconds} seconds.`,
  retry: "Check again",
  rejected: "We could not confirm that store. Choose the store again.",
  expired: "The store selection expired. Choose the store again.",
  mismatch: "That store belongs to another chain. Choose the store again.",
  noSession:
    "Continue in your browser: this page was opened in an app whose browsing session was not kept. Open this page in your phone's browser and choose the store again.",
  copyLink: "Copy page link",
  copied: "Link copied",
  copyFailed: "Copy failed. Select the address bar and copy it.",
  openFailed: "The store map could not be opened. Try again.",
  invalidRecipient: "Check the recipient name and mobile number.",
  invalidStore: "Check the store number, name and address.",
  unavailable: "This pickup option is not available right now.",
  errors: {
    bad_return_path: "This page cannot receive the store choice. Reload and try again.",
    bad_return_origin: "This page cannot receive the store choice. Reload and try again.",
    service_unavailable: "This chain is not available right now. Choose another delivery option.",
    selection_replay_new_key: "That store choice was already used. Choose the store again.",
    bad_store_code: "The store number does not match this chain's format.",
    bad_store_name: "Enter the store name (up to 40 characters).",
    bad_store_address: "Enter the store address (5–120 characters).",
    cvs_recipient_rejected:
      "The recipient name or mobile number was refused. Use your real name and a 09 mobile number.",
    cvs_amount_exceeds: "This order is above the convenience-store limit (NT$20,000).",
    cvs_environment_mismatch: "This store cannot be used with the current store setup. Choose again.",
    cvs_source_mismatch: "This store choice no longer matches the seller's setup. Choose the store again.",
    pay_at_pickup_unavailable: "Pay at pickup is not available for this store or chain.",
    pay_at_pickup_amount_exceeds: "This order is above the seller's pay-at-pickup limit.",
    pay_at_pickup_limit: "The seller has too many unpaid pickup orders right now. Try again later or pay by card.",
  } as Record<CvsErrorCode, string>,
  // order page (§5.3, §16.4, §16.8)
  pickupSection: "Store pickup",
  shipmentTitle: "Pickup progress",
  shipmentStates: {
    processing: "Processing",
    CREATED: "The seller created the store shipment",
    AT_DC: "At the logistics center",
    AT_STORE: "Arrived at the store. Please collect it",
    PICKED_UP: "Picked up",
    UNCLAIMED: "Not collected in time. Returning to the seller",
  },
  shipmentNote: "The carrier sends the arrival message. Progress may lag a few hours.",
  collection: {
    PENDING: (amount: string) => `Pay at pickup ${amount}`,
    COLLECTED: "Paid and collected",
    RETURNED: "Not collected. Returned",
    REFUNDED_OFFLINE: "Refunded by the seller outside this site",
    CANCELLED: "The seller canceled this order",
    RESTOCKED: "Not collected. Returned to the seller",
  },
  payAtPickupOrderNote:
    "No online payment is needed. Pay at the store when you collect.",
};
type Copy = typeof en;
export const cvsCopy: Record<Locale, Copy> = {
  en,
  "zh-CN": {
    chains: {
      cvs_711: "7-ELEVEN",
      cvs_familymart: "全家",
      cvs_hilife: "莱尔富",
      cvs_okmart: "OK超商",
    },
    comingSoon: "即将开放",
    title: "取货门店",
    intro: "请选择你要取货的门店。",
    paymentLegend: "付款方式",
    payCard: "信用卡",
    payAtPickup: "取货付款",
    payAtPickupNote: "到店取货时再付款，不会在线扣款。",
    payAtPickupTotal: (amount) => `取货付款 ${amount}`,
    recipientName: "收件人",
    recipientNameReal: "取件人真实姓名（与证件相同）",
    phone: "手机",
    phoneReal: "手机 09xxxxxxxx",
    recipientRules:
      "请填写真实姓名：不含数字或符号，宽度 4–10（中文字算 2）。手机需为 09 开头共 10 位数字。",
    pickStore: "选择门市",
    changeStore: "更换门市",
    goingToMap: "正在打开门市地图…",
    mapNote: "门市地图会在本页打开，选完后回到这里。回来前会暂存你的姓名与手机。",
    verifying: "正在确认你选的门市…",
    storeChosen: "已从超商地图选取的门市",
    outside: "离岛",
    storeName: "门市名称",
    storeCode: "门市店号",
    storeAddress: "地址",
    enteredLabel: "你填写的门市",
    enteredIntro: "请到超商官网查询门市，再把店号、店名和地址填在这里。",
    enteredCode: "店号",
    enteredName: "店名",
    enteredAddress: "门市地址",
    enteredNote: "我们只检查格式。请确认门市存在且营业中，卖家出货前也会核对。",
    searchLink: "到官网查询店号",
    codeHint: {
      cvs_711: "6 位数字",
      cvs_familymart: "6 位数字",
      cvs_hilife: "3–8 位数字",
      cvs_okmart: "4 位数字",
    },
    consent: "取件人姓名与手机将提供给物流商与门店，用于通知与取货。",
    confirmPickup: "确认取货信息",
    confirmedPickup: "取货门市已确认。修改任一字段后，需要重新确认。",
    createCard: "创建未付款订单",
    createPickup: "提交取货付款订单",
    noStoreYet: "请先选择或填写门市。",
    retryLater: (seconds) => `门市名单暂时忙碌，请约 ${seconds} 秒后再试。`,
    retry: "重新确认",
    rejected: "无法确认该门市，请重新选择门市。",
    expired: "门市选择已过期，请重新选择门市。",
    mismatch: "该门市属于其他超商品牌，请重新选择门市。",
    noSession:
      "请在浏览器中继续：此页面在未保留浏览会话的 App 中打开。请用手机浏览器打开本页，再重新选择门市。",
    copyLink: "复制页面链接",
    copied: "已复制链接",
    copyFailed: "复制失败，请选取地址栏后手动复制。",
    openFailed: "无法打开门市地图，请重试。",
    invalidRecipient: "请检查收件人姓名与手机号码。",
    invalidStore: "请检查店号、店名与地址。",
    unavailable: "此取货方式暂时无法使用。",
    errors: {
      bad_return_path: "此页面无法接收门市选择，请重新加载后再试。",
      bad_return_origin: "此页面无法接收门市选择，请重新加载后再试。",
      service_unavailable: "此超商暂时无法使用，请改选其他配送方式。",
      selection_replay_new_key: "该门市选择已使用过，请重新选择门市。",
      bad_store_code: "店号不符合该超商的格式。",
      bad_store_name: "请填写店名（最多 40 个字）。",
      bad_store_address: "请填写门市地址（5–120 个字）。",
      cvs_recipient_rejected: "收件人姓名或手机被拒绝，请填写真实姓名与 09 开头的手机。",
      cvs_amount_exceeds: "订单金额超过超商上限（NT$20,000）。",
      cvs_environment_mismatch: "该门市无法用于当前店铺设置，请重新选择。",
      cvs_source_mismatch: "该门市选择与卖家设置不再相符，请重新选择门市。",
      pay_at_pickup_unavailable: "此店铺或超商暂不支持取货付款。",
      pay_at_pickup_amount_exceeds: "订单金额超过卖家设定的取货付款上限。",
      pay_at_pickup_limit: "卖家目前的未取货订单过多，请稍后再试或改用信用卡。",
    },
    pickupSection: "门店取货",
    shipmentTitle: "取货进度",
    shipmentStates: {
      processing: "处理中",
      CREATED: "卖家已建立超商寄件",
      AT_DC: "已到物流中心",
      AT_STORE: "已到店，请取货",
      PICKED_UP: "已取货",
      UNCLAIMED: "逾期未取，退回中",
    },
    shipmentNote: "到店通知由物流商发送，进度可能延迟数小时。",
    collection: {
      PENDING: (amount) => `取货时付款 ${amount}`,
      COLLECTED: "已取货付款",
      RETURNED: "未取货，已退回",
      REFUNDED_OFFLINE: "卖家已在本站外退款",
      CANCELLED: "卖家已取消订单",
      RESTOCKED: "未取货，已退回",
    },
    payAtPickupOrderNote: "无需在线付款，到店取货时再付款。",
  },
  "zh-TW": {
    chains: {
      cvs_711: "7-ELEVEN",
      cvs_familymart: "全家",
      cvs_hilife: "萊爾富",
      cvs_okmart: "OK超商",
    },
    comingSoon: "即將開放",
    title: "取貨門市",
    intro: "請選擇你要取貨的門市。",
    paymentLegend: "付款方式",
    payCard: "信用卡",
    payAtPickup: "取貨付款",
    payAtPickupNote: "到店取貨時再付款，不會線上扣款。",
    payAtPickupTotal: (amount) => `取貨付款 ${amount}`,
    recipientName: "收件人",
    recipientNameReal: "取件人真實姓名（與證件相同）",
    phone: "手機",
    phoneReal: "手機 09xxxxxxxx",
    recipientRules:
      "請填寫真實姓名：不含數字或符號，寬度 4–10（中文字算 2）。手機需為 09 開頭共 10 碼數字。",
    pickStore: "選擇門市",
    changeStore: "更換門市",
    goingToMap: "正在開啟門市地圖…",
    mapNote: "門市地圖會在本頁開啟，選完後回到這裡。回來前會暫存你的姓名與手機。",
    verifying: "正在確認你選的門市…",
    storeChosen: "已從超商地圖選取的門市",
    outside: "離島",
    storeName: "門市名稱",
    storeCode: "門市店號",
    storeAddress: "地址",
    enteredLabel: "你填寫的門市",
    enteredIntro: "請到超商官網查詢門市，再把店號、店名和地址填在這裡。",
    enteredCode: "店號",
    enteredName: "店名",
    enteredAddress: "門市地址",
    enteredNote: "我們只檢查格式。請確認門市存在且營業中，賣家出貨前也會核對。",
    searchLink: "到官網查詢店號",
    codeHint: {
      cvs_711: "6 碼數字",
      cvs_familymart: "6 碼數字",
      cvs_hilife: "3–8 碼數字",
      cvs_okmart: "4 碼數字",
    },
    consent: "取件人姓名與手機將提供給物流商與門市，用於通知與取貨。",
    confirmPickup: "確認取貨資訊",
    confirmedPickup: "取貨門市已確認。修改任一欄位後，需要重新確認。",
    createCard: "建立未付款訂單",
    createPickup: "送出取貨付款訂單",
    noStoreYet: "請先選擇或填寫門市。",
    retryLater: (seconds) => `門市名單暫時忙碌，請約 ${seconds} 秒後再試。`,
    retry: "重新確認",
    rejected: "無法確認該門市，請重新選擇門市。",
    expired: "門市選擇已過期，請重新選擇門市。",
    mismatch: "該門市屬於其他超商品牌，請重新選擇門市。",
    noSession:
      "請在瀏覽器中繼續：此頁面在未保留瀏覽工作階段的 App 中開啟。請用手機瀏覽器開啟本頁，再重新選擇門市。",
    copyLink: "複製頁面連結",
    copied: "已複製連結",
    copyFailed: "複製失敗，請選取網址列後手動複製。",
    openFailed: "無法開啟門市地圖，請重試。",
    invalidRecipient: "請檢查收件人姓名與手機號碼。",
    invalidStore: "請檢查店號、店名與地址。",
    unavailable: "此取貨方式暫時無法使用。",
    errors: {
      bad_return_path: "此頁面無法接收門市選擇，請重新載入後再試。",
      bad_return_origin: "此頁面無法接收門市選擇，請重新載入後再試。",
      service_unavailable: "此超商暫時無法使用，請改選其他配送方式。",
      selection_replay_new_key: "該門市選擇已使用過，請重新選擇門市。",
      bad_store_code: "店號不符合該超商的格式。",
      bad_store_name: "請填寫店名（最多 40 字）。",
      bad_store_address: "請填寫門市地址（5–120 字）。",
      cvs_recipient_rejected: "收件人姓名或手機被拒絕，請填寫真實姓名與 09 開頭的手機。",
      cvs_amount_exceeds: "訂單金額超過超商上限（NT$20,000）。",
      cvs_environment_mismatch: "該門市無法用於目前商店設定，請重新選擇。",
      cvs_source_mismatch: "該門市選擇與賣家設定不再相符，請重新選擇門市。",
      pay_at_pickup_unavailable: "此商店或超商暫不支援取貨付款。",
      pay_at_pickup_amount_exceeds: "訂單金額超過賣家設定的取貨付款上限。",
      pay_at_pickup_limit: "賣家目前的未取貨訂單過多，請稍後再試或改用信用卡。",
    },
    pickupSection: "門市取貨",
    shipmentTitle: "取貨進度",
    shipmentStates: {
      processing: "處理中",
      CREATED: "賣家已建立超商寄件",
      AT_DC: "已到物流中心",
      AT_STORE: "已到店，請取貨",
      PICKED_UP: "已取貨",
      UNCLAIMED: "逾期未取，退回中",
    },
    shipmentNote: "到店通知由物流業者發送，進度可能延遲數小時。",
    collection: {
      PENDING: (amount) => `取貨時付款 ${amount}`,
      COLLECTED: "已取貨付款",
      RETURNED: "未取貨，已退回",
      REFUNDED_OFFLINE: "賣家已在本站外退款",
      CANCELLED: "賣家已取消訂單",
      RESTOCKED: "未取貨，已退回",
    },
    payAtPickupOrderNote: "無需線上付款，到店取貨時再付款。",
  },
};
