// Copy for the buyer privacy surfaces: the two checkout consent boxes (ConsentChoices), the /{locale}/privacy page
// (PrivacyCenter) and the public /{locale}/data-deletion instructions page (customers-billing-v1 §5, U7/U8, storefront
// locales zh-CN / zh-TW / en). Owns the notice text that LC_PRIVACY_POLICY_VERSION labels: a change to the notice
// wording must bump that constant (lib/privacy-contract.ts) in the same change.
// Non-goals: no legal review (the policy content owner is LQ7), no consent logic. Depends on: @live-commerce/i18n (Locale).
import type { Locale } from "@live-commerce/i18n";

const en = {
  // Checkout boxes (U7): both unticked; the ads box carries the purchase-events disclosure.
  choicesLegend: "Optional messages and ads",
  choicesIntro: "These are optional. Your order does not depend on them, and you can change them any time on the privacy page.",
  marketing: "The store may send me marketing messages on Messenger or Instagram DM.",
  ads: "Use my purchase to personalize Meta ads for me.",
  adsDisclosure:
    "If you tick this, this order's purchase event (order value and currency, linked to your browser signals) is sent to Meta to measure and personalize ads. Events already sent cannot be recalled.",
  noticeLink: "Privacy notice",
  noticeVersion: (version: string) => `version ${version}`,
  consentSaveFailed: "Your order was created. We could not save your optional choices; you can set them on the privacy page.",
  // Privacy page (U8)
  title: "Your privacy",
  intro: "See what this store may do with your data, change your choices, download a copy, or erase your data.",
  language: "Language",
  loading: "Loading your privacy settings…",
  failed: "Your privacy settings are unavailable right now. Try again.",
  reload: "Try again",
  session: "Your session ended. Renew it to continue.",
  renew: "Renew session",
  choicesTitle: "Your choices",
  granted: "On",
  notGranted: "Off",
  toggleOn: "Turn on",
  toggleOff: "Turn off",
  saved: "Your choice was saved.",
  saveFailed: "Your choice could not be saved. It is unchanged; try again.",
  historyNote:
    "Turning ads personalization off stops future events. Events already sent to Meta cannot be recalled.",
  downloadTitle: "Download my data",
  downloadText: "Get a file with your orders, consents and privacy actions held by this store.",
  download: "Download my data",
  downloading: "Preparing…",
  downloaded: "Your file was downloaded.",
  exportTooLarge: "Your data is too large for one file. Contact the store for a copy.",
  eraseTitle: "Erase my data",
  eraseText:
    "Erasing removes your name, phone and address from saved orders, ends your sessions here and withdraws your choices.",
  eraseKept:
    "The store keeps order, payment and shipping records for legal retention and may still contact you about existing orders.",
  erase: "Erase my data…",
  eraseDialogTitle: "Erase your data?",
  eraseType: "Type ERASE to confirm",
  eraseConfirm: "Erase my data",
  erasing: "Erasing…",
  retrySame: "Retry same request",
  cancel: "Cancel",
  uncertain: "The result is unknown. Retry the same request; it will not run twice.",
  eraseBlocked: "You have a payment that may still be open (up to 40 minutes). Try again later.",
  conflict: "That request conflicts with an earlier one. Reload and try again.",
  genericFailure: "This could not be completed. Try again.",
  erasedTitle: "Your data was erased",
  erasedText:
    "Your personal details were removed from this store's saved orders and your choices were withdrawn. The store keeps order, payment and shipping records for legal retention and may still contact you about existing orders.",
  noticeTitle: "Privacy notice",
  noticeItems: [
    "This store uses your name, phone, address and order history to sell to you and deliver your orders.",
    "With your permission, it may message you about offers on Messenger or Instagram DM.",
    "With your permission, purchase events may be sent to Meta to measure and personalize ads. Events already sent cannot be recalled.",
    "Turning a choice off never affects an existing order.",
  ],
  // Data deletion instructions (public; Meta App Review URL)
  deletionTitle: "Data deletion instructions",
  deletionIntro:
    "You can remove the connection between your Facebook or Instagram account and this service, and you can erase the data the store holds about you.",
  deletionStepsTitle: "Remove the app from Facebook or Instagram",
  deletionSteps: [
    "In Facebook, open Settings, then Apps and Websites. In Instagram, open Settings, then Apps and Websites.",
    "Find this app in the list and choose Remove.",
    "Once removed, this service can no longer receive new activity from your account.",
  ],
  deletionStoreTitle: "Erase data held by the store",
  deletionStoreText:
    "If you placed an order, open the privacy page on the device you ordered from and choose Erase my data. If you cannot, ask the store you bought from to handle your request.",
  deletionKept:
    "Order, payment and shipping records are kept for legal retention, and the store may still contact you about existing orders.",
  deletionLink: "Open the privacy page",
};
export type PrivacyCopy = typeof en;

export const privacyCopy: Record<Locale, PrivacyCopy> = {
  en,
  "zh-CN": {
    choicesLegend: "可选的消息与广告",
    choicesIntro: "以下均为可选项，不影响你的订单，你随时可以在隐私页面更改。",
    marketing: "允许店铺通过 Messenger 或 Instagram 私信向我发送营销消息。",
    ads: "使用我的购买记录为我个性化 Meta 广告。",
    adsDisclosure:
      "勾选后，本订单的购买事件（订单金额与币种，并关联你的浏览器信号）会发送给 Meta，用于衡量和个性化广告。已发送的事件无法撤回。",
    noticeLink: "隐私声明",
    noticeVersion: (version: string) => `版本 ${version}`,
    consentSaveFailed: "订单已创建。我们未能保存你的可选选择，你可以到隐私页面设置。",
    title: "你的隐私",
    intro: "查看本店可能如何使用你的数据，更改你的选择，下载副本，或抹除你的数据。",
    language: "语言",
    loading: "正在加载你的隐私设置…",
    failed: "暂时无法读取你的隐私设置，请重试。",
    reload: "重试",
    session: "你的会话已结束，请续期后继续。",
    renew: "续期会话",
    choicesTitle: "你的选择",
    granted: "已开启",
    notGranted: "已关闭",
    toggleOn: "开启",
    toggleOff: "关闭",
    saved: "已保存你的选择。",
    saveFailed: "未能保存你的选择，设置保持不变，请重试。",
    historyNote: "关闭广告个性化会停止后续事件；已发送给 Meta 的事件无法撤回。",
    downloadTitle: "下载我的数据",
    downloadText: "获取一份文件，包含本店持有的你的订单、授权与隐私操作。",
    download: "下载我的数据",
    downloading: "准备中…",
    downloaded: "文件已下载。",
    exportTooLarge: "你的数据过多，无法放入一个文件。请联系店铺索取副本。",
    eraseTitle: "抹除我的数据",
    eraseText: "抹除会移除已保存订单中的姓名、手机与地址，结束你在此处的会话，并撤回你的选择。",
    eraseKept: "店铺会按法定保存要求保留订单、付款与出货记录，并仍可能就现有订单联系你。",
    erase: "抹除我的数据…",
    eraseDialogTitle: "抹除你的数据？",
    eraseType: "输入 ERASE 以确认",
    eraseConfirm: "抹除我的数据",
    erasing: "抹除中…",
    retrySame: "重试同一请求",
    cancel: "取消",
    uncertain: "结果未知。请重试同一请求，不会重复执行。",
    eraseBlocked: "你可能有尚未结束的付款（最长 40 分钟），请稍后再试。",
    conflict: "此请求与之前的请求冲突，请重新加载后再试。",
    genericFailure: "无法完成，请重试。",
    erasedTitle: "你的数据已被抹除",
    erasedText:
      "你的个人信息已从本店已保存的订单中移除，你的选择也已撤回。店铺会按法定保存要求保留订单、付款与出货记录，并仍可能就现有订单联系你。",
    noticeTitle: "隐私声明",
    noticeItems: [
      "本店使用你的姓名、手机、地址与订单记录向你销售并配送订单。",
      "经你许可，店铺可能通过 Messenger 或 Instagram 私信向你发送优惠消息。",
      "经你许可，购买事件可能发送给 Meta，用于衡量和个性化广告；已发送的事件无法撤回。",
      "关闭任何选择都不会影响现有订单。",
    ],
    deletionTitle: "数据删除说明",
    deletionIntro: "你可以解除你的 Facebook 或 Instagram 账号与本服务的连接，也可以抹除店铺持有的关于你的数据。",
    deletionStepsTitle: "在 Facebook 或 Instagram 中移除应用",
    deletionSteps: [
      "在 Facebook 中打开“设置”，进入“应用和网站”；在 Instagram 中打开“设置”，进入“应用和网站”。",
      "在列表中找到本应用并选择“移除”。",
      "移除后，本服务将不再接收来自你账号的新活动。",
    ],
    deletionStoreTitle: "抹除店铺持有的数据",
    deletionStoreText: "如果你下过订单，请在下单所用的设备上打开隐私页面并选择“抹除我的数据”。若无法操作，请联系你购买的店铺处理你的请求。",
    deletionKept: "订单、付款与出货记录会按法定保存要求保留，店铺仍可能就现有订单联系你。",
    deletionLink: "打开隐私页面",
  },
  "zh-TW": {
    choicesLegend: "選填的訊息與廣告",
    choicesIntro: "以下皆為選填，不影響你的訂單，你隨時可以在隱私頁面更改。",
    marketing: "允許店鋪透過 Messenger 或 Instagram 私訊向我發送行銷訊息。",
    ads: "使用我的購買紀錄為我個人化 Meta 廣告。",
    adsDisclosure:
      "勾選後，本訂單的購買事件（訂單金額與幣別，並關聯你的瀏覽器訊號）會傳送給 Meta，用於衡量和個人化廣告。已傳送的事件無法撤回。",
    noticeLink: "隱私聲明",
    noticeVersion: (version: string) => `版本 ${version}`,
    consentSaveFailed: "訂單已建立。我們未能儲存你的選填選擇，你可以到隱私頁面設定。",
    title: "你的隱私",
    intro: "查看本店可能如何使用你的資料，更改你的選擇，下載副本，或抹除你的資料。",
    language: "語言",
    loading: "正在載入你的隱私設定…",
    failed: "暫時無法讀取你的隱私設定，請重試。",
    reload: "重試",
    session: "你的工作階段已結束，請續期後繼續。",
    renew: "續期工作階段",
    choicesTitle: "你的選擇",
    granted: "已開啟",
    notGranted: "已關閉",
    toggleOn: "開啟",
    toggleOff: "關閉",
    saved: "已儲存你的選擇。",
    saveFailed: "未能儲存你的選擇，設定維持不變，請重試。",
    historyNote: "關閉廣告個人化會停止後續事件；已傳送給 Meta 的事件無法撤回。",
    downloadTitle: "下載我的資料",
    downloadText: "取得一份檔案，包含本店持有的你的訂單、授權與隱私操作。",
    download: "下載我的資料",
    downloading: "準備中…",
    downloaded: "檔案已下載。",
    exportTooLarge: "你的資料過多，無法放入一個檔案。請聯絡店鋪索取副本。",
    eraseTitle: "抹除我的資料",
    eraseText: "抹除會移除已儲存訂單中的姓名、手機與地址，結束你在此處的工作階段，並撤回你的選擇。",
    eraseKept: "店鋪會依法定保存要求保留訂單、付款與出貨紀錄，並仍可能就現有訂單聯絡你。",
    erase: "抹除我的資料…",
    eraseDialogTitle: "抹除你的資料？",
    eraseType: "輸入 ERASE 以確認",
    eraseConfirm: "抹除我的資料",
    erasing: "抹除中…",
    retrySame: "重試同一請求",
    cancel: "取消",
    uncertain: "結果未知。請重試同一請求，不會重複執行。",
    eraseBlocked: "你可能有尚未結束的付款（最長 40 分鐘），請稍後再試。",
    conflict: "此請求與先前的請求衝突，請重新載入後再試。",
    genericFailure: "無法完成，請重試。",
    erasedTitle: "你的資料已被抹除",
    erasedText:
      "你的個人資料已從本店已儲存的訂單中移除，你的選擇也已撤回。店鋪會依法定保存要求保留訂單、付款與出貨紀錄，並仍可能就現有訂單聯絡你。",
    noticeTitle: "隱私聲明",
    noticeItems: [
      "本店使用你的姓名、手機、地址與訂單紀錄向你銷售並配送訂單。",
      "經你許可，店鋪可能透過 Messenger 或 Instagram 私訊向你發送優惠訊息。",
      "經你許可，購買事件可能傳送給 Meta，用於衡量和個人化廣告；已傳送的事件無法撤回。",
      "關閉任何選擇都不會影響現有訂單。",
    ],
    deletionTitle: "資料刪除說明",
    deletionIntro: "你可以解除你的 Facebook 或 Instagram 帳號與本服務的連結，也可以抹除店鋪持有的關於你的資料。",
    deletionStepsTitle: "在 Facebook 或 Instagram 中移除應用程式",
    deletionSteps: [
      "在 Facebook 中開啟「設定」，進入「應用程式和網站」；在 Instagram 中開啟「設定」，進入「應用程式和網站」。",
      "在清單中找到本應用程式並選擇「移除」。",
      "移除後，本服務將不再接收來自你帳號的新活動。",
    ],
    deletionStoreTitle: "抹除店鋪持有的資料",
    deletionStoreText: "如果你下過訂單，請在下單所用的裝置上開啟隱私頁面並選擇「抹除我的資料」。若無法操作，請聯絡你購買的店鋪處理你的請求。",
    deletionKept: "訂單、付款與出貨紀錄會依法定保存要求保留，店鋪仍可能就現有訂單聯絡你。",
    deletionLink: "開啟隱私頁面",
  },
};
