import type { Locale } from "@live-commerce/i18n";

const en = {
  demonstration: "Synthetic data · test environment",
  viewQuote: "View quotation",
  changeDelivery: "Change delivery",
  unpaid: "Not paid",
  store: "Storefront",
  language: "Language",
  loading: "Loading product…",
  empty: "This product is not available.",
  choose: "Choose an option",
  quantity: "Quantity",
  decrease: "Decrease quantity",
  increase: "Increase quantity",
  subtotal: "Product subtotal",
  shippingLater: "Delivery confirmed next",
  delivery: "Choose delivery",
  more: "Load more options",
  retry: "Retry",
  failed:
    "We could not confirm the result. Retry to recover the same request; do not start another purchase.",
  session:
    "This shopping session needs to be renewed. Your previous order is not canceled by renewal.",
  renew: "Renew shopping session",
  conflict:
    "Your cart or delivery settings changed. Reload the latest information and confirm your choices again.",
  savedCart:
    "Other items in your cart will be kept and included in the quotation.",
  deliveryTitle: "Delivery and quotation",
  selectDelivery: "Delivery method",
  quote: "Get current total",
  noDelivery: "No delivery method is available for this cart.",
  cvs: "You will choose your pickup store and payment method in the next step.",
  lines: "Items in this quotation",
  total: "Total",
  shipping: "Delivery",
  taxes: "Tax",
  discount: "Discount",
  expires: "Quote valid until",
  noPayment:
    "No payment has been taken. Confirm your address below before creating an unpaid order.",
  pending: "A previous request needs recovery before continuing.",
  recover: "Recover previous request",
  amountInvalid: "Choose a valid quantity within the purchase amount limit.",
};
type Copy = { [K in keyof typeof en]: string };
export const purchaseCopy: Record<Locale, Copy> = {
  en,
  "zh-CN": {
    demonstration: "示意数据 · 测试环境",
    viewQuote: "查看报价",
    changeDelivery: "重新选择配送",
    unpaid: "尚未付款",
    store: "店铺",
    language: "语言",
    loading: "正在加载商品…",
    empty: "此商品暂不可购买。",
    choose: "选择款式",
    quantity: "数量",
    decrease: "减少数量",
    increase: "增加数量",
    subtotal: "商品小计",
    shippingLater: "运费于下一步确认",
    delivery: "选择配送",
    more: "加载更多款式",
    retry: "重试",
    failed: "暂未确认结果。请重试以恢复同一笔请求，不要重新发起购买。",
    session: "购物会话需要更新。更新会话不会取消此前已创建的订单。",
    renew: "更新购物会话",
    conflict: "购物车或配送设置已变更。请重新加载最新信息，再确认选择。",
    savedCart: "购物车内其他商品将保留，并一同计入报价。",
    deliveryTitle: "配送与报价",
    selectDelivery: "配送方式",
    quote: "获取当前总额",
    noDelivery: "此购物车暂无可用的配送方式。",
    cvs: "取货门店与付款方式将在下一步选择。",
    lines: "本次报价商品",
    total: "合计",
    shipping: "运费",
    taxes: "税额",
    discount: "优惠",
    expires: "报价有效期至",
    noPayment: "尚未收款。请在下方确认收货信息，再创建未付款订单。",
    pending: "请先恢复上一笔结果未确认的请求。",
    recover: "恢复上一笔请求",
    amountInvalid: "请选择有效数量，且商品金额不得超过购买限额。",
  },
  "zh-TW": {
    demonstration: "示意資料 · 測試環境",
    viewQuote: "查看報價",
    changeDelivery: "重新選擇配送",
    unpaid: "尚未付款",
    store: "店舖",
    language: "語言",
    loading: "正在載入商品…",
    empty: "此商品暫不可購買。",
    choose: "選擇款式",
    quantity: "數量",
    decrease: "減少數量",
    increase: "增加數量",
    subtotal: "商品小計",
    shippingLater: "運費於下一步確認",
    delivery: "選擇配送",
    more: "載入更多款式",
    retry: "重試",
    failed: "暫未確認結果。請重試以恢復同一筆請求，不要重新發起購買。",
    session: "購物工作階段需要更新。更新不會取消先前已建立的訂單。",
    renew: "更新購物工作階段",
    conflict: "購物車或配送設定已變更。請重新載入最新資訊，再確認選擇。",
    savedCart: "購物車內其他商品將保留，並一同計入報價。",
    deliveryTitle: "配送與報價",
    selectDelivery: "配送方式",
    quote: "取得目前總額",
    noDelivery: "此購物車暫無可用的配送方式。",
    cvs: "取貨門市與付款方式將在下一步選擇。",
    lines: "本次報價商品",
    total: "合計",
    shipping: "運費",
    taxes: "稅額",
    discount: "優惠",
    expires: "報價有效期限",
    noPayment: "尚未收款。請在下方確認收件資訊，再建立未付款訂單。",
    pending: "請先恢復上一筆結果未確認的請求。",
    recover: "恢復上一筆請求",
    amountInvalid: "請選擇有效數量，且商品金額不得超過購買限額。",
  },
};
