// Copy for the admin ads page (components/Ads.tsx; BFF `/api/stores/{store}/ads/*` and `/api/ads/meta/*` -> Go internal/httpapi/ads.go).
// zh-TW is the primary locale (U8), zh-CN and en follow. Every frozen error code has a line in `errors` (the type
// forces all three locales to carry the same keys). Wording rules: ruling O4 (allowance off), O6 (consent lives in
// the customers UI, not here), §12 (a budget is never described as a real-time hard stop), X7 (no "resume").
import type { Locale } from "@live-commerce/i18n";
import type { AdsCode, ConnectError, DraftStatus } from "./ads-model.ts";

const en = {
  title: "Ads",
  subtitle: "Connect a Meta ad account, prepare a boosted post or product-traffic campaign, approve it, and read the results.",
  store: "Store",
  refresh: "Refresh",
  loading: "Loading ads…",
  signedOut: "Sign in to manage ads.",
  forbidden: "This account does not have permission to manage ads.",
  unavailable: "Ads are temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  cancel: "Cancel",
  close: "Close",
  sending: "Working…",
  sandboxBanner: "Sandbox — no delivery. Nothing created here reaches real people and nothing is spent.",
  allowanceOff: "Ads are off for this store until the platform enables them.",
  allowanceLine: (amount: string) => `Approved lifetime budgets across this store's ads are capped at ${amount}.`,
  budgetNote: "A Meta budget is not a real-time hard stop: delivery can slightly overshoot and figures refresh with a delay. Pause an ad to stop it.",
  // connection
  connTitle: "Meta connection",
  connEmpty: "No Meta ad account is connected yet.",
  connectButton: "Connect a Meta ad account",
  connecting: "Opening Meta…",
  connectHint: "You sign in on Meta's own page. This site never sees your Meta password or access token.",
  connAccount: "Ad account",
  connDataset: "Dataset",
  connBusiness: "Business",
  connAt: "Connected",
  connEnabled: "Enabled",
  connDisabled: "Disabled",
  identitiesTitle: "Pages and Instagram accounts available for boosting",
  identitiesEmpty: "No Facebook Page or Instagram account is connected for this store.",
  providers: { facebook: "Facebook Page", instagram: "Instagram", meta_ads: "Meta ad account", meta_dataset: "Meta dataset" } as Record<string, string>,
  pickTitle: "Choose the ad account to use",
  pickAccounts: "Ad accounts",
  pickDatasets: "Dataset for purchase events (optional)",
  pickNoDataset: "No dataset",
  pickNoAccounts: "Meta returned no ad accounts for this login.",
  pickSubmit: "Connect this account",
  pickExpired: "This connection attempt expired or was already used. Start again.",
  startAgain: "Start again",
  accountReady: "Active",
  accountStatus: (n: number): string => (n === 1 ? "Active" : n === 2 ? "Disabled" : n === 3 ? "Payment unsettled" : n === 7 ? "Risk review" : n === 9 ? "Grace period" : n === 100 || n === 101 ? "Closing or closed" : `Status ${n}`),
  connected: "Connected. The ad account is now available to drafts.",
  connectErrors: {
    state_mismatch: "This connection attempt does not belong to this session or store. Start again.",
    state_expired: "The connection attempt expired. Start again.",
    meta_connect_failed: "Meta could not complete the connection. Start again in a moment.",
    denied: "The connection was cancelled on Meta.",
    invalid_request: "The return from Meta was not valid. Start again.",
    forbidden: "This account cannot connect ad accounts for this store.",
    unavailable: "The connection could not be completed right now. Start again.",
  } as Record<ConnectError, string>,
  // drafts
  draftsTitle: "Ad drafts",
  draftsEmpty: "No drafts yet.",
  newDraft: "New draft",
  colTemplate: "Template",
  colBudget: "Lifetime budget",
  colSchedule: "Schedule",
  colStatus: "Status",
  colCreated: "Created",
  select: "Open",
  templates: { BOOST_POST: "Boost a post", PRODUCT_TRAFFIC: "Product traffic" },
  // form
  formNew: "New ad draft",
  formEdit: "Edit draft",
  formCopy: "New draft from a paused ad",
  fTemplate: "Template",
  fAdAccount: "Ad account",
  fIdentity: "Facebook Page or Instagram account",
  fIdentityFacebookOnly: "Facebook Page (required for product traffic)",
  fSource: "Post id, Instagram media id or product id",
  fSourceBoost: "A Facebook post id (page_post) or an Instagram media id, from an account connected above.",
  fSourceProduct: "The product id of a published product in this store.",
  fBudget: (currency: string) => `Lifetime budget (${currency}, whole units)`,
  fBudgetHint: (currency: string): string => (currency === "TWD" ? "Whole NT$ only; for example 300." : "Up to two decimals; for example 12.50."),
  fStarts: "Starts",
  fEnds: "Ends",
  fDatesHint: "Local time. Start at least 10 minutes from now; run at most 30 days.",
  fCountries: "Countries",
  fCountriesHint: "Two-letter codes separated by commas; default TW.",
  fAgeMin: "Minimum age",
  fAgeMax: "Maximum age",
  fPlacement: "Placements are chosen automatically by Meta.",
  fNoAccount: "Connect an ad account first.",
  fNoIdentity: "No connected Page or Instagram account fits this template.",
  save: "Save draft",
  saving: "Saving…",
  saved: "Draft saved. The list shows the server's copy.",
  fixFields: "Fix these before saving:",
  // detail
  detailTitle: "Draft",
  budget: "Lifetime budget",
  starts: "Starts",
  ends: "Ends",
  countries: "Countries",
  ages: "Ages",
  source: "Source",
  revision: "Revision",
  attempt: "Publish attempt",
  remote: "Meta objects",
  remoteCampaign: "Campaign",
  remoteAdset: "Ad set",
  remoteCreative: "Creative",
  remoteAd: "Ad",
  remoteNone: "Nothing created on Meta yet.",
  opsTitle: "Steps sent to Meta",
  opsEmpty: "No steps yet.",
  opKind: "Step",
  opAttempt: "Attempt",
  opState: "State",
  opUpdated: "Updated",
  opStates: {
    READY: "Queued", DISPATCHING: "Sending", UNKNOWN: "Result unknown", ACKNOWLEDGED: "Accepted", SUCCEEDED: "Done",
    FAILED_FINAL: "Failed", CANCELLED: "Cancelled", BLOCKED_POLICY: "Blocked by a rule", STALE_BINDING: "Connection changed",
  },
  adsManager: "Open in Ads Manager",
  checkAdsManager: "The result of a step is unknown. Check Ads Manager for the real state of this ad, and pause it here if in doubt.",
  // actions
  edit: "Edit",
  approve: "Approve",
  publish: "Publish",
  republish: "Publish again",
  pause: "Pause",
  end: "End",
  copy: "Copy to new draft",
  endConfirmTitle: "End this ad permanently?",
  endConfirmBody: "An ended ad is paused on Meta and cannot be started again. To run it again, copy it into a new draft.",
  endConfirm: "End ad",
  copyHint: "A paused ad never starts again. A new draft needs its own approval before it can run.",
  approveOffHint: "Ads are off for this store, so approval is unavailable.",
  approved: "Approved for this revision.",
  published: "Publishing started. Steps below show the server's progress.",
  paused: "Pause requested. Steps below show the server's progress.",
  ended: "The ad was ended.",
  uncertain: "The result is not confirmed. Retrying safely sends the same request; or refresh to see the server state.",
  retrySame: "Retry the same request",
  // status
  statuses: {
    DRAFT: "Draft", APPROVED: "Approved", SUBMITTING: "Being created on Meta", REMOTE_PAUSED: "Created, paused", ACTIVE: "Active",
    PAUSED: "Paused", UNKNOWN: "Check Ads Manager", FAILED: "Failed", ENDED: "Ended", REJECTED: "Rejected by Meta",
  } as Record<DraftStatus, string>,
  // report
  reportTitle: "Results",
  reportFrom: "From",
  reportTo: "To",
  reportLoad: "Show results",
  reportLoading: "Loading results…",
  reportWindow: "Window",
  reportTimezone: "Time zone",
  reportFetched: "Fetched",
  reportNotFetched: "Not fetched yet",
  reportInvalid: "Choose dates in order, at most 92 days apart.",
  reportRefreshNote: "Meta figures refresh with a delay and can still change for a few days. They are not a real-time hard stop for spend.",
  reportSeparate: "These are three separate measures from three sources. They are not added together and no combined return figure is shown.",
  blockOrders: "Orders, net of refunds",
  blockOrdersSub: "Your own paid orders in this window minus refunds.",
  blockDelivery: "Meta delivery",
  blockDeliverySub: "What Meta says it delivered and charged.",
  blockReported: "Purchases reported by Meta",
  blockReportedSub: "Meta's own attribution; it can differ from your orders.",
  notAvailable: "Not available",
  captured: "Paid",
  refunded: "Refunded",
  net: "Net",
  spend: "Spend",
  impressions: "Impressions",
  clicks: "Clicks",
  purchases: "Purchases",
  purchaseValue: "Purchase value",
  finalThrough: "Final through",
  cardOnly: "Card payments only; pay-at-pickup orders are not counted.",
  // capi
  capiTitle: "Purchase events (Conversions API)",
  capiIntro: "Send purchase events for paid orders to a Meta dataset so Meta can measure and optimize ads.",
  capiConsent: "Events are sent only for buyers whose consent is recorded.",
  capiEnable: "Send purchase events",
  capiDataset: "Dataset",
  capiNoDataset: "No dataset",
  capiTest: "Test event code (optional)",
  capiTestHint: "Only for Meta's test tool; leave empty for real events.",
  capiSave: "Save",
  capiSaved: "Saved.",
  capiInvalid: "Choose a dataset when events are on; the test code may use letters, digits, - and _.",
  capiNoneConnected: "Connect a dataset with an ad account to turn this on.",
  // errors: every frozen code + session/BFF codes + local rule codes
  errors: {
    state_mismatch: "This connection attempt does not belong to this session or store. Start again.",
    state_expired: "The connection attempt expired. Start again.",
    meta_connect_failed: "Meta could not complete the connection. Try again in a moment.",
    not_in_pick_list: "That ad account or dataset was not offered by Meta for this login. Start the connection again.",
    client_business_changed: "This ad account now belongs to a different Meta business than the one first connected. Contact support.",
    revision_changed: "The draft changed since you loaded it. It was reloaded; review it and try again.",
    over_allowance: "This would exceed the ad budget allowance set for this store.",
    billing_restricted: "Your account has an overdue balance, so new ads cannot be approved or published. Pausing still works.",
    attempt_changed: "The publish attempt changed. The draft was reloaded; review it and try again.",
    prior_attempt_not_paused: "An earlier attempt may still be able to spend. Pause it and wait for confirmation first.",
    draft_approved: "An approved draft cannot be edited. Copy it into a new draft instead.",
    budget_below_minimum: "The budget is below what Meta requires for this schedule.",
    not_whole_unit: "This currency needs a whole-unit budget (for example NT$300, not NT$300.50).",
    currency_mismatch: "The draft currency must match the store's ad currency and the ad account's currency.",
    starts_too_soon: "The start time must be at least 10 minutes from now.",
    binding_disabled: "The connection used by this draft is disabled. Reconnect it first.",
    source_not_owned: "That post is not on the selected Page or Instagram account.",
    product_not_published: "That product is not published, or the store has no active storefront domain.",
    forbidden: "This account does not have permission for this action.",
    not_found: "This item is unavailable in the selected store.",
    invalid_request: "The request was not valid. Check the fields and try again.",
    unauthorized: "Sign in again to continue.",
    retry_later: "Temporarily unavailable. Try again.",
    rate_limited: "Too many requests. Try again in a few seconds.",
    invalid_json: "The request could not be read. Reload the page and try again.",
    json_required: "The request could not be read. Reload the page and try again.",
    method_not_allowed: "This action is not available.",
    conflict: "This conflicts with an earlier request. Refresh and try again.",
    budget_invalid: "Enter the budget as a plain number.",
    unsupported_currency: "Ads support TWD, USD and HKD budgets only.",
    ends_before_start: "The end must be after the start.",
    duration_too_long: "An ad can run at most 30 days.",
    age_invalid: "Ages must be between 18 and 65, minimum not above maximum.",
    countries_invalid: "Use one or more different two-letter country codes, separated by commas.",
    source_invalid: "The post, media or product id does not look valid.",
    bindings_missing: "Choose an ad account and a Page or Instagram account.",
    dates_invalid: "Choose a start and an end time.",
  } as Record<AdsCode, string>,
};
export type AdsCopy = typeof en;

const zhTW: AdsCopy = {
  title: "廣告",
  subtitle: "連結 Meta 廣告帳號，建立加強貼文或商品導流廣告，核准後發布並查看成效。",
  store: "商店",
  refresh: "重新整理",
  loading: "讀取廣告中…",
  signedOut: "請登入後管理廣告。",
  forbidden: "此帳號沒有管理廣告的權限。",
  unavailable: "廣告功能暫時無法使用，請重試。",
  noStore: "沒有可用的授權商店。",
  retry: "重試",
  cancel: "取消",
  close: "關閉",
  sending: "處理中…",
  sandboxBanner: "沙盒模式，不會投放。在此建立的內容不會觸及任何人，也不會花費任何費用。",
  allowanceOff: "平台啟用前，此商店的廣告功能為關閉狀態。",
  allowanceLine: (amount) => `此商店已核准廣告的總預算上限為 ${amount}。`,
  budgetNote: "Meta 預算不是即時的硬性上限：實際花費可能略為超出，數據也會延遲更新。要停止廣告請按「暫停」。",
  connTitle: "Meta 連結",
  connEmpty: "尚未連結 Meta 廣告帳號。",
  connectButton: "連結 Meta 廣告帳號",
  connecting: "正在前往 Meta…",
  connectHint: "登入在 Meta 自己的頁面完成，本網站不會取得您的 Meta 密碼或存取權杖。",
  connAccount: "廣告帳號",
  connDataset: "資料集",
  connBusiness: "商家",
  connAt: "連結時間",
  connEnabled: "已啟用",
  connDisabled: "已停用",
  identitiesTitle: "可用於加強貼文的粉絲專頁與 Instagram 帳號",
  identitiesEmpty: "此商店尚未連結任何 Facebook 粉絲專頁或 Instagram 帳號。",
  providers: { facebook: "Facebook 粉絲專頁", instagram: "Instagram", meta_ads: "Meta 廣告帳號", meta_dataset: "Meta 資料集" },
  pickTitle: "選擇要使用的廣告帳號",
  pickAccounts: "廣告帳號",
  pickDatasets: "購買事件資料集（選填）",
  pickNoDataset: "不使用資料集",
  pickNoAccounts: "Meta 沒有為此登入回傳任何廣告帳號。",
  pickSubmit: "連結此帳號",
  pickExpired: "此次連結已過期或已使用過，請重新開始。",
  startAgain: "重新開始",
  accountReady: "正常",
  accountStatus: (n) => (n === 1 ? "正常" : n === 2 ? "已停用" : n === 3 ? "款項未結清" : n === 7 ? "風險審查中" : n === 9 ? "寬限期" : n === 100 || n === 101 ? "關閉中或已關閉" : `狀態 ${n}`),
  connected: "已連結，廣告帳號現在可用於草稿。",
  connectErrors: {
    state_mismatch: "此次連結不屬於目前的登入或商店，請重新開始。",
    state_expired: "此次連結已過期，請重新開始。",
    meta_connect_failed: "Meta 無法完成連結，請稍後重新開始。",
    denied: "您已在 Meta 取消連結。",
    invalid_request: "從 Meta 返回的資料無效，請重新開始。",
    forbidden: "此帳號無法為這間商店連結廣告帳號。",
    unavailable: "目前無法完成連結，請重新開始。",
  },
  draftsTitle: "廣告草稿",
  draftsEmpty: "尚無草稿。",
  newDraft: "新增草稿",
  colTemplate: "類型",
  colBudget: "總預算",
  colSchedule: "期間",
  colStatus: "狀態",
  colCreated: "建立時間",
  select: "開啟",
  templates: { BOOST_POST: "加強貼文", PRODUCT_TRAFFIC: "商品導流" },
  formNew: "新增廣告草稿",
  formEdit: "編輯草稿",
  formCopy: "由已暫停的廣告建立新草稿",
  fTemplate: "類型",
  fAdAccount: "廣告帳號",
  fIdentity: "Facebook 粉絲專頁或 Instagram 帳號",
  fIdentityFacebookOnly: "Facebook 粉絲專頁（商品導流必填）",
  fSource: "貼文編號、Instagram 貼文編號或商品編號",
  fSourceBoost: "上方已連結帳號的 Facebook 貼文編號（頁面編號_貼文編號）或 Instagram 貼文編號。",
  fSourceProduct: "此商店已上架商品的商品編號。",
  fBudget: (currency) => `總預算（${currency}，整數單位）`,
  fBudgetHint: (currency) => (currency === "TWD" ? "僅限整數新台幣，例如 300。" : "最多兩位小數，例如 12.50。"),
  fStarts: "開始時間",
  fEnds: "結束時間",
  fDatesHint: "以本機時間計。開始時間須在 10 分鐘之後，最長刊登 30 天。",
  fCountries: "國家／地區",
  fCountriesHint: "兩位字母代碼，以逗號分隔；預設 TW。",
  fAgeMin: "最低年齡",
  fAgeMax: "最高年齡",
  fPlacement: "廣告版位由 Meta 自動選擇。",
  fNoAccount: "請先連結廣告帳號。",
  fNoIdentity: "沒有符合此類型的已連結粉絲專頁或 Instagram 帳號。",
  save: "儲存草稿",
  saving: "儲存中…",
  saved: "草稿已儲存，列表顯示的是伺服器上的內容。",
  fixFields: "請先修正以下項目：",
  detailTitle: "草稿",
  budget: "總預算",
  starts: "開始",
  ends: "結束",
  countries: "國家／地區",
  ages: "年齡",
  source: "來源",
  revision: "版本",
  attempt: "發布次數",
  remote: "Meta 上的物件",
  remoteCampaign: "廣告活動",
  remoteAdset: "廣告組合",
  remoteCreative: "廣告素材",
  remoteAd: "廣告",
  remoteNone: "尚未在 Meta 建立任何物件。",
  opsTitle: "送往 Meta 的步驟",
  opsEmpty: "尚無步驟。",
  opKind: "步驟",
  opAttempt: "次數",
  opState: "狀態",
  opUpdated: "更新時間",
  opStates: {
    READY: "排隊中", DISPATCHING: "送出中", UNKNOWN: "結果未知", ACKNOWLEDGED: "已接受", SUCCEEDED: "完成",
    FAILED_FINAL: "失敗", CANCELLED: "已取消", BLOCKED_POLICY: "被規則攔下", STALE_BINDING: "連結已變更",
  },
  adsManager: "在 Ads Manager 開啟",
  checkAdsManager: "某個步驟的結果未知。請到 Ads Manager 確認此廣告的實際狀態，有疑慮時請在此暫停。",
  edit: "編輯",
  approve: "核准",
  publish: "發布",
  republish: "重新發布",
  pause: "暫停",
  end: "結束",
  copy: "複製為新草稿",
  endConfirmTitle: "要永久結束這則廣告嗎？",
  endConfirmBody: "結束後的廣告會在 Meta 上暫停，且無法再啟動。若要再次刊登，請複製為新草稿。",
  endConfirm: "結束廣告",
  copyHint: "已暫停的廣告不會再啟動。新草稿需要重新核准才能刊登。",
  approveOffHint: "此商店的廣告功能為關閉狀態，無法核准。",
  approved: "已核准此版本。",
  published: "已開始發布，下方步驟顯示伺服器的進度。",
  paused: "已要求暫停，下方步驟顯示伺服器的進度。",
  ended: "廣告已結束。",
  uncertain: "結果尚未確認。重試會安全地送出相同請求，或重新整理查看伺服器狀態。",
  retrySame: "重試相同請求",
  statuses: {
    DRAFT: "草稿", APPROVED: "已核准", SUBMITTING: "正在 Meta 建立", REMOTE_PAUSED: "已建立·暫停中", ACTIVE: "刊登中",
    PAUSED: "已暫停", UNKNOWN: "請查看 Ads Manager", FAILED: "失敗", ENDED: "已結束", REJECTED: "遭 Meta 拒絕",
  },
  reportTitle: "成效",
  reportFrom: "起",
  reportTo: "迄",
  reportLoad: "顯示成效",
  reportLoading: "讀取成效中…",
  reportWindow: "區間",
  reportTimezone: "時區",
  reportFetched: "擷取時間",
  reportNotFetched: "尚未擷取",
  reportInvalid: "請依序選擇日期，最多相隔 92 天。",
  reportRefreshNote: "Meta 數據會延遲更新，且數天內仍可能變動；這不是即時的花費硬性上限。",
  reportSeparate: "以下是來自三個來源的三項獨立指標，不會相加，也不提供合併的報酬率數字。",
  blockOrders: "訂單（扣除退款後）",
  blockOrdersSub: "此區間內您自己的已付款訂單減去退款。",
  blockDelivery: "Meta 投放",
  blockDeliverySub: "Meta 表示已投放與收費的內容。",
  blockReported: "Meta 回報的購買",
  blockReportedSub: "Meta 自己的歸因，可能與您的訂單不同。",
  notAvailable: "無法取得",
  captured: "已付款",
  refunded: "已退款",
  net: "淨額",
  spend: "花費",
  impressions: "曝光",
  clicks: "點擊",
  purchases: "購買數",
  purchaseValue: "購買金額",
  finalThrough: "數據定案至",
  cardOnly: "僅計信用卡付款；超商取貨付款的訂單不計入。",
  capiTitle: "購買事件（Conversions API）",
  capiIntro: "將已付款訂單的購買事件傳送到 Meta 資料集，讓 Meta 衡量並最佳化廣告。",
  capiConsent: "只會傳送已記錄同意的買家的事件。",
  capiEnable: "傳送購買事件",
  capiDataset: "資料集",
  capiNoDataset: "不使用資料集",
  capiTest: "測試事件代碼（選填）",
  capiTestHint: "僅供 Meta 測試工具使用；正式事件請留空。",
  capiSave: "儲存",
  capiSaved: "已儲存。",
  capiInvalid: "開啟時請選擇資料集；測試代碼只能包含字母、數字、- 與 _。",
  capiNoneConnected: "請先連結廣告帳號與資料集才能開啟。",
  errors: {
    state_mismatch: "此次連結不屬於目前的登入或商店，請重新開始。",
    state_expired: "此次連結已過期，請重新開始。",
    meta_connect_failed: "Meta 無法完成連結，請稍後再試。",
    not_in_pick_list: "Meta 沒有為此次登入提供該廣告帳號或資料集，請重新開始連結。",
    client_business_changed: "此廣告帳號目前屬於與最初連結不同的 Meta 商家，請聯絡支援。",
    revision_changed: "草稿在您讀取後已變更，已重新載入；請檢查後再試。",
    over_allowance: "這會超過此商店的廣告預算上限。",
    billing_restricted: "您的帳戶有逾期款項，暫時無法核准或發布新廣告；暫停功能仍可使用。",
    attempt_changed: "發布次數已變更，草稿已重新載入；請檢查後再試。",
    prior_attempt_not_paused: "先前的發布可能仍會花費，請先暫停並等待確認。",
    draft_approved: "已核准的草稿無法編輯，請複製為新草稿。",
    budget_below_minimum: "預算低於 Meta 對此期間的最低要求。",
    not_whole_unit: "此幣別的預算須為整數單位（例如 NT$300，不能是 NT$300.50）。",
    currency_mismatch: "草稿幣別須與商店廣告幣別及廣告帳號幣別一致。",
    starts_too_soon: "開始時間須在 10 分鐘之後。",
    binding_disabled: "此草稿使用的連結已停用，請先重新連結。",
    source_not_owned: "該貼文不屬於所選的粉絲專頁或 Instagram 帳號。",
    product_not_published: "該商品未上架，或商店沒有啟用中的店面網域。",
    forbidden: "此帳號沒有此操作的權限。",
    not_found: "所選商店中無法讀取此項目。",
    invalid_request: "請求無效，請檢查欄位後重試。",
    unauthorized: "請重新登入後繼續。",
    retry_later: "暫時無法使用，請重試。",
    rate_limited: "請求過多，請幾秒後再試。",
    invalid_json: "請求無法讀取，請重新載入頁面後再試。",
    json_required: "請求無法讀取，請重新載入頁面後再試。",
    method_not_allowed: "此操作不可用。",
    conflict: "此請求與先前的請求衝突，請重新整理後再試。",
    budget_invalid: "預算請輸入純數字。",
    unsupported_currency: "廣告僅支援 TWD、USD 與 HKD 的預算。",
    ends_before_start: "結束時間須晚於開始時間。",
    duration_too_long: "廣告最長可刊登 30 天。",
    age_invalid: "年齡須介於 18 到 65，且最低不得高於最高。",
    countries_invalid: "請輸入一個以上不重複的兩位字母國家代碼，以逗號分隔。",
    source_invalid: "貼文、貼文編號或商品編號格式看起來不正確。",
    bindings_missing: "請選擇廣告帳號與粉絲專頁或 Instagram 帳號。",
    dates_invalid: "請選擇開始與結束時間。",
  },
};

const zhCN: AdsCopy = {
  title: "广告",
  subtitle: "连接 Meta 广告账号，创建加强帖文或商品导流广告，审批后发布并查看效果。",
  store: "店铺",
  refresh: "刷新",
  loading: "正在读取广告…",
  signedOut: "请登录后管理广告。",
  forbidden: "此账号没有管理广告的权限。",
  unavailable: "广告功能暂时无法使用，请重试。",
  noStore: "没有可用的授权店铺。",
  retry: "重试",
  cancel: "取消",
  close: "关闭",
  sending: "处理中…",
  sandboxBanner: "沙盒模式，不会投放。在此创建的内容不会触达任何人，也不会产生任何费用。",
  allowanceOff: "平台启用前，此店铺的广告功能处于关闭状态。",
  allowanceLine: (amount) => `此店铺已审批广告的总预算上限为 ${amount}。`,
  budgetNote: "Meta 预算不是实时的硬性上限：实际花费可能略有超出，数据也会延迟更新。要停止广告请点“暂停”。",
  connTitle: "Meta 连接",
  connEmpty: "尚未连接 Meta 广告账号。",
  connectButton: "连接 Meta 广告账号",
  connecting: "正在前往 Meta…",
  connectHint: "登录在 Meta 自己的页面完成，本网站不会获取您的 Meta 密码或访问令牌。",
  connAccount: "广告账号",
  connDataset: "数据集",
  connBusiness: "商家",
  connAt: "连接时间",
  connEnabled: "已启用",
  connDisabled: "已停用",
  identitiesTitle: "可用于加强帖文的主页与 Instagram 账号",
  identitiesEmpty: "此店铺尚未连接任何 Facebook 主页或 Instagram 账号。",
  providers: { facebook: "Facebook 主页", instagram: "Instagram", meta_ads: "Meta 广告账号", meta_dataset: "Meta 数据集" },
  pickTitle: "选择要使用的广告账号",
  pickAccounts: "广告账号",
  pickDatasets: "购买事件数据集（选填）",
  pickNoDataset: "不使用数据集",
  pickNoAccounts: "Meta 没有为此登录返回任何广告账号。",
  pickSubmit: "连接此账号",
  pickExpired: "此次连接已过期或已使用过，请重新开始。",
  startAgain: "重新开始",
  accountReady: "正常",
  accountStatus: (n) => (n === 1 ? "正常" : n === 2 ? "已停用" : n === 3 ? "款项未结清" : n === 7 ? "风险审核中" : n === 9 ? "宽限期" : n === 100 || n === 101 ? "关闭中或已关闭" : `状态 ${n}`),
  connected: "已连接，广告账号现在可用于草稿。",
  connectErrors: {
    state_mismatch: "此次连接不属于当前的登录或店铺，请重新开始。",
    state_expired: "此次连接已过期，请重新开始。",
    meta_connect_failed: "Meta 无法完成连接，请稍后重新开始。",
    denied: "您已在 Meta 取消连接。",
    invalid_request: "从 Meta 返回的数据无效，请重新开始。",
    forbidden: "此账号无法为这家店铺连接广告账号。",
    unavailable: "目前无法完成连接，请重新开始。",
  },
  draftsTitle: "广告草稿",
  draftsEmpty: "暂无草稿。",
  newDraft: "新建草稿",
  colTemplate: "类型",
  colBudget: "总预算",
  colSchedule: "时间",
  colStatus: "状态",
  colCreated: "创建时间",
  select: "打开",
  templates: { BOOST_POST: "加强帖文", PRODUCT_TRAFFIC: "商品导流" },
  formNew: "新建广告草稿",
  formEdit: "编辑草稿",
  formCopy: "由已暂停的广告创建新草稿",
  fTemplate: "类型",
  fAdAccount: "广告账号",
  fIdentity: "Facebook 主页或 Instagram 账号",
  fIdentityFacebookOnly: "Facebook 主页（商品导流必填）",
  fSource: "帖文编号、Instagram 帖文编号或商品编号",
  fSourceBoost: "上方已连接账号的 Facebook 帖文编号（主页编号_帖文编号）或 Instagram 帖文编号。",
  fSourceProduct: "此店铺已上架商品的商品编号。",
  fBudget: (currency) => `总预算（${currency}，整数单位）`,
  fBudgetHint: (currency) => (currency === "TWD" ? "仅限整数新台币，例如 300。" : "最多两位小数，例如 12.50。"),
  fStarts: "开始时间",
  fEnds: "结束时间",
  fDatesHint: "按本机时间。开始时间须在 10 分钟之后，最长投放 30 天。",
  fCountries: "国家／地区",
  fCountriesHint: "两位字母代码，以逗号分隔；默认 TW。",
  fAgeMin: "最低年龄",
  fAgeMax: "最高年龄",
  fPlacement: "广告版位由 Meta 自动选择。",
  fNoAccount: "请先连接广告账号。",
  fNoIdentity: "没有符合此类型的已连接主页或 Instagram 账号。",
  save: "保存草稿",
  saving: "保存中…",
  saved: "草稿已保存，列表显示的是服务器上的内容。",
  fixFields: "请先修正以下项目：",
  detailTitle: "草稿",
  budget: "总预算",
  starts: "开始",
  ends: "结束",
  countries: "国家／地区",
  ages: "年龄",
  source: "来源",
  revision: "版本",
  attempt: "发布次数",
  remote: "Meta 上的对象",
  remoteCampaign: "广告系列",
  remoteAdset: "广告组",
  remoteCreative: "广告素材",
  remoteAd: "广告",
  remoteNone: "尚未在 Meta 创建任何对象。",
  opsTitle: "发往 Meta 的步骤",
  opsEmpty: "暂无步骤。",
  opKind: "步骤",
  opAttempt: "次数",
  opState: "状态",
  opUpdated: "更新时间",
  opStates: {
    READY: "排队中", DISPATCHING: "发送中", UNKNOWN: "结果未知", ACKNOWLEDGED: "已接受", SUCCEEDED: "完成",
    FAILED_FINAL: "失败", CANCELLED: "已取消", BLOCKED_POLICY: "被规则拦下", STALE_BINDING: "连接已变更",
  },
  adsManager: "在 Ads Manager 打开",
  checkAdsManager: "某个步骤的结果未知。请到 Ads Manager 确认此广告的实际状态，有疑虑时请在此暂停。",
  edit: "编辑",
  approve: "审批",
  publish: "发布",
  republish: "重新发布",
  pause: "暂停",
  end: "结束",
  copy: "复制为新草稿",
  endConfirmTitle: "要永久结束这条广告吗？",
  endConfirmBody: "结束后的广告会在 Meta 上暂停，且无法再启动。若要再次投放，请复制为新草稿。",
  endConfirm: "结束广告",
  copyHint: "已暂停的广告不会再启动。新草稿需要重新审批才能投放。",
  approveOffHint: "此店铺的广告功能处于关闭状态，无法审批。",
  approved: "已审批此版本。",
  published: "已开始发布，下方步骤显示服务器的进度。",
  paused: "已请求暂停，下方步骤显示服务器的进度。",
  ended: "广告已结束。",
  uncertain: "结果尚未确认。重试会安全地发送相同请求，或刷新查看服务器状态。",
  retrySame: "重试相同请求",
  statuses: {
    DRAFT: "草稿", APPROVED: "已审批", SUBMITTING: "正在 Meta 创建", REMOTE_PAUSED: "已创建·暂停中", ACTIVE: "投放中",
    PAUSED: "已暂停", UNKNOWN: "请查看 Ads Manager", FAILED: "失败", ENDED: "已结束", REJECTED: "被 Meta 拒绝",
  },
  reportTitle: "效果",
  reportFrom: "起",
  reportTo: "止",
  reportLoad: "显示效果",
  reportLoading: "正在读取效果…",
  reportWindow: "区间",
  reportTimezone: "时区",
  reportFetched: "获取时间",
  reportNotFetched: "尚未获取",
  reportInvalid: "请按先后顺序选择日期，最多相隔 92 天。",
  reportRefreshNote: "Meta 数据会延迟更新，且几天内仍可能变动；这不是实时的花费硬性上限。",
  reportSeparate: "以下是来自三个来源的三项独立指标，不会相加，也不提供合并的回报率数字。",
  blockOrders: "订单（扣除退款后）",
  blockOrdersSub: "此区间内您自己的已付款订单减去退款。",
  blockDelivery: "Meta 投放",
  blockDeliverySub: "Meta 表示已投放与收费的内容。",
  blockReported: "Meta 报告的购买",
  blockReportedSub: "Meta 自己的归因，可能与您的订单不同。",
  notAvailable: "无法获取",
  captured: "已付款",
  refunded: "已退款",
  net: "净额",
  spend: "花费",
  impressions: "曝光",
  clicks: "点击",
  purchases: "购买数",
  purchaseValue: "购买金额",
  finalThrough: "数据定稿至",
  cardOnly: "仅统计银行卡付款；超商取货付款的订单不计入。",
  capiTitle: "购买事件（Conversions API）",
  capiIntro: "将已付款订单的购买事件发送到 Meta 数据集，让 Meta 衡量并优化广告。",
  capiConsent: "只会发送已记录同意的买家的事件。",
  capiEnable: "发送购买事件",
  capiDataset: "数据集",
  capiNoDataset: "不使用数据集",
  capiTest: "测试事件代码（选填）",
  capiTestHint: "仅供 Meta 测试工具使用；正式事件请留空。",
  capiSave: "保存",
  capiSaved: "已保存。",
  capiInvalid: "开启时请选择数据集；测试代码只能包含字母、数字、- 与 _。",
  capiNoneConnected: "请先连接广告账号与数据集才能开启。",
  errors: {
    state_mismatch: "此次连接不属于当前的登录或店铺，请重新开始。",
    state_expired: "此次连接已过期，请重新开始。",
    meta_connect_failed: "Meta 无法完成连接，请稍后再试。",
    not_in_pick_list: "Meta 没有为此次登录提供该广告账号或数据集，请重新开始连接。",
    client_business_changed: "此广告账号目前属于与最初连接不同的 Meta 商家，请联系支持。",
    revision_changed: "草稿在您读取后已变更，已重新加载；请检查后再试。",
    over_allowance: "这会超过此店铺的广告预算上限。",
    billing_restricted: "您的账户有逾期款项，暂时无法审批或发布新广告；暂停功能仍可使用。",
    attempt_changed: "发布次数已变更，草稿已重新加载；请检查后再试。",
    prior_attempt_not_paused: "之前的发布可能仍会花费，请先暂停并等待确认。",
    draft_approved: "已审批的草稿无法编辑，请复制为新草稿。",
    budget_below_minimum: "预算低于 Meta 对此期间的最低要求。",
    not_whole_unit: "此币种的预算须为整数单位（例如 NT$300，不能是 NT$300.50）。",
    currency_mismatch: "草稿币种须与店铺广告币种及广告账号币种一致。",
    starts_too_soon: "开始时间须在 10 分钟之后。",
    binding_disabled: "此草稿使用的连接已停用，请先重新连接。",
    source_not_owned: "该帖文不属于所选的主页或 Instagram 账号。",
    product_not_published: "该商品未上架，或店铺没有启用中的店面域名。",
    forbidden: "此账号没有此操作的权限。",
    not_found: "所选店铺中无法读取此项目。",
    invalid_request: "请求无效，请检查字段后重试。",
    unauthorized: "请重新登录后继续。",
    retry_later: "暂时无法使用，请重试。",
    rate_limited: "请求过多，请几秒后再试。",
    invalid_json: "请求无法读取，请重新加载页面后再试。",
    json_required: "请求无法读取，请重新加载页面后再试。",
    method_not_allowed: "此操作不可用。",
    conflict: "此请求与之前的请求冲突，请刷新后再试。",
    budget_invalid: "预算请输入纯数字。",
    unsupported_currency: "广告仅支持 TWD、USD 与 HKD 的预算。",
    ends_before_start: "结束时间须晚于开始时间。",
    duration_too_long: "广告最长可投放 30 天。",
    age_invalid: "年龄须介于 18 到 65，且最低不得高于最高。",
    countries_invalid: "请输入一个以上不重复的两位字母国家代码，以逗号分隔。",
    source_invalid: "帖文、帖文编号或商品编号格式看起来不正确。",
    bindings_missing: "请选择广告账号与主页或 Instagram 账号。",
    dates_invalid: "请选择开始与结束时间。",
  },
};

export const adsCopy: Record<Locale, AdsCopy> = { en, "zh-TW": zhTW, "zh-CN": zhCN };
/** Text for any code the server or BFF may return; unknown codes degrade to the generic retry line. */
export const errorText = (c: AdsCopy, code: string) => (c.errors as Record<string, string>)[code] ?? c.errors.retry_later;
