// Copy for the admin Billing page and the standing banner (BFF billing*, billing/standing -> Go internal/httpapi/billing.go;
// contract customers-billing-v1 §5, U4/U5, locales zh-CN / zh-TW / en). Owns every string of both components and the
// error map for the frozen billing codes (subscription_exists, no_billing_customer, billing_unavailable).
// Non-goals: no price formatting (component uses Intl), no rule about standing (the server derives it, BD4).
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Billing",
  subtitle: "Your platform subscription, payment method and usage for this store.",
  store: "Store",
  loading: "Loading billing…",
  signedOut: "Sign in to manage billing.",
  forbidden: "This account does not have permission to manage billing.",
  notFound: "Billing is unavailable for this store.",
  unavailable: "Billing is temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  refresh: "Refresh",
  testNote: "Test mode: checkout uses Stripe's test environment and no real card is charged.",
  stale: "Showing saved data because Stripe could not be reached just now.",
  standingTitle: "Standing",
  standing: {
    GOOD: "In good standing",
    GRACE: "Payment overdue",
    RESTRICTED: "Restricted",
    UNBILLED: "No subscription",
  } as Record<string, string>,
  standingText: {
    GOOD: "Your subscription is active.",
    GRACE: "The last payment failed. Update your payment method before the retries run out.",
    RESTRICTED: "New claim windows can't be opened until payment is fixed. Orders, refunds, shipping and privacy actions keep working.",
    UNBILLED: "This store has no subscription. Nothing is restricted.",
  } as Record<string, string>,
  paymentPending: "Your payment is still being confirmed. This page updates when it is.",
  checkoutDone: "Payment received. Updating your subscription…",
  checkoutDoneSlow: "Your subscription is still updating. Refresh in a moment.",
  checkoutCancel: "Checkout was cancelled. Nothing was charged.",
  subscriptionsTitle: "Subscription",
  subscriptionsNone: "No subscription yet.",
  status: "Status",
  period: "Current period (UTC)",
  renews: "Renews",
  endsAtPeriodEnd: "Ends at the end of the period",
  plan: "Plan",
  subStatus: {
    incomplete: "Payment incomplete",
    incomplete_expired: "Expired before payment",
    trialing: "Trial",
    active: "Active",
    past_due: "Past due",
    canceled: "Canceled",
    unpaid: "Unpaid",
    paused: "Paused",
  } as Record<string, string>,
  plansTitle: "Plans",
  plansNone: "No plan is available to choose right now.",
  plansHave: "This store already has a subscription. Manage it below.",
  per: { day: "day", week: "week", month: "month", year: "year" } as Record<string, string>,
  choose: "Subscribe",
  choosing: "Opening Stripe…",
  portal: "Manage payment & invoices",
  portalOpening: "Opening Stripe…",
  portalHint: "Opens Stripe's hosted page where you can change your card, see invoices and cancel.",
  usageTitle: "Usage this period",
  usagePeriod: "Period (UTC)",
  paidOrders: "Paid orders",
  claimWindows: "Claim windows opened",
  privateReplies: "Private replies sent",
  members: "Team members",
  errors: {
    default: "This could not be completed. Try again.",
    unauthorized: "Your session changed. Reload the page and sign in again.",
    forbidden: "This account does not have permission to manage billing.",
    subscription_exists: "This store already has a subscription. Use “Manage payment & invoices”.",
    no_billing_customer: "There is no billing account yet. Subscribe to a plan first.",
    billing_unavailable: "Billing is not available on this platform right now.",
    unprocessable: "That plan is not available.",
    invalid_request: "That plan is not available.",
    rate_limited: "Too many requests. Wait a moment and try again.",
    retry_later: "Stripe did not answer. Try again.",
  } as Record<string, string>,
  bannerGrace: "Your last payment failed. Update your payment method to avoid restrictions.",
  bannerRestricted:
    "Your subscription is restricted: new claim windows can't be opened. Orders, refunds and shipping keep working.",
  bannerLink: "Go to billing",
  bannerLabel: "Billing notice",
};
export type BillingCopy = typeof en;

export const billingCopy: Record<Locale, BillingCopy> = {
  en,
  "zh-CN": {
    title: "账单",
    subtitle: "本店的平台订阅、付款方式与用量。",
    store: "店铺",
    loading: "正在加载账单…",
    signedOut: "请登录后管理账单。",
    forbidden: "此账号无权管理账单。",
    notFound: "此店铺的账单不可用。",
    unavailable: "账单暂时无法使用，请重试。",
    noStore: "没有可用的授权店铺。",
    retry: "重试",
    refresh: "刷新",
    testNote: "测试模式：结账使用 Stripe 测试环境，不会扣取真实银行卡。",
    stale: "暂时无法连接 Stripe，显示的是已保存的数据。",
    standingTitle: "账户状态",
    standing: { GOOD: "状态良好", GRACE: "付款逾期", RESTRICTED: "已受限", UNBILLED: "未订阅" },
    standingText: {
      GOOD: "你的订阅有效。",
      GRACE: "最近一次付款失败。请在重试结束前更新付款方式。",
      RESTRICTED: "付款恢复前无法开启新的登记窗口。订单、退款、出货与隐私操作不受影响。",
      UNBILLED: "本店没有订阅，不受任何限制。",
    },
    paymentPending: "付款仍在确认中，确认后本页会自动更新。",
    checkoutDone: "已收到付款，正在更新订阅…",
    checkoutDoneSlow: "订阅仍在更新，请稍后刷新。",
    checkoutCancel: "已取消结账，未扣款。",
    subscriptionsTitle: "订阅",
    subscriptionsNone: "尚未订阅。",
    status: "状态",
    period: "当前周期（UTC）",
    renews: "续订",
    endsAtPeriodEnd: "周期结束后终止",
    plan: "方案",
    subStatus: {
      incomplete: "付款未完成",
      incomplete_expired: "未付款已过期",
      trialing: "试用中",
      active: "有效",
      past_due: "逾期",
      canceled: "已取消",
      unpaid: "未付款",
      paused: "已暂停",
    },
    plansTitle: "方案",
    plansNone: "目前没有可选的方案。",
    plansHave: "本店已有订阅，请在下方管理。",
    per: { day: "天", week: "周", month: "月", year: "年" },
    choose: "订阅",
    choosing: "正在打开 Stripe…",
    portal: "管理付款与发票",
    portalOpening: "正在打开 Stripe…",
    portalHint: "打开 Stripe 托管页面，可更换银行卡、查看发票与取消订阅。",
    usageTitle: "本周期用量",
    usagePeriod: "周期（UTC）",
    paidOrders: "已付款订单",
    claimWindows: "已开启登记窗口",
    privateReplies: "已发送私信回复",
    members: "团队成员",
    errors: {
      default: "无法完成，请重试。",
      unauthorized: "登录状态已变化。请重新加载页面并再次登录。",
      forbidden: "此账号无权管理账单。",
      subscription_exists: "本店已有订阅，请使用“管理付款与发票”。",
      no_billing_customer: "尚无账单账户，请先订阅方案。",
      billing_unavailable: "平台账单功能目前不可用。",
      unprocessable: "该方案不可选。",
      invalid_request: "该方案不可选。",
      rate_limited: "请求过于频繁，请稍候再试。",
      retry_later: "Stripe 没有响应，请重试。",
    },
    bannerGrace: "最近一次付款失败。请更新付款方式，以免受到限制。",
    bannerRestricted: "你的订阅已受限：无法开启新的登记窗口。订单、退款与出货不受影响。",
    bannerLink: "前往账单",
    bannerLabel: "账单提示",
  },
  "zh-TW": {
    title: "帳單",
    subtitle: "本店的平台訂閱、付款方式與用量。",
    store: "店鋪",
    loading: "正在載入帳單…",
    signedOut: "請登入後管理帳單。",
    forbidden: "此帳號無權管理帳單。",
    notFound: "此店鋪的帳單不可用。",
    unavailable: "帳單暫時無法使用，請重試。",
    noStore: "沒有可用的授權店鋪。",
    retry: "重試",
    refresh: "重新整理",
    testNote: "測試模式：結帳使用 Stripe 測試環境，不會扣取真實信用卡。",
    stale: "暫時無法連線 Stripe，顯示的是已儲存的資料。",
    standingTitle: "帳戶狀態",
    standing: { GOOD: "狀態良好", GRACE: "付款逾期", RESTRICTED: "已受限", UNBILLED: "未訂閱" },
    standingText: {
      GOOD: "你的訂閱有效。",
      GRACE: "最近一次付款失敗。請在重試結束前更新付款方式。",
      RESTRICTED: "付款恢復前無法開啟新的登記窗口。訂單、退款、出貨與隱私操作不受影響。",
      UNBILLED: "本店沒有訂閱，不受任何限制。",
    },
    paymentPending: "付款仍在確認中，確認後本頁會自動更新。",
    checkoutDone: "已收到付款，正在更新訂閱…",
    checkoutDoneSlow: "訂閱仍在更新，請稍後重新整理。",
    checkoutCancel: "已取消結帳，未扣款。",
    subscriptionsTitle: "訂閱",
    subscriptionsNone: "尚未訂閱。",
    status: "狀態",
    period: "目前週期（UTC）",
    renews: "續訂",
    endsAtPeriodEnd: "週期結束後終止",
    plan: "方案",
    subStatus: {
      incomplete: "付款未完成",
      incomplete_expired: "未付款已過期",
      trialing: "試用中",
      active: "有效",
      past_due: "逾期",
      canceled: "已取消",
      unpaid: "未付款",
      paused: "已暫停",
    },
    plansTitle: "方案",
    plansNone: "目前沒有可選的方案。",
    plansHave: "本店已有訂閱，請在下方管理。",
    per: { day: "天", week: "週", month: "月", year: "年" },
    choose: "訂閱",
    choosing: "正在開啟 Stripe…",
    portal: "管理付款與發票",
    portalOpening: "正在開啟 Stripe…",
    portalHint: "開啟 Stripe 託管頁面，可更換信用卡、查看發票與取消訂閱。",
    usageTitle: "本週期用量",
    usagePeriod: "週期（UTC）",
    paidOrders: "已付款訂單",
    claimWindows: "已開啟登記窗口",
    privateReplies: "已發送私訊回覆",
    members: "團隊成員",
    errors: {
      default: "無法完成，請重試。",
      unauthorized: "登入狀態已變更。請重新載入頁面並再次登入。",
      forbidden: "此帳號無權管理帳單。",
      subscription_exists: "本店已有訂閱，請使用「管理付款與發票」。",
      no_billing_customer: "尚無帳單帳戶，請先訂閱方案。",
      billing_unavailable: "平台帳單功能目前不可用。",
      unprocessable: "該方案不可選。",
      invalid_request: "該方案不可選。",
      rate_limited: "請求過於頻繁，請稍候再試。",
      retry_later: "Stripe 沒有回應，請重試。",
    },
    bannerGrace: "最近一次付款失敗。請更新付款方式，以免受到限制。",
    bannerRestricted: "你的訂閱已受限：無法開啟新的登記窗口。訂單、退款與出貨不受影響。",
    bannerLink: "前往帳單",
    bannerLabel: "帳單提示",
  },
};
