// Owns every Studio › Claims string in zh-CN, zh-TW and en, including the FROZEN host
// prompt copy of contracts/live-keyword-claims-v1.md §11.1 (verbatim) and the buyer
// message that accompanies a one-time claim link. Words shared with Studio (its title,
// "Refresh facts", "Retry same request", "No authorized store") stay in studio-copy.ts.
// Non-goals: no formatting of money or time (the component uses Intl), no business rule;
// the reason names mirror the Go claims.Reason values only for display.
// Depends on: @live-commerce/i18n (Locale) and claims-model.ts (reason and mode types).

import type { Locale } from "@live-commerce/i18n";
import type { MatchMode, Reason } from "./claims-model";

const en = {
  title: "Keyword claims",
  // Ruling t: the old MOCK banner states whether comments are read automatically.
  feedNone: "Bind a Facebook or Instagram post to read comments automatically",
  feedBound: "Reading comments from the bound post",
  mockDetail: "Record what a buyer commented. Nothing is reserved, charged or sent until the buyer opens their link and checks out.",
  scene: "Scene", loading: "Loading claims…",
  window: "Claim window", open: "Open", closed: "Closed", round: "Round", openedAt: "Opened (UTC)",
  openWindow: "Open claim window", closeWindow: "Close claim window",
  mode: "Quantity rule", modeExact: "Keyword = 1 · keyword+N = N", modeQty: "Keyword+N only",
  modeLocked: "Close the window to change the quantity rule.",
  stats: "This round", accepted: "Recorded",
  reasons: {
    NO_MATCH: "Not understood", UNKNOWN_KEYWORD: "Unknown keyword", OFFER_INACTIVE: "Offer paused",
    INVALID_QUANTITY: "Invalid quantity", QUANTITY_REQUIRED: "Quantity missing",
    QUANTITY_OVER_MAX: "Over the per-claim limit", BUNDLE_LIMIT: "Buyer item limit reached",
    WINDOW_CLOSED: "Claim window closed — not recorded",
  } satisfies Record<Exclude<Reason, "">, string>,
  notUnderstood: (n: number) => `${n} not understood — pin the host prompt`,
  prompt: "Host prompt", promptLanguage: "Prompt language", promptKeyword: "Keyword",
  promptNone: "Add an active offer to build the host prompt.", copyPrompt: "Copy prompt", copied: "Copied",
  offers: "Offers", keyword: "Keyword", product: "Product", sku: "SKU", maxPerClaim: "Max per claim",
  status: "Status", actions: "Actions", active: "Active", paused: "Paused", pause: "Pause", resume: "Resume",
  saveMax: "Save limit", noOffers: "No offers yet. Add a keyword for a SKU.", addOffer: "Add offer",
  chooseProduct: "Choose a product", chooseSKU: "Choose a SKU",
  keywordHint: "1–16 letters or digits. Keywords can't be changed later; pause and add a new one to fix a typo.",
  keywordInvalid: "Enter 1–16 letters or digits.", maxInvalid: "Enter a whole number from 1 to 999.",
  skuRequired: "Choose a product and SKU.", catalogUnavailable: "Products could not be loaded.",
  noProducts: "No active products with sellable SKUs.",
  manual: "Record a comment", buyer: "Buyer", newBuyer: "New buyer…", label: "Buyer label",
  labelHint: "A display name only. Don't enter phone numbers or addresses.", comment: "Comment text",
  record: "Record comment", working: "Submitting…",
  resultAccepted: (keyword: string, quantity: number, previous: number) =>
    previous ? `Recorded: ${keyword} × ${quantity} (was ${previous})` : `Recorded: ${keyword} × ${quantity}`,
  resultRejected: (reason: string) => `Not recorded: ${reason}`,
  labelInvalid: "Enter a label of 1–60 characters without control characters.",
  textInvalid: "Enter the comment text (up to 256 bytes).",
  bundles: "Buyers and claim links", ref: "Ref", items: "Claimed items", cart: "Cart", link: "Link",
  noBundles: "No buyers yet. Accepted comments create them.", inCart: "In cart", notInCart: "Not in cart yet",
  bound: "Opened by a buyer", unbound: "Not opened yet", linkNone: "No link",
  linkActive: (time: string) => `Active until ${time} UTC`, linkExpired: "Expired", issue: "Create link",
  rotate: "Replace link", release: "Release and replace", more: "Load more",
  releaseConfirm: "Release this buyer and replace the link? The old link stops working, and the next buyer to open the new link receives every item.",
  dialog: "One-time buyer link",
  dialogHint: "This link is shown only now. Paste it into your private message to the buyer. Don't show it on a stream or screen share.",
  buyerLanguage: "Buyer language", hidden: "Link hidden", reveal: "Reveal link", hide: "Hide link",
  copyLink: "Copy link", copyMessage: "Copy message", close: "Close and discard",
  expires: (time: string) => `Expires ${time} UTC`, released: "The previous buyer was released.",
  replayed: "This link was already created, but its one-time link was not received here. Replace the link to get a new one.",
  noOrigin: "No verified, published storefront address is available.",
  readOnly: "Read-only access. Claim controls are unavailable.",
  signedOut: "Sign in again to open claims.", forbidden: "You no longer have access to this scene.",
  notFound: "This scene or buyer is unavailable in the selected store.",
  unavailable: "Claims are temporarily unavailable. Refresh and try again.",
  invalid: "The request was rejected. Check the fields and refresh.",
  uncertain: "The result is unknown. Refresh the facts; retry uses the same request key.",
  source: "Comment source",
  sourceIntro: "Paste the link or ID of the Facebook post, live video, or Instagram post or reel that this scene's comments come from.",
  sourceInput: "Post or media link or ID",
  sourceInputHint: "Facebook: a post or live-video link, or its numeric ID. Instagram: a post or reel link, or the numeric media ID. Short links such as fb.watch are not accepted.",
  sourceInputInvalid: "Enter one link or ID without spaces (up to 1024 characters).",
  sourcePrivateReply: "Send a private reply with the cart link",
  sourcePrivateReplyHint: "One private reply per recorded comment, only where Meta allows it.",
  sourceReplyLocale: "Reply language",
  sourceActive: "Collect comments from this source",
  sourceSave: "Save comment source",
  sourceNone: "No source is bound yet, so comments are not collected.",
  sourceBoundTitle: "Bound source",
  sourceObject: "Object ID",
  sourceState: "Collecting",
  sourceOn: "On",
  sourceOff: "Paused",
  sourceVerification: "Verification",
  sourceVerified: "Verified",
  sourceUnverified: "Unverified",
  sourceCount: "Comments collected",
  sourceCapped: "Skipped: intake limit reached",
  sourcePlatformLabel: "Platform",
  sourcePlatformAuto: "From the link",
  sourcePlatformHint: "Choose one for a bare numeric ID: this store has both a Facebook and an Instagram connection.",
  sourceUpdated: "Updated (UTC)",
  sourceUnavailable: "The comment source could not be loaded. Refresh to try again.",
  sourceForbidden: "You need permission to manage live scenes and integrations to change the comment source.",
  sourcePlatform: {
    facebook: "Facebook post or live video",
    instagram: "Instagram post or reel",
  },
  sourceErrors: {
    input_invalid: "This is not a supported post or media link or ID. Use a facebook.com post or video link, an instagram.com post or reel link, or a numeric ID.",
    input_unresolvable: "This Instagram link can't be converted to a media ID without reading from Instagram. Paste the numeric media ID instead.",
    binding_missing: "This store has no enabled Facebook Page or Instagram account connection for that link. Connect one in settings first.",
    binding_ambiguous: "This store has more than one enabled connection for that platform, so the source can't be chosen automatically.",
    source_conflict: "This post or media is already bound to another scene.",
    page_token_missing: "Private replies need a registered Page token for this connection. Register the Page token first, or turn private replies off.",
    version_changed: "The comment source changed since you loaded it. Refresh first.",
  },
  billingRestricted: "New claim windows can't be opened while billing is restricted. Orders, refunds and shipping are not affected.",
  billingLink: "Fix billing",
  conflict: {
    window: "The window changed, or another scene in this store already has an open window. Refresh first.",
    offer: "This keyword is already used in this scene, the SKU already has an active offer, or the SKU can't be sold now.",
    update: "The offer changed, or another active offer already uses this SKU. Refresh first.",
    manual: "This label is already used in this scene. Choose that buyer from the list.",
    link: "The link changed since you loaded it. Refresh first.",
    source: "The comment source changed since you loaded it. Refresh first.",
  },
};
export type ClaimsCopy = typeof en;

export const claimsCopy: Record<Locale, ClaimsCopy> = {
  en,
  "zh-CN": {
    title: "评论口令登记",
    feedNone: "绑定 Facebook 或 Instagram 帖子即可自动读取评论",
    feedBound: "正在读取已绑定帖子的评论",
    mockDetail: "由你代为记录买家的评论。买家打开链接并结账之前，不会保留库存、扣款或发送任何消息。",
    scene: "场次", loading: "正在读取登记…",
    window: "登记窗口", open: "开放中", closed: "已关闭", round: "轮次", openedAt: "开放时间（UTC）",
    openWindow: "开放登记窗口", closeWindow: "关闭登记窗口",
    mode: "数量规则", modeExact: "口令 = 1 件 · 口令+N = N 件", modeQty: "只接受口令+数量",
    modeLocked: "关闭窗口后才能修改数量规则。",
    stats: "本轮", accepted: "已登记",
    reasons: {
      NO_MATCH: "无法识别", UNKNOWN_KEYWORD: "没有这个口令", OFFER_INACTIVE: "商品已暂停登记",
      INVALID_QUANTITY: "数量无效", QUANTITY_REQUIRED: "缺少数量",
      QUANTITY_OVER_MAX: "超过单次上限", BUNDLE_LIMIT: "已达买家品项上限",
      WINDOW_CLOSED: "登记窗口已关闭——未记录",
    },
    notUnderstood: (n: number) => `${n} 条评论无法识别——请置顶主持人提示`,
    prompt: "主持人提示", promptLanguage: "提示语言", promptKeyword: "口令",
    promptNone: "添加一个启用中的口令后即可生成主持人提示。", copyPrompt: "复制提示", copied: "已复制",
    offers: "口令商品", keyword: "口令", product: "商品", sku: "SKU", maxPerClaim: "单次上限",
    status: "状态", actions: "操作", active: "启用中", paused: "已暂停", pause: "暂停", resume: "恢复",
    saveMax: "保存上限", noOffers: "还没有口令。为 SKU 添加一个口令。", addOffer: "添加口令",
    chooseProduct: "选择商品", chooseSKU: "选择 SKU",
    keywordHint: "1–16 个字母或数字。口令之后不能修改；打错时请暂停并新建一个。",
    keywordInvalid: "请输入 1–16 个字母或数字。", maxInvalid: "请输入 1 到 999 的整数。",
    skuRequired: "请选择商品和 SKU。", catalogUnavailable: "无法读取商品。",
    noProducts: "没有可售 SKU 的启用商品。",
    manual: "记录一条评论", buyer: "买家", newBuyer: "新买家…", label: "买家标签",
    labelHint: "只填显示名称，不要填写电话号码或地址。", comment: "评论内容",
    record: "记录评论", working: "正在提交…",
    resultAccepted: (keyword: string, quantity: number, previous: number) =>
      previous ? `已登记：${keyword} × ${quantity}（原为 ${previous}）` : `已登记：${keyword} × ${quantity}`,
    resultRejected: (reason: string) => `未登记：${reason}`,
    labelInvalid: "请输入 1–60 个字符的标签，不含控制字符。",
    textInvalid: "请输入评论内容（最多 256 字节）。",
    bundles: "买家与登记链接", ref: "编号", items: "已登记商品", cart: "购物车", link: "链接",
    noBundles: "还没有买家。被接受的评论会建立买家。", inCart: "已加入购物车", notInCart: "尚未加入购物车",
    bound: "已有买家打开", unbound: "尚未打开", linkNone: "没有链接",
    linkActive: (time: string) => `有效至 ${time} UTC`, linkExpired: "已过期", issue: "生成链接",
    rotate: "更换链接", release: "解除并更换", more: "加载更多",
    releaseConfirm: "解除此买家并更换链接？旧链接会失效，下一位打开新链接的买家会收到全部商品。",
    dialog: "一次性买家链接",
    dialogHint: "链接只在此刻显示。请粘贴到给买家的私信中，不要在直播画面或屏幕共享中显示。",
    buyerLanguage: "买家语言", hidden: "链接已隐藏", reveal: "显示链接", hide: "隐藏链接",
    copyLink: "复制链接", copyMessage: "复制消息", close: "关闭并丢弃",
    expires: (time: string) => `${time} UTC 过期`, released: "已解除之前的买家。",
    replayed: "此链接先前已生成，但一次性链接没有送达这里。请更换链接以取得新的链接。",
    noOrigin: "没有已验证且已发布的店铺前台地址。",
    readOnly: "当前为只读权限，无法操作登记。",
    signedOut: "请重新登录后查看登记。", forbidden: "当前已无权查看此场次。",
    notFound: "所选店铺中无法读取此场次或买家。",
    unavailable: "登记暂时无法读取，请刷新后重试。",
    invalid: "请求未被接受，请检查字段并刷新。",
    uncertain: "提交结果暂无法确认。请刷新事实；重试会使用同一个请求键。",
    source: "评论来源",
    sourceIntro: "粘贴本场次评论所在的 Facebook 帖子、直播视频，或 Instagram 帖子、Reel 的链接或 ID。",
    sourceInput: "帖子或媒体的链接或 ID",
    sourceInputHint: "Facebook：帖子或直播视频链接，或数字 ID。Instagram：帖子或 Reel 链接，或数字媒体 ID。不接受 fb.watch 等短链接。",
    sourceInputInvalid: "请输入一个不含空格的链接或 ID（最多 1024 个字符）。",
    sourcePrivateReply: "发送附带购物车链接的私信回复",
    sourcePrivateReplyHint: "每条已登记的评论最多一条私信回复，且仅在 Meta 允许时发送。",
    sourceReplyLocale: "回复语言",
    sourceActive: "从此来源收集评论",
    sourceSave: "保存评论来源",
    sourceNone: "尚未绑定来源，因此不会收集评论。",
    sourceBoundTitle: "已绑定的来源",
    sourceObject: "对象 ID",
    sourceState: "收集评论",
    sourceOn: "开启",
    sourceOff: "已暂停",
    sourceVerification: "验证状态",
    sourceVerified: "已验证",
    sourceUnverified: "未验证",
    sourceCount: "已收集评论",
    sourceCapped: "已略过：达到收集上限",
    sourcePlatformLabel: "平台",
    sourcePlatformAuto: "按链接判断",
    sourcePlatformHint: "只粘贴数字 ID 时请选择：本店同时连接了 Facebook 和 Instagram。",
    sourceUpdated: "更新时间（UTC）",
    sourceUnavailable: "无法读取评论来源，请刷新后重试。",
    sourceForbidden: "修改评论来源需要管理直播场次和集成的权限。",
    sourcePlatform: {
      facebook: "Facebook 帖子或直播视频",
      instagram: "Instagram 帖子或 Reel",
    },
    sourceErrors: {
      input_invalid: "不是支持的帖子或媒体链接或 ID。请使用 facebook.com 的帖子或视频链接、instagram.com 的帖子或 Reel 链接，或数字 ID。",
      input_unresolvable: "无法在不读取 Instagram 的情况下把此 Instagram 链接转换成媒体 ID。请改为粘贴数字媒体 ID。",
      binding_missing: "本店没有可用于此链接的已启用 Facebook 主页或 Instagram 账号连接。请先到设置中连接。",
      binding_ambiguous: "本店在该平台有多个已启用的连接，无法自动选定来源。",
      source_conflict: "此帖子或媒体已绑定到另一个场次。",
      page_token_missing: "私信回复需要为此连接登记主页令牌。请先登记主页令牌，或关闭私信回复。",
      version_changed: "载入后评论来源已变化。请先刷新。",
    },
    billingRestricted: "账单受限期间无法开启新的登记窗口。订单、退款与出货不受影响。",
    billingLink: "处理账单",
    conflict: {
      window: "窗口已变化，或本店另一场次已有开放中的窗口。请先刷新。",
      offer: "此口令已在本场次使用、此 SKU 已有启用中的口令，或此 SKU 目前不可售。",
      update: "口令已变化，或另一个启用中的口令已使用此 SKU。请先刷新。",
      manual: "此标签已在本场次使用。请从列表中选择该买家。",
      link: "载入后链接已变化。请先刷新。",
      source: "载入后评论来源已变化。请先刷新。",
    },
  },
  "zh-TW": {
    title: "留言關鍵字登記",
    feedNone: "綁定 Facebook 或 Instagram 貼文即可自動讀取留言",
    feedBound: "正在讀取已綁定貼文的留言",
    mockDetail: "由你代為記錄買家的留言。買家打開連結並結帳之前，不會保留庫存、扣款或傳送任何訊息。",
    scene: "場次", loading: "正在讀取登記…",
    window: "登記窗口", open: "開放中", closed: "已關閉", round: "輪次", openedAt: "開放時間（UTC）",
    openWindow: "開放登記窗口", closeWindow: "關閉登記窗口",
    mode: "數量規則", modeExact: "關鍵字 = 1 件 · 關鍵字+N = N 件", modeQty: "只接受關鍵字+數量",
    modeLocked: "關閉窗口後才能修改數量規則。",
    stats: "本輪", accepted: "已登記",
    reasons: {
      NO_MATCH: "無法辨識", UNKNOWN_KEYWORD: "沒有這個關鍵字", OFFER_INACTIVE: "商品已暫停登記",
      INVALID_QUANTITY: "數量無效", QUANTITY_REQUIRED: "缺少數量",
      QUANTITY_OVER_MAX: "超過單次上限", BUNDLE_LIMIT: "已達買家品項上限",
      WINDOW_CLOSED: "登記窗口已關閉——未記錄",
    },
    notUnderstood: (n: number) => `${n} 則留言無法辨識——請置頂主持人提示`,
    prompt: "主持人提示", promptLanguage: "提示語言", promptKeyword: "關鍵字",
    promptNone: "新增一個啟用中的關鍵字後即可產生主持人提示。", copyPrompt: "複製提示", copied: "已複製",
    offers: "關鍵字商品", keyword: "關鍵字", product: "商品", sku: "SKU", maxPerClaim: "單次上限",
    status: "狀態", actions: "操作", active: "啟用中", paused: "已暫停", pause: "暫停", resume: "恢復",
    saveMax: "儲存上限", noOffers: "還沒有關鍵字。為 SKU 新增一個關鍵字。", addOffer: "新增關鍵字",
    chooseProduct: "選擇商品", chooseSKU: "選擇 SKU",
    keywordHint: "1–16 個英文字母或數字。關鍵字之後不能修改；打錯時請暫停並新增一個。",
    keywordInvalid: "請輸入 1–16 個英文字母或數字。", maxInvalid: "請輸入 1 到 999 的整數。",
    skuRequired: "請選擇商品和 SKU。", catalogUnavailable: "無法讀取商品。",
    noProducts: "沒有可售 SKU 的啟用商品。",
    manual: "記錄一則留言", buyer: "買家", newBuyer: "新買家…", label: "買家標籤",
    labelHint: "只填顯示名稱，不要填寫電話號碼或地址。", comment: "留言內容",
    record: "記錄留言", working: "正在提交…",
    resultAccepted: (keyword: string, quantity: number, previous: number) =>
      previous ? `已登記：${keyword} × ${quantity}（原為 ${previous}）` : `已登記：${keyword} × ${quantity}`,
    resultRejected: (reason: string) => `未登記：${reason}`,
    labelInvalid: "請輸入 1–60 個字元的標籤，不含控制字元。",
    textInvalid: "請輸入留言內容（最多 256 位元組）。",
    bundles: "買家與登記連結", ref: "編號", items: "已登記商品", cart: "購物車", link: "連結",
    noBundles: "還沒有買家。被接受的留言會建立買家。", inCart: "已加入購物車", notInCart: "尚未加入購物車",
    bound: "已有買家打開", unbound: "尚未打開", linkNone: "沒有連結",
    linkActive: (time: string) => `有效至 ${time} UTC`, linkExpired: "已過期", issue: "產生連結",
    rotate: "更換連結", release: "解除並更換", more: "載入更多",
    releaseConfirm: "解除此買家並更換連結？舊連結會失效，下一位打開新連結的買家會收到全部商品。",
    dialog: "一次性買家連結",
    dialogHint: "連結只在此刻顯示。請貼到給買家的私訊中，不要在直播畫面或螢幕分享中顯示。",
    buyerLanguage: "買家語言", hidden: "連結已隱藏", reveal: "顯示連結", hide: "隱藏連結",
    copyLink: "複製連結", copyMessage: "複製訊息", close: "關閉並捨棄",
    expires: (time: string) => `${time} UTC 到期`, released: "已解除先前的買家。",
    replayed: "此連結先前已產生，但一次性連結沒有送達這裡。請更換連結以取得新的連結。",
    noOrigin: "沒有已驗證且已發布的商店前台位址。",
    readOnly: "目前為唯讀權限，無法操作登記。",
    signedOut: "請重新登入後查看登記。", forbidden: "目前已無權檢視此場次。",
    notFound: "所選商店中無法讀取此場次或買家。",
    unavailable: "登記暫時無法讀取，請重新整理後重試。",
    invalid: "請求未被接受，請檢查欄位並重新整理。",
    uncertain: "提交結果暫無法確認。請重新整理事實；重試會使用同一個請求鍵。",
    source: "留言來源",
    sourceIntro: "貼上本場次留言所在的 Facebook 貼文、直播影片，或 Instagram 貼文、Reel 的連結或 ID。",
    sourceInput: "貼文或媒體的連結或 ID",
    sourceInputHint: "Facebook：貼文或直播影片連結，或數字 ID。Instagram：貼文或 Reel 連結，或數字媒體 ID。不接受 fb.watch 等短連結。",
    sourceInputInvalid: "請輸入一個不含空格的連結或 ID（最多 1024 個字元）。",
    sourcePrivateReply: "傳送附帶購物車連結的私訊回覆",
    sourcePrivateReplyHint: "每則已登記的留言最多一則私訊回覆，且僅在 Meta 允許時傳送。",
    sourceReplyLocale: "回覆語言",
    sourceActive: "從此來源收集留言",
    sourceSave: "儲存留言來源",
    sourceNone: "尚未綁定來源，因此不會收集留言。",
    sourceBoundTitle: "已綁定的來源",
    sourceObject: "物件 ID",
    sourceState: "收集留言",
    sourceOn: "開啟",
    sourceOff: "已暫停",
    sourceVerification: "驗證狀態",
    sourceVerified: "已驗證",
    sourceUnverified: "未驗證",
    sourceCount: "已收集留言",
    sourceCapped: "已略過：達到收集上限",
    sourcePlatformLabel: "平台",
    sourcePlatformAuto: "依連結判斷",
    sourcePlatformHint: "只貼上數字 ID 時請選擇：本店同時連接了 Facebook 和 Instagram。",
    sourceUpdated: "更新時間（UTC）",
    sourceUnavailable: "無法讀取留言來源，請重新整理後重試。",
    sourceForbidden: "修改留言來源需要管理直播場次和整合的權限。",
    sourcePlatform: {
      facebook: "Facebook 貼文或直播影片",
      instagram: "Instagram 貼文或 Reel",
    },
    sourceErrors: {
      input_invalid: "不是支援的貼文或媒體連結或 ID。請使用 facebook.com 的貼文或影片連結、instagram.com 的貼文或 Reel 連結，或數字 ID。",
      input_unresolvable: "無法在不讀取 Instagram 的情況下把此 Instagram 連結轉換成媒體 ID。請改為貼上數字媒體 ID。",
      binding_missing: "本店沒有可用於此連結的已啟用 Facebook 粉絲專頁或 Instagram 帳號連線。請先到設定中連線。",
      binding_ambiguous: "本店在該平台有多個已啟用的連線，無法自動選定來源。",
      source_conflict: "此貼文或媒體已綁定到另一個場次。",
      page_token_missing: "私訊回覆需要為此連線登錄粉絲專頁權杖。請先登錄粉絲專頁權杖，或關閉私訊回覆。",
      version_changed: "載入後留言來源已變更。請先重新整理。",
    },
    billingRestricted: "帳單受限期間無法開啟新的登記窗口。訂單、退款與出貨不受影響。",
    billingLink: "處理帳單",
    conflict: {
      window: "窗口已變更，或本店另一個場次已有開放中的窗口。請先重新整理。",
      offer: "此關鍵字已在本場次使用、此 SKU 已有啟用中的關鍵字，或此 SKU 目前不可售。",
      update: "關鍵字已變更，或另一個啟用中的關鍵字已使用此 SKU。請先重新整理。",
      manual: "此標籤已在本場次使用。請從清單中選擇該買家。",
      link: "載入後連結已變更。請先重新整理。",
      source: "載入後留言來源已變更。請先重新整理。",
    },
  },
};

// FROZEN host prompt copy (contract §11.1), verbatim; {KW} is an active offer keyword.
export const hostPromptExact: Record<Locale, string> = {
  "zh-TW": "留言關鍵字就能登記：{KW} = 1 件；{KW}+2 = 數量改成 2 件（不是再加 2 件）。之後再留言，以最新數量為準。請只留關鍵字，不要加其他文字。留言不代表已保留庫存，結帳時才確認。",
  "zh-CN": "评论口令即可登记：{KW} = 1 件；{KW}+2 = 数量改成 2 件（不是再加 2 件）。再次评论以最新数量为准。请只发口令，不要加其他文字。评论不代表已保留库存，结账时才确认。",
  en: "Comment the code to claim: {KW} = 1 item; {KW}+2 = set your quantity to 2 (it does not add 2 more). Your latest comment replaces the earlier quantity. Comment only the code. Claims don't reserve stock; stock is confirmed at checkout.",
};
// KEYWORD_QTY_ONLY replaces the first clause (the text before the first semicolon) with
// the frozen replacement; the rest of the prompt stays verbatim.
const exactFirstClause: Record<Locale, string> = {
  "zh-TW": "留言關鍵字就能登記：{KW} = 1 件", "zh-CN": "评论口令即可登记：{KW} = 1 件",
  en: "Comment the code to claim: {KW} = 1 item",
};
const hostPromptQtyOnlyClause: Record<Locale, string> = {
  "zh-TW": "請留言「{KW}+數量」，例如 {KW}+1；只留 {KW} 不會登記",
  "zh-CN": "请评论“{KW}+数量”，例如 {KW}+1；只发 {KW} 不会登记",
  en: "Comment {KW}+quantity, e.g. {KW}+1; {KW} alone is not counted",
};

/** The host prompt for one language, window mode and canonical keyword. Pure. */
export function hostPrompt(language: Locale, mode: MatchMode, keyword: string) {
  const exact = hostPromptExact[language];
  const text = mode === "EXACT" ? exact
    : hostPromptQtyOnlyClause[language] + exact.slice(exactFirstClause[language].length);
  return text.replaceAll("{KW}", keyword);
}

/** The private message sent with a one-time link, in the buyer's language. Pure. */
export function claimLinkMessage(language: Locale, url: string, expires: string) {
  return language === "zh-TW" ? `你的留言登記已準備好。打開這個連結即可確認並加入購物車（有效至 ${expires} UTC）：${url}`
    : language === "zh-CN" ? `你的评论登记已准备好。打开这个链接即可确认并加入购物车（有效至 ${expires} UTC）：${url}`
    : `Your claimed items are ready. Open this link to review them and add them to your cart (valid until ${expires} UTC): ${url}`;
}
