import type { Locale } from "@live-commerce/i18n";

const en = {
  storageUnavailable:
    "Reliable command storage is unavailable. Restore browser storage before continuing; an earlier command may need recovery.",
  skuSaved: "Product and SKU saved",
  title: "Commerce workspace",
  store: "Demo store",
  user: "Merchant account",
  menu: "Open navigation",
  products: "Products",
  inventory: "Inventory",
  orders: "Orders",
  signOut: "Sign out",
  signingOut: "Signing out…",
  signOutFailed: "Could not sign out. Try again.",
  live: "Live workspace",
  siteChat: "Website service",
  meta: "Meta messages",
  ads: "Ads",
  support: "Platform support",
  settings: "Settings",
  heading: "Products & inventory",
  subtitle: "Review SKU availability and record each inventory adjustment.",
  search: "Search product name or SKU",
  searchAction: "Search",
  reset: "Reset",
  all: "All statuses",
  active: "Active",
  archived: "Archived",
  warehouse: "Warehouse",
  selectWarehouse: "Choose a warehouse",
  create: "Add product",
  product: "Product",
  price: "Price",
  onHand: "On hand",
  reserved: "Reserved",
  available: "Available",
  status: "Status",
  actions: "Actions",
  edit: "Select",
  demo: "Demo data",
  fixture: "Isolated local fixture — not customer inventory",
  notConnected: "Not connected",
  channels: "Channel status",
  website: "Storefront",
  loading: "Loading inventory…",
  empty: "No matching SKUs",
  emptyHint: "Create a product and SKU, or change the search and warehouse.",
  choose: "Select a SKU to inspect or adjust inventory.",
  adjustment: "Adjust inventory",
  quantity: "Adjustment quantity",
  reason: "Reason (required)",
  reasonHint: "Why is this inventory changing?",
  confirm: "Confirm adjustment",
  pending: "Saving…",
  success: "Inventory updated",
  cancel: "Cancel",
  selected: "Selected SKU",
  stockInfo: "Inventory",
  auditHint: "This operation records an inventory ledger entry.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  pageSize: "Rows per page",
  retry: "Retry",
  refresh: "Refresh",
  noSession: "Sign-in is not connected",
  noSessionHint:
    "This environment has no merchant session. Production access stays disabled until the identity service is configured.",
  conflict: "Inventory changed. Refresh the row before submitting again.",
  failed: "The request failed. Retry with the same command or refresh.",
  validation: "Check the quantity and enter an adjustment reason.",
  forbidden: "This account cannot perform this action.",
  requestID: "Request ID",
  language: "Language",
  close: "Close details",
  name: "Product name",
  description: "Description",
  createHint:
    "Create the product, then add its first SKU. Both steps are recorded independently.",
  skuCode: "SKU code",
  priceMinor: "Price in minor units",
  createSKU: "Add first SKU",
  productSaved: "Product saved. Add its first SKU below.",
  purchaseEntry: "Purchase page",
  purchaseConfigured: "Purchase page address configured",
  purchaseInactive: "This product is archived.",
  purchaseNoSKU:
    "Add an active SKU in the store currency to create a purchase page address.",
  purchaseUnavailable:
    "No verified, published storefront address is available.",
  purchaseAmbiguous:
    "Multiple storefront addresses are eligible; choose a primary domain before sharing.",
  purchaseLoading: "Checking the current purchase page address…",
  purchaseFailed:
    "Could not check the purchase page address. The saved product is unchanged; try again.",
  purchaseNotFound: "This product is no longer available in this store.",
  purchaseHint:
    "This address is configuration only. Payment availability is checked during checkout.",
  copyPurchaseLink: "Copy address",
  openPurchasePage: "Open purchase page",
  purchaseCopied: "Address copied",
  purchaseCopyFailed:
    "Could not copy automatically. Select the address to copy it.",
  unavailable: "This module is not connected in the current build.",
  sectionHint:
    "Website chat, Meta conversations and platform support use separate authorization and storage domains.",
};
export type Copy = typeof en;
export const copy: Record<Locale, Copy> = {
  en,
  "zh-CN": {
    storageUnavailable:
      "操作记录无法可靠保存。请恢复浏览器存储后继续，之前的操作可能需要恢复确认。",
    skuSaved: "商品与 SKU 已保存",
    title: "直播商家工作台",
    store: "演示店铺",
    user: "商家账号",
    menu: "打开导航",
    products: "商品",
    inventory: "库存",
    orders: "订单",
    signOut: "退出登录",
    signingOut: "正在退出…",
    signOutFailed: "退出失败，请重试。",
    live: "直播工作区",
    siteChat: "网站客服",
    meta: "Meta 消息",
    ads: "广告",
    support: "平台支持",
    settings: "设置",
    heading: "商品与库存",
    subtitle: "核对 SKU 可售库存，为每次库存调整保留记录。",
    search: "搜索商品名称、SKU",
    searchAction: "查询",
    reset: "重置",
    all: "全部状态",
    active: "在售",
    archived: "已归档",
    warehouse: "仓库",
    selectWarehouse: "请选择仓库",
    create: "新增商品",
    product: "商品信息",
    price: "售价",
    onHand: "现有",
    reserved: "预留",
    available: "可售",
    status: "状态",
    actions: "操作",
    edit: "选择",
    demo: "演示数据",
    fixture: "隔离本地测试店铺 · 非客户真实库存",
    notConnected: "尚未连接",
    channels: "渠道连接状态",
    website: "网站商城",
    loading: "正在读取库存…",
    empty: "没有符合条件的 SKU",
    emptyHint: "创建商品和 SKU，或调整搜索条件与仓库。",
    choose: "选择一个 SKU，查看或调整库存。",
    adjustment: "调整库存",
    quantity: "调整数量",
    reason: "调整原因（必填）",
    reasonHint: "请说明此次库存变化的原因",
    confirm: "确认调整",
    pending: "正在保存…",
    success: "库存已更新",
    cancel: "取消",
    selected: "已选择 SKU",
    stockInfo: "库存信息",
    auditHint: "此操作将记录在库存流水中。",
    previous: "上一页",
    next: "下一页",
    page: "页",
    pageSize: "每页显示",
    retry: "重试",
    refresh: "刷新",
    noSession: "尚未接入商家登录",
    noSessionHint:
      "当前环境没有商家会话。身份服务配置完成前，生产数据访问保持关闭。",
    conflict: "库存已发生变化，请刷新该行后重新提交。",
    failed: "请求失败，可以使用原操作重试或刷新。",
    validation: "请检查调整数量，并填写调整原因。",
    forbidden: "当前账号没有执行此操作的权限。",
    requestID: "请求编号",
    language: "语言",
    close: "关闭详情",
    name: "商品名称",
    description: "商品描述",
    createHint: "先创建商品，再添加首个 SKU。两步分别保留记录。",
    skuCode: "SKU 编码",
    priceMinor: "价格（最小货币单位）",
    createSKU: "添加首个 SKU",
    productSaved: "商品已保存，请继续添加首个 SKU。",
    purchaseEntry: "购买页面",
    purchaseConfigured: "购买页面地址已配置",
    purchaseInactive: "该商品已归档。",
    purchaseNoSKU: "添加使用店铺币种的在售 SKU 后，才能生成购买页面地址。",
    purchaseUnavailable: "暂无已验证并发布的店铺地址。",
    purchaseAmbiguous: "有多个符合条件的店铺地址，请先选择主域名再分享。",
    purchaseLoading: "正在核对当前购买页面地址…",
    purchaseFailed: "无法核对购买页面地址。已保存的商品不受影响，请重试。",
    purchaseNotFound: "当前店铺已无法读取该商品。",
    purchaseHint: "此地址仅表示配置完成；支付是否可用会在结账时检查。",
    copyPurchaseLink: "复制地址",
    openPurchasePage: "打开购买页面",
    purchaseCopied: "地址已复制",
    purchaseCopyFailed: "无法自动复制，请选中地址手动复制。",
    unavailable: "当前版本尚未连接此模块。",
    sectionHint: "网站客服、Meta 会话与平台支持使用独立的授权和数据域。",
  },
  "zh-TW": {
    storageUnavailable:
      "操作紀錄無法可靠儲存。請恢復瀏覽器儲存後繼續，先前的操作可能需要恢復確認。",
    skuSaved: "商品與 SKU 已儲存",
    title: "直播商家工作台",
    store: "示範商店",
    user: "商家帳號",
    menu: "開啟導覽",
    products: "商品",
    inventory: "庫存",
    orders: "訂單",
    signOut: "登出",
    signingOut: "正在登出…",
    signOutFailed: "登出失敗，請重試。",
    live: "直播工作區",
    siteChat: "網站客服",
    meta: "Meta 訊息",
    ads: "廣告",
    support: "平台支援",
    settings: "設定",
    heading: "商品與庫存",
    subtitle: "核對 SKU 可售庫存，為每次庫存調整保留紀錄。",
    search: "搜尋商品名稱、SKU",
    searchAction: "查詢",
    reset: "重設",
    all: "全部狀態",
    active: "販售中",
    archived: "已封存",
    warehouse: "倉庫",
    selectWarehouse: "請選擇倉庫",
    create: "新增商品",
    product: "商品資訊",
    price: "售價",
    onHand: "現有",
    reserved: "預留",
    available: "可售",
    status: "狀態",
    actions: "操作",
    edit: "選取",
    demo: "示範資料",
    fixture: "隔離本機測試商店 · 非客戶真實庫存",
    notConnected: "尚未連線",
    channels: "通路連線狀態",
    website: "網站商城",
    loading: "正在讀取庫存…",
    empty: "沒有符合條件的 SKU",
    emptyHint: "建立商品和 SKU，或調整搜尋條件與倉庫。",
    choose: "選取一個 SKU，查看或調整庫存。",
    adjustment: "調整庫存",
    quantity: "調整數量",
    reason: "調整原因（必填）",
    reasonHint: "請說明此次庫存變動的原因",
    confirm: "確認調整",
    pending: "正在儲存…",
    success: "庫存已更新",
    cancel: "取消",
    selected: "已選取 SKU",
    stockInfo: "庫存資訊",
    auditHint: "此操作將記錄於庫存流水。",
    previous: "上一頁",
    next: "下一頁",
    page: "頁",
    pageSize: "每頁顯示",
    retry: "重試",
    refresh: "重新整理",
    noSession: "尚未接入商家登入",
    noSessionHint:
      "目前環境沒有商家工作階段。身分服務設定完成前，正式資料存取保持關閉。",
    conflict: "庫存已變動，請重新整理該列後再送出。",
    failed: "請求失敗，可使用原操作重試或重新整理。",
    validation: "請檢查調整數量，並填寫調整原因。",
    forbidden: "目前帳號沒有執行此操作的權限。",
    requestID: "請求編號",
    language: "語言",
    close: "關閉詳情",
    name: "商品名稱",
    description: "商品描述",
    createHint: "先建立商品，再新增第一個 SKU。兩步各自保留紀錄。",
    skuCode: "SKU 編碼",
    priceMinor: "價格（最小貨幣單位）",
    createSKU: "新增第一個 SKU",
    productSaved: "商品已儲存，請繼續新增第一個 SKU。",
    purchaseEntry: "購買頁面",
    purchaseConfigured: "購買頁面位址已設定",
    purchaseInactive: "此商品已封存。",
    purchaseNoSKU: "新增使用商店幣別的販售中 SKU 後，才能產生購買頁面位址。",
    purchaseUnavailable: "目前沒有已驗證並發佈的商店位址。",
    purchaseAmbiguous: "有多個符合條件的商店位址，請先選擇主要網域再分享。",
    purchaseLoading: "正在核對目前的購買頁面位址…",
    purchaseFailed: "無法核對購買頁面位址。已儲存的商品不受影響，請重試。",
    purchaseNotFound: "目前商店已無法讀取此商品。",
    purchaseHint: "此位址僅代表設定完成；付款是否可用會在結帳時檢查。",
    copyPurchaseLink: "複製位址",
    openPurchasePage: "開啟購買頁面",
    purchaseCopied: "位址已複製",
    purchaseCopyFailed: "無法自動複製，請選取位址手動複製。",
    unavailable: "目前版本尚未連線此模組。",
    sectionHint: "網站客服、Meta 對話與平台支援使用獨立的授權和資料域。",
  },
};
