// Copy for the admin Customers, Customer detail and Finance pages (BFF customers*, finance/summary* -> Go
// internal/customers + internal/reporting; contract customers-billing-v1 §5, U9 locales zh-CN / zh-TW / en).
// Owns every string those pages show, including the erase dialog text (U2: says what is kept) and the error map for the
// frozen Go error codes. Non-goals: no money/date formatting (components use Intl), no consent or privacy rule.
// Depends on: @live-commerce/i18n (Locale) only. Nav labels for the integrator's WorkspaceFrame hook live in `nav`.
import type { Locale } from "@live-commerce/i18n";

const en = {
  nav: { customers: "Customers", finance: "Finance", billing: "Billing" },
  title: "Customers",
  subtitle: "Buyers of this store, with their orders, consent and privacy actions.",
  store: "Store",
  search: "Search by name or phone digits",
  searchHint: "Names match from the start; phone search uses the digits at the end of the number.",
  searchButton: "Search",
  clear: "Clear",
  refresh: "Refresh",
  loading: "Loading customers…",
  detailLoading: "Loading customer…",
  empty: "No customers yet.",
  emptySearch: "No customers match this search.",
  signedOut: "Sign in to view customers.",
  forbidden: "This account does not have permission to view customers.",
  notFound: "This customer is unavailable in the selected store.",
  unavailable: "Customers are temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  previous: "Previous page",
  next: "Next page",
  pageCount: "Customers on this page",
  customer: "Customer",
  orders: "Orders",
  spent: "Paid / refunded",
  claims: "Claims",
  consents: "Consent",
  lastActivity: "Last activity (UTC)",
  noName: "Name not recorded",
  erased: "Erased",
  inactive: "Inactive",
  open: "Open customer",
  ordersPaid: (all: number, paid: number) => `${all} (${paid} paid)`,
  consentGranted: "Granted",
  consentNone: "Not granted",
  marketing: "Marketing messages (Messenger / Instagram DM)",
  ads: "Ads personalization (Meta)",
  platforms: { facebook: "Facebook", instagram: "Instagram", manual: "Manual" } as Record<string, string>,
  back: "All customers",
  firstSeen: "First seen (UTC)",
  phoneEnding: "Phone ends",
  facts: "Customer",
  ordersSection: "Orders",
  ordersNone: "No orders.",
  ordersNewest: "Newest 50 orders.",
  orderId: "Order",
  created: "Created (UTC)",
  total: "Total",
  status: "Status",
  payment: "Payment",
  orderOpen: "Open in orders",
  claimsSection: "Comment claims",
  claimsNone: "No claims.",
  platform: "Platform",
  boundAt: "Linked (UTC)",
  lines: "Items",
  consentSection: "Consent",
  consentNow: "Current",
  consentHistory: "History",
  consentHistoryNone: "No consent has been recorded.",
  policy: "Notice version",
  source: "Recorded by",
  when: "When (UTC)",
  sources: {
    buyer_checkout: "Buyer at checkout",
    buyer_settings: "Buyer, privacy page",
    merchant: "This store",
    erasure: "Erasure",
  } as Record<string, string>,
  withdraw: "Record withdrawal",
  withdrawing: "Recording…",
  withdrawDone: "Withdrawal recorded.",
  withdrawHint: "Use this when the customer asks you to stop. The customer can grant again only from their own privacy page.",
  privacySection: "Privacy",
  privacyIntro: "Give the customer a copy of their data, or erase it when they ask.",
  download: "Download data",
  downloading: "Preparing…",
  downloadDone: "The data file was downloaded.",
  erase: "Erase customer",
  eraseTitle: "Erase this customer?",
  eraseBody:
    "Personal details saved with this customer's orders (name, phone, address) are redacted, their sign-in sessions end and their consents are withdrawn. This cannot be undone.",
  eraseKept:
    "Kept: orders, payments and shipments stay in your records for legal retention, and you may still contact the customer about existing orders.",
  eraseType: "Type ERASE to confirm",
  eraseConfirm: "Erase customer",
  erasing: "Erasing…",
  eraseRetry: "Retry same request",
  erasedDone: (s: { consents: number; sessions: number; snapshots: number; bundles: number }) =>
    `Customer erased: ${s.consents} consents withdrawn, ${s.sessions} sessions ended, ${s.snapshots} order details redacted, ${s.bundles} claim bundles relabelled.`,
  erasedState: "This customer was erased. Their orders, payments and shipments are kept.",
  cancel: "Cancel",
  close: "Close",
  actionsSection: "Privacy actions",
  actionsNone: "No privacy actions yet.",
  actionCol: "Action",
  kinds: { export: "Data export", erasure: "Erasure" } as Record<string, string>,
  via: { merchant: "This store", buyer: "Customer", restore: "Restored after recovery" } as Record<string, string>,
  uncertain: "The result is unknown. Retry the same request; it will not run twice.",
  errors: {
    default: "This could not be completed. Try again.",
    unauthorized: "Your session changed. Reload the page and sign in again.",
    forbidden: "This account does not have permission for this action.",
    erasure_blocked: "Erasure is blocked while a payment for this customer may still be open (up to 40 minutes). Try again later.",
    export_too_large: "This customer has too much data for one file (more than 200 orders or 1 MiB). Ask support for a manual export.",
    idempotency_conflict: "This request conflicts with an earlier one. Reload and try again.",
    erased: "This customer was already erased.",
    not_found: "This customer is unavailable.",
    rate_limited: "Too many requests. Wait a moment and try again.",
    retry_later: "The service did not answer. Try again.",
  } as Record<string, string>,
  financeTitle: "Finance",
  financeSubtitle: "Daily captured and refunded payments, by currency.",
  from: "From",
  to: "To",
  show: "Show",
  csv: "Download CSV",
  csvHint: "Amounts in the CSV are whole numbers in minor units (for example cents), one row per day and currency.",
  testBadge: "Test mode — sandbox payments, not real money",
  timezone: (zone: string) => `Days follow ${zone} (UTC+8).`,
  day: "Day",
  currency: "Currency",
  environment: "Environment",
  paidOrders: "Paid orders",
  captured: "Captured",
  refunded: "Refunded",
  net: "Net",
  totalRow: "Total",
  financeEmpty: "No payments in this range.",
  financeLoading: "Loading finance summary…",
  financeUnavailable: "The finance summary is temporarily unavailable. Try again.",
  rangeInvalid: "Choose a start before the end, at most 91 days apart.",
  financeForbidden: "This account does not have permission to view finance.",
  financeSignedOut: "Sign in to view finance.",
};
export type CustomersCopy = typeof en;

export const customersCopy: Record<Locale, CustomersCopy> = {
  en,
  "zh-CN": {
    nav: { customers: "客户", finance: "财务", billing: "账单" },
    title: "客户",
    subtitle: "本店买家，及其订单、授权与隐私操作。",
    store: "店铺",
    search: "按姓名或手机号码数字搜索",
    searchHint: "姓名从开头匹配；手机号码按末尾数字搜索。",
    searchButton: "搜索",
    clear: "清除",
    refresh: "刷新",
    loading: "正在加载客户…",
    detailLoading: "正在加载客户…",
    empty: "还没有客户。",
    emptySearch: "没有符合搜索的客户。",
    signedOut: "请登录后查看客户。",
    forbidden: "此账号无权查看客户。",
    notFound: "所选店铺中没有这位客户。",
    unavailable: "客户暂时无法使用，请重试。",
    noStore: "没有可用的授权店铺。",
    retry: "重试",
    previous: "上一页",
    next: "下一页",
    pageCount: "本页客户数",
    customer: "客户",
    orders: "订单",
    spent: "已收款 / 已退款",
    claims: "登记",
    consents: "授权",
    lastActivity: "最近活动（UTC）",
    noName: "未记录姓名",
    erased: "已抹除",
    inactive: "未启用",
    open: "打开客户",
    ordersPaid: (all: number, paid: number) => `${all}（已付款 ${paid}）`,
    consentGranted: "已授权",
    consentNone: "未授权",
    marketing: "营销消息（Messenger / Instagram 私信）",
    ads: "广告个性化（Meta）",
    platforms: { facebook: "Facebook", instagram: "Instagram", manual: "手动" },
    back: "全部客户",
    firstSeen: "首次出现（UTC）",
    phoneEnding: "手机尾号",
    facts: "客户",
    ordersSection: "订单",
    ordersNone: "没有订单。",
    ordersNewest: "最近 50 笔订单。",
    orderId: "订单",
    created: "创建时间（UTC）",
    total: "合计",
    status: "状态",
    payment: "付款",
    orderOpen: "在订单中打开",
    claimsSection: "评论登记",
    claimsNone: "没有登记。",
    platform: "平台",
    boundAt: "关联时间（UTC）",
    lines: "商品数",
    consentSection: "授权",
    consentNow: "当前状态",
    consentHistory: "历史记录",
    consentHistoryNone: "尚无授权记录。",
    policy: "声明版本",
    source: "记录来源",
    when: "时间（UTC）",
    sources: { buyer_checkout: "买家结账时", buyer_settings: "买家隐私页", merchant: "本店", erasure: "抹除" },
    withdraw: "记录撤回",
    withdrawing: "记录中…",
    withdrawDone: "已记录撤回。",
    withdrawHint: "当客户要求停止时使用。客户只能在自己的隐私页重新授权。",
    privacySection: "隐私",
    privacyIntro: "向客户提供其数据副本，或在客户要求时抹除。",
    download: "下载数据",
    downloading: "准备中…",
    downloadDone: "数据文件已下载。",
    erase: "抹除客户",
    eraseTitle: "抹除这位客户？",
    eraseBody: "该客户订单中保存的个人信息（姓名、手机、地址）将被遮蔽，登录会话结束，授权全部撤回。此操作无法撤销。",
    eraseKept: "保留：订单、付款与出货记录会按法定保存要求留在你的账目中，你仍可就现有订单联系该客户。",
    eraseType: "输入 ERASE 以确认",
    eraseConfirm: "抹除客户",
    erasing: "抹除中…",
    eraseRetry: "重试同一请求",
    erasedDone: (s: { consents: number; sessions: number; snapshots: number; bundles: number }) =>
      `客户已抹除：撤回授权 ${s.consents} 项，结束会话 ${s.sessions} 个，遮蔽订单信息 ${s.snapshots} 笔，重新标记登记组 ${s.bundles} 个。`,
    erasedState: "该客户已被抹除。其订单、付款与出货记录予以保留。",
    cancel: "取消",
    close: "关闭",
    actionsSection: "隐私操作",
    actionsNone: "尚无隐私操作。",
    actionCol: "操作",
    kinds: { export: "数据导出", erasure: "抹除" },
    via: { merchant: "本店", buyer: "客户本人", restore: "恢复后补记" },
    uncertain: "结果未知。请重试同一请求，不会重复执行。",
    errors: {
      default: "无法完成，请重试。",
      unauthorized: "登录状态已变化。请重新加载页面并再次登录。",
      forbidden: "此账号无权执行此操作。",
      erasure_blocked: "该客户可能仍有未结付款（最长 40 分钟），暂时无法抹除。请稍后再试。",
      export_too_large: "该客户数据过多，无法放入一个文件（超过 200 笔订单或 1 MiB）。请联系支持人员手动导出。",
      idempotency_conflict: "此请求与之前的请求冲突。请重新加载后再试。",
      erased: "该客户已被抹除。",
      not_found: "该客户不可用。",
      rate_limited: "请求过于频繁，请稍候再试。",
      retry_later: "服务没有响应，请重试。",
    },
    financeTitle: "财务",
    financeSubtitle: "按币种统计每日已收款与已退款金额。",
    from: "起始",
    to: "结束",
    show: "查看",
    csv: "下载 CSV",
    csvHint: "CSV 中的金额为最小货币单位的整数（例如分），每个日期与币种一行。",
    testBadge: "测试模式——沙盒付款，非真实资金",
    timezone: (zone: string) => `日期按 ${zone}（UTC+8）计算。`,
    day: "日期",
    currency: "币种",
    environment: "环境",
    paidOrders: "已付款订单",
    captured: "已收款",
    refunded: "已退款",
    net: "净额",
    totalRow: "合计",
    financeEmpty: "此区间没有付款。",
    financeLoading: "正在加载财务汇总…",
    financeUnavailable: "财务汇总暂时无法使用，请重试。",
    rangeInvalid: "请选择开始不晚于结束、相隔不超过 91 天的区间。",
    financeForbidden: "此账号无权查看财务。",
    financeSignedOut: "请登录后查看财务。",
  },
  "zh-TW": {
    nav: { customers: "客戶", finance: "財務", billing: "帳單" },
    title: "客戶",
    subtitle: "本店買家，及其訂單、授權與隱私操作。",
    store: "店鋪",
    search: "依姓名或手機號碼數字搜尋",
    searchHint: "姓名從開頭比對；手機號碼依尾數搜尋。",
    searchButton: "搜尋",
    clear: "清除",
    refresh: "重新整理",
    loading: "正在載入客戶…",
    detailLoading: "正在載入客戶…",
    empty: "目前還沒有客戶。",
    emptySearch: "沒有符合搜尋的客戶。",
    signedOut: "請登入後查看客戶。",
    forbidden: "此帳號無權查看客戶。",
    notFound: "所選店鋪中沒有這位客戶。",
    unavailable: "客戶暫時無法使用，請重試。",
    noStore: "沒有可用的授權店鋪。",
    retry: "重試",
    previous: "上一頁",
    next: "下一頁",
    pageCount: "本頁客戶數",
    customer: "客戶",
    orders: "訂單",
    spent: "已收款 / 已退款",
    claims: "登記",
    consents: "授權",
    lastActivity: "最近活動（UTC）",
    noName: "未記錄姓名",
    erased: "已抹除",
    inactive: "未啟用",
    open: "開啟客戶",
    ordersPaid: (all: number, paid: number) => `${all}（已付款 ${paid}）`,
    consentGranted: "已授權",
    consentNone: "未授權",
    marketing: "行銷訊息（Messenger / Instagram 私訊）",
    ads: "廣告個人化（Meta）",
    platforms: { facebook: "Facebook", instagram: "Instagram", manual: "手動" },
    back: "全部客戶",
    firstSeen: "首次出現（UTC）",
    phoneEnding: "手機末碼",
    facts: "客戶",
    ordersSection: "訂單",
    ordersNone: "沒有訂單。",
    ordersNewest: "最近 50 筆訂單。",
    orderId: "訂單",
    created: "建立時間（UTC）",
    total: "合計",
    status: "狀態",
    payment: "付款",
    orderOpen: "在訂單中開啟",
    claimsSection: "留言登記",
    claimsNone: "沒有登記。",
    platform: "平台",
    boundAt: "關聯時間（UTC）",
    lines: "商品數",
    consentSection: "授權",
    consentNow: "目前狀態",
    consentHistory: "歷史紀錄",
    consentHistoryNone: "尚無授權紀錄。",
    policy: "聲明版本",
    source: "記錄來源",
    when: "時間（UTC）",
    sources: { buyer_checkout: "買家結帳時", buyer_settings: "買家隱私頁", merchant: "本店", erasure: "抹除" },
    withdraw: "記錄撤回",
    withdrawing: "記錄中…",
    withdrawDone: "已記錄撤回。",
    withdrawHint: "當客戶要求停止時使用。客戶只能在自己的隱私頁重新授權。",
    privacySection: "隱私",
    privacyIntro: "向客戶提供其資料副本，或在客戶要求時抹除。",
    download: "下載資料",
    downloading: "準備中…",
    downloadDone: "資料檔案已下載。",
    erase: "抹除客戶",
    eraseTitle: "抹除這位客戶？",
    eraseBody: "該客戶訂單中保存的個人資料（姓名、手機、地址）將被遮蔽，登入工作階段結束，授權全部撤回。此操作無法復原。",
    eraseKept: "保留：訂單、付款與出貨紀錄會依法定保存要求留在你的帳目中，你仍可就現有訂單聯絡該客戶。",
    eraseType: "輸入 ERASE 以確認",
    eraseConfirm: "抹除客戶",
    erasing: "抹除中…",
    eraseRetry: "重試同一請求",
    erasedDone: (s: { consents: number; sessions: number; snapshots: number; bundles: number }) =>
      `客戶已抹除：撤回授權 ${s.consents} 項，結束工作階段 ${s.sessions} 個，遮蔽訂單資料 ${s.snapshots} 筆，重新標記登記組 ${s.bundles} 個。`,
    erasedState: "該客戶已被抹除。其訂單、付款與出貨紀錄予以保留。",
    cancel: "取消",
    close: "關閉",
    actionsSection: "隱私操作",
    actionsNone: "尚無隱私操作。",
    actionCol: "操作",
    kinds: { export: "資料匯出", erasure: "抹除" },
    via: { merchant: "本店", buyer: "客戶本人", restore: "復原後補記" },
    uncertain: "結果未知。請重試同一請求，不會重複執行。",
    errors: {
      default: "無法完成，請重試。",
      unauthorized: "登入狀態已變更。請重新載入頁面並再次登入。",
      forbidden: "此帳號無權執行此操作。",
      erasure_blocked: "該客戶可能仍有未結付款（最長 40 分鐘），暫時無法抹除。請稍後再試。",
      export_too_large: "該客戶資料過多，無法放入一個檔案（超過 200 筆訂單或 1 MiB）。請聯絡支援人員手動匯出。",
      idempotency_conflict: "此請求與先前的請求衝突。請重新載入後再試。",
      erased: "該客戶已被抹除。",
      not_found: "該客戶不可用。",
      rate_limited: "請求過於頻繁，請稍候再試。",
      retry_later: "服務沒有回應，請重試。",
    },
    financeTitle: "財務",
    financeSubtitle: "依幣別統計每日已收款與已退款金額。",
    from: "起始",
    to: "結束",
    show: "查看",
    csv: "下載 CSV",
    csvHint: "CSV 中的金額為最小貨幣單位的整數（例如分），每個日期與幣別一列。",
    testBadge: "測試模式——沙盒付款，非真實資金",
    timezone: (zone: string) => `日期依 ${zone}（UTC+8）計算。`,
    day: "日期",
    currency: "幣別",
    environment: "環境",
    paidOrders: "已付款訂單",
    captured: "已收款",
    refunded: "已退款",
    net: "淨額",
    totalRow: "合計",
    financeEmpty: "此區間沒有付款。",
    financeLoading: "正在載入財務彙總…",
    financeUnavailable: "財務彙總暫時無法使用，請重試。",
    rangeInvalid: "請選擇開始不晚於結束、相隔不超過 91 天的區間。",
    financeForbidden: "此帳號無權查看財務。",
    financeSignedOut: "請登入後查看財務。",
  },
};
