// Copy for the signed-out entry (components/Entry.tsx) and the password pages (components/PasswordAuth.tsx,
// BFF /api/auth/password/* → Go /v1/identity/password/*). Sign-up and reset wording never confirms
// whether an address has an account (merchant-password-auth-v1 PD6/§7.3). Placeholders {email},
// {minutes}, {seconds} are filled by PasswordAuth; no other interpolation exists.
import type { Locale } from "@live-commerce/i18n";

const en = {
  product: "Live commerce workspace",
  manage: "Workspace setup",
  account: "Merchant account",
  language: "Language",
  title: "Create your first workspace",
  signInTitle: "Sign in to your merchant workspace",
  signInBody:
    "Continue through the configured identity service. This page never asks for your provider password.",
  signIn: "Sign in with identity service",
  authFailed:
    "Sign-in did not complete. Start the identity-service flow again.",
  authExpired:
    "Your session expired. Sign in again; the previous session's draft was not carried forward.",
  providerDisabled: "Merchant sign-in is not configured",
  providerDisabledBody:
    "This environment cannot start merchant sign-in. No production data is available here.",
  serviceUnavailable: "The merchant service is temporarily unavailable",
  serviceUnavailableBody:
    "No setup request was sent. Refresh after the service is restored.",
  onboardingDisabled: "First-workspace setup is not enabled",
  onboardingDisabledBody:
    "Your signed-in session is valid, but this deployment has not enabled workspace creation.",
  currencyUnavailable: "No transaction currency policy is configured.",
  stepMerchant: "Merchant name",
  stepStore: "Store settings",
  stepWarehouse: "Warehouse",
  merchantHeading: "Name the merchant",
  merchantBody: "Use the operating name that should own this workspace.",
  merchantName: "Merchant name",
  merchantPlaceholder: "Example merchant",
  storeHeading: "Set the store name and currency",
  storeName: "Store name",
  storePlaceholder: "Example store",
  currency: "Transaction currency",
  currencyHint:
    "Changing the interface language does not change this currency.",
  completed: "Completed",
  edit: "Edit",
  warehouseHeading: "Add the initial inventory warehouse",
  warehouseName: "Initial warehouse name",
  warehousePlaceholder: "Main warehouse",
  review: "Review before creating",
  previous: "Previous",
  nextStore: "Next: store settings",
  nextWarehouse: "Next: warehouse",
  create: "Create internal workspace",
  creating: "Creating…",
  retryExact: "Retry the same request",
  checkWorkspace: "Check workspace status",
  openWorkspace: "Open workspace",
  signOut: "Sign out",
  scope:
    "This creates an internal workspace. It does not publish a store or connect payment or shipping.",
  finalHint:
    "Review every field. Only this final step sends the creation request.",
  invalid: "Complete the required field before continuing.",
  storageUnavailable:
    "Secure draft storage is unavailable. No setup request can be sent from this tab.",
  unknown:
    "The server result is unknown. Fields are locked; retry the exact saved request and key.",
  conflict:
    "A workspace may already exist or this request conflicts with an earlier setup. Check workspace status before doing anything else.",
  failed: "The workspace could not be created. Check the fields and try again.",
  success:
    "Internal workspace created. The store is not published, and payment and shipping are not connected.",
};

export type EntryCopy = typeof en;

export const entryCopy: Record<Locale, EntryCopy> = {
  en,
  "zh-CN": {
    product: "直播商家工作台",
    manage: "工作区管理",
    account: "商家账号",
    language: "语言",
    title: "创建第一个工作区",
    signInTitle: "登录商家工作区",
    signInBody: "通过已配置的身份服务继续。本页面不会要求输入身份服务密码。",
    signIn: "通过身份服务登录",
    authFailed: "登录未完成，请重新开始身份服务登录流程。",
    authExpired: "会话已过期，请重新登录；上一会话的草稿不会带入新会话。",
    providerDisabled: "尚未配置商家登录",
    providerDisabledBody: "当前环境无法开始商家登录，也不会开放生产数据。",
    serviceUnavailable: "商家服务暂时不可用",
    serviceUnavailableBody: "尚未发送开通请求，请在服务恢复后刷新。",
    onboardingDisabled: "尚未启用首个工作区开通",
    onboardingDisabledBody: "当前登录会话有效，但此部署尚未启用工作区创建。",
    currencyUnavailable: "尚未配置可用的交易币种策略。",
    stepMerchant: "商户名称",
    stepStore: "店铺设置",
    stepWarehouse: "库存仓",
    merchantHeading: "填写商户名称",
    merchantBody: "填写将持有此工作区的经营名称。",
    merchantName: "商户名称",
    merchantPlaceholder: "示例商户",
    storeHeading: "设置店铺名称与币种",
    storeName: "店铺名称",
    storePlaceholder: "示例店铺",
    currency: "交易币种",
    currencyHint: "切换界面语言不会改变交易币种。",
    completed: "已填写",
    edit: "修改",
    warehouseHeading: "设置初始库存仓",
    warehouseName: "初始库存仓名称",
    warehousePlaceholder: "主仓",
    review: "创建前核对",
    previous: "上一步",
    nextStore: "下一步：店铺设置",
    nextWarehouse: "下一步：库存仓",
    create: "创建内部工作区",
    creating: "正在创建…",
    retryExact: "重试同一请求",
    checkWorkspace: "检查工作区状态",
    openWorkspace: "进入工作区",
    signOut: "退出登录",
    scope: "创建内部工作区，不会自动发布店铺或接通支付、物流。",
    finalHint: "请核对全部资料。只有最后一步会发送创建请求。",
    invalid: "请先填写必填资料。",
    storageUnavailable: "当前标签页无法可靠保存草稿，因此不会发送开通请求。",
    unknown:
      "服务器结果未知。资料已锁定；只能使用已保存的原请求与原幂等键重试。",
    conflict:
      "工作区可能已经存在，或本次请求与既有开通记录冲突。请先检查工作区状态。",
    failed: "工作区未能创建，请检查资料后重试。",
    success: "内部工作区已创建；店铺尚未发布，支付和物流尚未接通。",
  },
  "zh-TW": {
    product: "直播商家工作台",
    manage: "工作區管理",
    account: "商家帳號",
    language: "語言",
    title: "建立第一個工作區",
    signInTitle: "登入商家工作區",
    signInBody: "透過已設定的身分服務繼續。本頁面不會要求輸入身分服務密碼。",
    signIn: "透過身分服務登入",
    authFailed: "登入未完成，請重新開始身分服務登入流程。",
    authExpired:
      "工作階段已過期，請重新登入；上一工作階段的草稿不會帶入新工作階段。",
    providerDisabled: "尚未設定商家登入",
    providerDisabledBody: "目前環境無法開始商家登入，也不會開放正式資料。",
    serviceUnavailable: "商家服務暫時無法使用",
    serviceUnavailableBody: "尚未送出開通請求，請在服務恢復後重新整理。",
    onboardingDisabled: "尚未啟用第一個工作區開通",
    onboardingDisabledBody:
      "目前登入工作階段有效，但此部署尚未啟用工作區建立。",
    currencyUnavailable: "尚未設定可用的交易幣別政策。",
    stepMerchant: "商戶名稱",
    stepStore: "商店設定",
    stepWarehouse: "庫存倉",
    merchantHeading: "填寫商戶名稱",
    merchantBody: "填寫將持有此工作區的營運名稱。",
    merchantName: "商戶名稱",
    merchantPlaceholder: "範例商戶",
    storeHeading: "設定商店名稱與幣別",
    storeName: "商店名稱",
    storePlaceholder: "範例商店",
    currency: "交易幣別",
    currencyHint: "切換介面語言不會改變交易幣別。",
    completed: "已填寫",
    edit: "修改",
    warehouseHeading: "設定初始庫存倉",
    warehouseName: "初始庫存倉名稱",
    warehousePlaceholder: "主倉",
    review: "建立前核對",
    previous: "上一步",
    nextStore: "下一步：商店設定",
    nextWarehouse: "下一步：庫存倉",
    create: "建立內部工作區",
    creating: "正在建立…",
    retryExact: "重試同一請求",
    checkWorkspace: "檢查工作區狀態",
    openWorkspace: "進入工作區",
    signOut: "登出",
    scope: "建立內部工作區，不會自動發布商店或接通付款、物流。",
    finalHint: "請核對全部資料。只有最後一步會送出建立請求。",
    invalid: "請先填寫必填資料。",
    storageUnavailable: "目前分頁無法可靠儲存草稿，因此不會送出開通請求。",
    unknown:
      "伺服器結果未知。資料已鎖定；只能使用已儲存的原請求與原冪等鍵重試。",
    conflict:
      "工作區可能已存在，或本次請求與既有開通紀錄衝突。請先檢查工作區狀態。",
    failed: "工作區未能建立，請檢查資料後重試。",
    success: "內部工作區已建立；商店尚未發布，付款和物流尚未接通。",
  },
};

const passwordEn = {
  signinTitle: "Sign in to your merchant workspace",
  signinBody: "Use your email and password. We then email you a 6-digit code to finish signing in.",
  signupTitle: "Create your merchant account",
  signupBody: "Enter your email and choose a password. We email you a 6-digit code to confirm the address.",
  resetTitle: "Reset your password",
  resetBody: "Enter your email. If it can be used, we email you a 6-digit code to choose a new password.",
  email: "Email",
  password: "Password",
  newPassword: "New password",
  code: "6-digit code",
  policyHint: "At least 12 characters. Use a password you do not use anywhere else.",
  submitSignin: "Continue",
  submitSignup: "Send code",
  submitReset: "Send code",
  verifySignin: "Sign in",
  verifySignup: "Create account",
  verifyReset: "Set password and sign in",
  busy: "Please wait…",
  codeTitle: "Enter the code",
  codeSent: "If this address can receive the code, we sent a 6-digit code to {email}.",
  codeExpiry: "The code is valid for 10 minutes.",
  spamHint: "Check your spam folder if it does not arrive.",
  resend: "Send a new code",
  resendIn: "Send a new code in {seconds} s",
  changeEmail: "Start over",
  toSignup: "Create an account",
  toSignin: "Back to sign in",
  toReset: "Forgot your password?",
  or: "or",
  errors: {
    invalid_credentials: "The email or password is not correct.",
    invalid_code: "That code is not correct or has expired. Check it or send a new code.",
    invalid_email: "Enter a valid email address.",
    invalid_request: "Complete every field, or start over if this page was open for a long time.",
    challenge_lost: "This verification expired. Start over to get a new code.",
    account_exists: "This email cannot be used to create an account. Sign in, or reset your password.",
    throttled: "Too many attempts. Try again in {minutes} min.",
    mail_unavailable: "We cannot send email right now. Try again later.",
    mail_unavailable_login: "We cannot send the sign-in code right now. Wait a while before trying again; retrying now will not help.",
    busy: "The service is busy. Try again in a moment.",
    retry_later: "The service is temporarily unavailable. Try again shortly.",
    password_policy: "That password does not meet the policy.",
    unknown: "Something went wrong. Try again.",
  },
  policy: {
    too_short: "The password is too short. Use at least 12 characters.",
    too_long: "The password is too long. Use at most 128 characters.",
    breached: "This password appears in known data breaches. Choose a different one.",
    equals_email: "The password must not be the same as your email.",
  },
};

export type PasswordCopy = typeof passwordEn;

export const passwordCopy: Record<Locale, PasswordCopy> = {
  en: passwordEn,
  "zh-CN": {
    signinTitle: "登录商家工作区",
    signinBody: "使用邮箱和密码登录，随后我们会发送 6 位验证码到该邮箱以完成登录。",
    signupTitle: "创建商家账号",
    signupBody: "填写邮箱并设置密码，我们会发送 6 位验证码来确认该邮箱。",
    resetTitle: "重置密码",
    resetBody: "填写邮箱。若该邮箱可用，我们会发送 6 位验证码用于设置新密码。",
    email: "邮箱",
    password: "密码",
    newPassword: "新密码",
    code: "6 位验证码",
    policyHint: "至少 12 个字符，请使用没有在其他地方用过的密码。",
    submitSignin: "继续",
    submitSignup: "发送验证码",
    submitReset: "发送验证码",
    verifySignin: "登录",
    verifySignup: "创建账号",
    verifyReset: "设置密码并登录",
    busy: "请稍候…",
    codeTitle: "输入验证码",
    codeSent: "若该地址能收到验证码，我们已向 {email} 发送 6 位验证码。",
    codeExpiry: "验证码 10 分钟内有效。",
    spamHint: "如果没有收到，请检查垃圾邮件文件夹。",
    resend: "重新发送验证码",
    resendIn: "{seconds} 秒后可重新发送",
    changeEmail: "重新开始",
    toSignup: "创建账号",
    toSignin: "返回登录",
    toReset: "忘记密码？",
    or: "或",
    errors: {
      invalid_credentials: "邮箱或密码不正确。",
      invalid_code: "验证码不正确或已过期，请检查或重新发送。",
      invalid_email: "请填写有效的邮箱地址。",
      invalid_request: "请填写全部字段；若页面已打开很久，请重新开始。",
      challenge_lost: "本次验证已过期，请重新开始以获取新验证码。",
      account_exists: "该邮箱无法用于创建账号。请直接登录，或重置密码。",
      throttled: "尝试次数过多，请 {minutes} 分钟后再试。",
      mail_unavailable: "暂时无法发送邮件，请稍后再试。",
      mail_unavailable_login: "暂时无法发送登录验证码。请等待一段时间后再试，现在重试也不会成功。",
      busy: "服务繁忙，请稍后再试。",
      retry_later: "服务暂时不可用，请稍后再试。",
      password_policy: "该密码不符合要求。",
      unknown: "出了点问题，请重试。",
    },
    policy: {
      too_short: "密码太短，至少需要 12 个字符。",
      too_long: "密码太长，最多 128 个字符。",
      breached: "该密码出现在已知的数据泄露中，请换一个。",
      equals_email: "密码不能与邮箱相同。",
    },
  },
  "zh-TW": {
    signinTitle: "登入商家工作區",
    signinBody: "使用電子郵件和密碼登入，接著我們會寄送 6 位數驗證碼到該信箱以完成登入。",
    signupTitle: "建立商家帳號",
    signupBody: "填寫電子郵件並設定密碼，我們會寄送 6 位數驗證碼來確認該信箱。",
    resetTitle: "重設密碼",
    resetBody: "填寫電子郵件。若該信箱可用，我們會寄送 6 位數驗證碼用於設定新密碼。",
    email: "電子郵件",
    password: "密碼",
    newPassword: "新密碼",
    code: "6 位數驗證碼",
    policyHint: "至少 12 個字元，請使用沒有在其他地方用過的密碼。",
    submitSignin: "繼續",
    submitSignup: "寄送驗證碼",
    submitReset: "寄送驗證碼",
    verifySignin: "登入",
    verifySignup: "建立帳號",
    verifyReset: "設定密碼並登入",
    busy: "請稍候…",
    codeTitle: "輸入驗證碼",
    codeSent: "若該信箱能收到驗證碼，我們已向 {email} 寄送 6 位數驗證碼。",
    codeExpiry: "驗證碼 10 分鐘內有效。",
    spamHint: "如果沒有收到，請檢查垃圾郵件資料夾。",
    resend: "重新寄送驗證碼",
    resendIn: "{seconds} 秒後可重新寄送",
    changeEmail: "重新開始",
    toSignup: "建立帳號",
    toSignin: "返回登入",
    toReset: "忘記密碼？",
    or: "或",
    errors: {
      invalid_credentials: "電子郵件或密碼不正確。",
      invalid_code: "驗證碼不正確或已過期，請檢查或重新寄送。",
      invalid_email: "請填寫有效的電子郵件地址。",
      invalid_request: "請填寫所有欄位；若頁面已開啟很久，請重新開始。",
      challenge_lost: "本次驗證已過期，請重新開始以取得新的驗證碼。",
      account_exists: "該信箱無法用於建立帳號。請直接登入，或重設密碼。",
      throttled: "嘗試次數過多，請 {minutes} 分鐘後再試。",
      mail_unavailable: "目前無法寄送郵件，請稍後再試。",
      mail_unavailable_login: "目前無法寄送登入驗證碼。請等待一段時間後再試，現在重試也不會成功。",
      busy: "服務忙碌中，請稍後再試。",
      retry_later: "服務暫時無法使用，請稍後再試。",
      password_policy: "該密碼不符合要求。",
      unknown: "發生問題，請重試。",
    },
    policy: {
      too_short: "密碼太短，至少需要 12 個字元。",
      too_long: "密碼太長，最多 128 個字元。",
      breached: "該密碼出現在已知的資料外洩中，請換一個。",
      equals_email: "密碼不能與電子郵件相同。",
    },
  },
};
