// Copy (zh-CN / zh-TW / en) for the admin CVS surfaces: Settings -> 物流 cards (綠界物流, 超商取貨), the order CVS
// section (create shipment, print, timeline, abandon, pay-at-pickup actions) and the print tab
// (contracts/taiwan-cvs-logistics-v1.md §8, §9, §16.1, §16.4, §16.5, §16.8; owner answers U1..U6).
// Rendered by components/{LogisticsSettings,OrderCvsShipment}.tsx and app/[locale]/orders/cvs-print; the BFF
// routes are listed in lib/logistics-client.ts. Error codes are every refusal §8 lists; unknown codes fall back to
// the orders copy's generic text (see errorText in components/OrderCvsShipment.tsx).
import type { Locale } from "@live-commerce/i18n";

const en = {
  // shared
  chains: { cvs_711: "7-ELEVEN", cvs_familymart: "FamilyMart", cvs_hilife: "Hi-Life", cvs_okmart: "OK mart" },
  save: "Save",
  saving: "Saving…",
  retry: "Try again",
  retrySame: "Retry the same request",
  cancel: "Cancel",
  close: "Close",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Copy failed. Select the text and copy it manually.",
  loading: "Loading…",
  unavailable: "This section could not be loaded. Try again.",
  noPermission: "This account does not have permission to change these settings.",
  uncertain: "The result is not known yet. Retry sends the identical request safely, or reload.",
  // ECPay card
  ecpayTitle: "ECPay logistics",
  ecpayIntro:
    "Connect your own ECPay logistics account to let buyers pick stores on the ECPay map and to create store shipments. Without it, buyers type their store and you ship yourself.",
  ecpayNone: "Not connected.",
  ecpayEnv: "Environment",
  ecpayEnvBadge: { SANDBOX: "Test (sandbox)", LIVE: "Live" },
  ecpayMode: "Account type",
  ecpayModes: { C2C: "Store to store (C2C)", B2C: "Business to store (B2C)" },
  ecpayMerchantID: "ECPay merchant ID",
  ecpayHashKey: "HashKey",
  ecpayHashIV: "HashIV",
  ecpaySenderName: "Sender name (up to 10 characters)",
  ecpaySenderPhone: "Sender mobile (09xxxxxxxx)",
  ecpaySecretsNote: "The keys are sent once and never shown again. Re-enter them to rotate.",
  ecpayConnect: "Connect and check",
  ecpayRotate: "Rotate keys",
  ecpayChange: "Replace connection",
  ecpayRotateWarn:
    "Rotate only when no shipment is between created and picked up: ECPay keeps one active key pair, so status messages for older shipments stop verifying after a rotation.",
  ecpayEnabled: "Enabled for buyers",
  ecpayDisabled: "Not enabled",
  ecpayEnable: "Enable",
  ecpayDisable: "Disable",
  ecpayQualified: "Checked with ECPay",
  ecpayNotQualified: "Not checked yet",
  ecpayOkVerified: "OK mart verified",
  ecpayOkPending: "OK mart pending",
  ecpayStatusURL: "Status URL (read-only)",
  ecpayStatusHint: "Enter this address as the logistics status notification URL in the ECPay merchant back office.",
  ecpayInvalid: "Check the merchant ID, both keys and the sender details.",
  ecpaySaved: "Connection saved.",
  ecpayEnabledDone: "Setting saved.",
  // CVS settings card
  cvsTitle: "Convenience-store pickup",
  cvsIntro: "Choose which chains buyers can use and whether they may pay at pickup.",
  cvsChains: "Chains offered",
  cvsPayAtPickup: "Allow pay at pickup",
  cvsMaxTWD: "Pay-at-pickup limit per order (NT$, 1–20000)",
  cvsMaxOpen: "Unpaid pickup orders allowed at once (1–500)",
  cvsPayNote: "You collect the money through your own channel or ECPay collection; this site never holds it.",
  cvsInvalid: "Check the limits: NT$1–20000 per order and 1–500 open orders; pay at pickup needs a limit.",
  cvsSaved: "Pickup settings saved.",
  // delivery-service editor
  modeLabel: "Mode",
  modeManual: "Manual (you ship)",
  modeApi: "API (ECPay)",
  modeApiHint: "Available for store-pickup services once the ECPay connection is checked and enabled.",
  // order section
  secTitle: "Store pickup",
  secLoadFailed: "The pickup section could not be loaded.",
  sourceLabel: "Store source",
  manualOnly: "ECPay cannot create a shipment for a store the buyer typed. Ship it yourself with the shipment form.",
  createButton: "Create store shipment",
  createTitle: "Create store shipment",
  createConfirm: (days: number | null) =>
    days === null
      ? "ECPay will deduct the freight from your ECPay account balance. Drop the parcel within the validity days."
      : `ECPay will deduct the freight from your ECPay account balance. Drop the parcel within ${days} days.`,
  createSubmit: "Create and pay freight",
  createDone: "Shipment requested. The result appears here shortly.",
  createNotEligible: "This order cannot get a store shipment in its current state.",
  code: "Drop-off code",
  codeMissing: "The code is not available here. Check it in the ECPay back office.",
  printButton: "Print label",
  printThermal: "A6 thermal size",
  printHint: "Opens ECPay's label page in a new tab.",
  printUnsupported: "OK mart has no printable label. Give the code at the store.",
  attemptTitle: "Attempt",
  state: "State",
  updated: "Updated (UTC)",
  goods: "Goods amount",
  collect: "To collect",
  events: "Timeline",
  noEvents: "No events yet.",
  shipmentStates: {
    REQUESTED: "Requested",
    UNKNOWN: "Result unknown",
    FAILED: "Failed",
    ABANDONED: "Abandoned",
    CREATED: "Label created",
    AT_DC: "At the logistics center",
    AT_STORE: "At the store",
    PICKED_UP: "Picked up",
    UNCLAIMED: "Not collected",
  },
  alerts: {
    duplicate_label_risk: "A later ECPay report arrived for an abandoned or failed attempt. Check the ECPay back office for a duplicate label.",
    collection_conflict: "ECPay's collection report disagrees with what you recorded. Check the order.",
  },
  alertGeneric: "ECPay reported something that needs a look.",
  unknownBanner:
    "ECPay did not confirm the creation. Do not create another label until you have checked the ECPay back office.",
  failedBanner: "ECPay did not create the shipment. Nothing was charged. You can try again or ship the order yourself with the form below.",
  refundedWarn: "Refunded. Do not drop this parcel.",
  manualButton: "Ship it myself instead",
  manualTitle: "Use manual shipping instead",
  manualConfirm:
    "This abandons the ECPay shipment so you can record your own shipment. If a label was really created, using it later can duplicate the parcel.",
  manualChecked: "I checked the ECPay back office and no label exists for this order.",
  manualSubmit: "Abandon and ship myself",
  manualDone: "The ECPay shipment was abandoned. Record your own shipment below.",
  tradeFound: "ECPay already had this shipment. It is now shown as created.",
  // pay-at-pickup panel
  payTitle: "Pay at pickup",
  payState: "Collection status",
  payStates: {
    PENDING: "Waiting for payment at pickup",
    COLLECTED: "Paid and collected",
    RETURNED: "Not collected · returned",
    REFUNDED_OFFLINE: "Refunded outside this site",
    CANCELLED: "Cancelled · stock released",
    RESTOCKED: "Returned · stock restored",
  },
  payNote: "This site never holds pay-at-pickup money. Record what happened; refunds are made outside this site.",
  collected: "Mark paid at pickup",
  returned: "Mark returned unclaimed",
  refundedOffline: "Mark refunded outside this site",
  cancelOrder: "Cancel order and release stock",
  restockOrder: "Parcel is back — restore stock",
  confirmTitle: "Confirm",
  confirmCollected: "Record that the buyer paid and collected the parcel? This cannot be undone here.",
  confirmReturned: "Record that the parcel was not collected and came back? Stock is restored separately.",
  confirmRefundedOffline: "Record that you refunded the buyer outside this site? No money moves through this site.",
  confirmCancel: "Cancel this unshipped order and release its stock? The buyer's pickup order ends.",
  confirmRestock: "The parcel is back with you. Restore its stock now? This cannot be undone.",
  confirmSubmit: "Confirm",
  payDone: "Saved. The order shows the server state.",
  // print tab
  printTabTitle: "Print store label",
  printTabOpening: "Opening ECPay's label page…",
  printTabManual: "If the page does not open, press the button.",
  printTabOpen: "Open the label page",
  printTabFailed: "The label could not be prepared. Close this tab and try again from the order.",
  printTabSignedOut: "Sign in again in the orders page, then reopen this tab.",
  printTabBad: "This link is not valid. Open it from the order.",
  // errors (§8 refusals and the unit's own)
  errors: {
    not_shippable: "This order cannot be shipped in its current state.",
    no_cvs_destination: "This order has no ECPay-verified store, so ECPay cannot create a shipment.",
    connection_unavailable: "The ECPay connection is missing or disabled.",
    cvs_recipient_rejected: "ECPay would refuse the recipient name or mobile. Contact the buyer.",
    cvs_environment_mismatch: "This order was paid in another environment than the ECPay connection.",
    cvs_amount_exceeds: "The amount is above the convenience-store limit.",
    print_unsupported: "OK mart has no printable label. Give the code at the store.",
    ecpay_shows_movement: "ECPay shows movement on this shipment. Do not abandon it; wait or check the back office.",
    ecpay_trade_found: "ECPay already had this shipment. It is now shown as created.",
    ecpay_probe_failed: "ECPay did not accept these keys. Check the merchant ID, keys and account type.",
    invalid_sender: "The sender name or mobile was refused.",
    ecpay_environment_not_allowed: "This deployment does not allow that ECPay environment.",
    invalid_settings: "The pickup settings were refused. Check the limits.",
    not_pay_at_pickup: "This is not a pay-at-pickup order.",
    not_shipped: "Record the shipment first.",
    collection_state_changed: "The pickup payment state changed. Reload the order and check it.",
    not_cancellable: "This order can no longer be cancelled here.",
    cvs_attempt_in_flight: "An ECPay shipment may already exist. Resolve it first.",
    parcel_not_returned: "The parcel is not shown as returned yet.",
    version_changed: "This changed since you loaded it. Reload the order and try again.",
    version_conflict: "This changed since you loaded it. Reload and try again.",
    idempotency_conflict: "This request conflicts with an earlier one. Reload the order and try again.",
  } as Record<string, string>,
};
export type LogisticsCopy = typeof en;

export const logisticsCopy: Record<Locale, LogisticsCopy> = {
  en,
  "zh-CN": {
    chains: { cvs_711: "7-ELEVEN", cvs_familymart: "全家", cvs_hilife: "莱尔富", cvs_okmart: "OK超商" },
    save: "保存", saving: "保存中…", retry: "重试", retrySame: "重试相同请求", cancel: "取消", close: "关闭",
    copy: "复制", copied: "已复制", copyFailed: "复制失败，请选中文字后手动复制。", loading: "加载中…",
    unavailable: "此区块暂时无法加载，请重试。", noPermission: "当前账号没有修改这些设置的权限。",
    uncertain: "结果尚未确认。重试会安全地送出相同请求，或重新加载。",
    ecpayTitle: "绿界物流",
    ecpayIntro: "连接你自己的绿界物流账户后，买家可在绿界地图选择门市，你也可以直接建立超商寄件。未连接时，买家自行填写门市，由你自己寄出。",
    ecpayNone: "尚未连接。", ecpayEnv: "环境", ecpayEnvBadge: { SANDBOX: "测试（沙盒）", LIVE: "正式" },
    ecpayMode: "账户类型", ecpayModes: { C2C: "店到店（C2C）", B2C: "企业到店（B2C）" },
    ecpayMerchantID: "绿界商店代号", ecpayHashKey: "HashKey", ecpayHashIV: "HashIV",
    ecpaySenderName: "寄件人姓名（最多 10 字）", ecpaySenderPhone: "寄件人手机（09xxxxxxxx）",
    ecpaySecretsNote: "密钥只会送出一次，之后不再显示。要更换请重新输入。",
    ecpayConnect: "连接并检查", ecpayRotate: "更换密钥", ecpayChange: "更换连接",
    ecpayRotateWarn: "请在没有「已建单到取货」之间的寄件时更换：绿界只保留一组有效密钥，更换后旧寄件的状态通知将无法验证。",
    ecpayEnabled: "已对买家启用", ecpayDisabled: "未启用", ecpayEnable: "启用", ecpayDisable: "停用",
    ecpayQualified: "已通过绿界检查", ecpayNotQualified: "尚未检查", ecpayOkVerified: "OK超商已验证", ecpayOkPending: "OK超商待验证",
    ecpayStatusURL: "状态通知网址（只读）", ecpayStatusHint: "请把此网址填入绿界后台的物流状态通知网址。",
    ecpayInvalid: "请检查商店代号、两组密钥与寄件人资料。", ecpaySaved: "连接已保存。", ecpayEnabledDone: "设置已保存。",
    cvsTitle: "超商取货", cvsIntro: "选择买家可用的超商品牌，以及是否允许取货付款。",
    cvsChains: "提供的超商", cvsPayAtPickup: "允许取货付款", cvsMaxTWD: "单笔取货付款上限（NT$，1–20000）",
    cvsMaxOpen: "同时允许的未取货付款订单数（1–500）",
    cvsPayNote: "款项由你通过自己的渠道或绿界代收，本站不经手资金。",
    cvsInvalid: "请检查上限：单笔 NT$1–20000、未取货订单 1–500；开启取货付款需设定上限。", cvsSaved: "取货设置已保存。",
    modeLabel: "模式", modeManual: "手动（自行寄出）", modeApi: "API（绿界）",
    modeApiHint: "绿界连接通过检查并启用后，门店取货服务才能选用。",
    secTitle: "门店取货", secLoadFailed: "无法加载取货区块。", sourceLabel: "门店来源",
    manualOnly: "买家自填的门店无法由绿界建立寄件，请用出货表单自行出货。",
    createButton: "建立超商寄件", createTitle: "建立超商寄件",
    createConfirm: (days) =>
      days === null
        ? "绿界将从你的绿界账户余额扣运费；请在有效期内交寄。"
        : `绿界将从你的绿界账户余额扣运费；请在 ${days} 天内交寄。`,
    createSubmit: "建立并扣运费", createDone: "已提交寄件，结果稍后显示在这里。", createNotEligible: "此订单目前的状态不能建立超商寄件。",
    code: "寄件代码", codeMissing: "此处没有代码，请到绿界后台查看。",
    printButton: "列印托运单", printThermal: "A6 热感应尺寸", printHint: "会在新分页打开绿界的托运单页面。",
    printUnsupported: "OK超商没有可列印的托运单，请到门市出示代码。",
    attemptTitle: "第几次寄件", state: "状态", updated: "更新时间（UTC）", goods: "商品金额", collect: "代收金额",
    events: "时间线", noEvents: "尚无事件。",
    shipmentStates: {
      REQUESTED: "已提交", UNKNOWN: "结果未确认", FAILED: "失败", ABANDONED: "已放弃", CREATED: "已建单",
      AT_DC: "已到物流中心", AT_STORE: "已到店", PICKED_UP: "已取货", UNCLAIMED: "逾期未取",
    },
    alerts: {
      duplicate_label_risk: "已放弃或失败的寄件收到了绿界的后续通知，请到绿界后台确认是否有重复的托运单。",
      collection_conflict: "绿界的代收回报与你记录的不一致，请核对订单。",
    },
    alertGeneric: "绿界回报了需要留意的事项。",
    unknownBanner: "绿界未确认建单结果。请先到绿界后台确认，再决定是否重新建单，不要直接重复建立。",
    failedBanner: "绿界没有建立寄件，也没有扣款。可以重试，或用下方表单自行出货。",
    refundedWarn: "已退款，请勿交寄。", manualButton: "改用手动出货", manualTitle: "改用手动出货",
    manualConfirm: "这会放弃绿界寄件，让你记录自己的出货。若托运单其实已建立，之后再使用可能造成包裹重复。",
    manualChecked: "我已到绿界后台确认此订单没有托运单。", manualSubmit: "放弃并自行出货",
    manualDone: "已放弃绿界寄件，请在下方记录你自己的出货。", tradeFound: "绿界已有这笔寄件，现已显示为已建单。",
    payTitle: "取货付款", payState: "收款状态",
    payStates: {
      PENDING: "等待取货时付款", COLLECTED: "已取货付款", RETURNED: "未取货·已退回",
      REFUNDED_OFFLINE: "已在本站外退款", CANCELLED: "已取消·库存已释放", RESTOCKED: "已退回·库存已恢复",
    },
    payNote: "本站不经手取货付款的款项。请记录实际情况；退款在本站外进行。",
    collected: "已收款", returned: "已退回", refundedOffline: "已线下退款",
    cancelOrder: "取消订单并释放库存", restockOrder: "已收回包裹，恢复库存",
    confirmTitle: "请确认",
    confirmCollected: "记录买家已取货并付款？此处无法撤销。",
    confirmReturned: "记录包裹未被取走并已退回？库存需另行恢复。",
    confirmRefundedOffline: "记录你已在本站外退款给买家？款项不经过本站。",
    confirmCancel: "取消这笔未出货订单并释放库存？买家的取货订单将结束。",
    confirmRestock: "包裹已回到你手上，现在恢复库存？此操作无法撤销。",
    confirmSubmit: "确认", payDone: "已保存，订单显示服务器状态。",
    printTabTitle: "列印门市托运单", printTabOpening: "正在打开绿界托运单页面…", printTabManual: "若页面没有打开，请按下按钮。",
    printTabOpen: "打开托运单页面", printTabFailed: "无法准备托运单，请关闭此分页后从订单重试。",
    printTabSignedOut: "请先在订单页重新登录，再重新打开此分页。", printTabBad: "此链接无效，请从订单页打开。",
    errors: {
      not_shippable: "此订单目前的状态不能出货。", no_cvs_destination: "此订单没有经绿界核对的门市，绿界无法建立寄件。",
      connection_unavailable: "绿界连接不存在或已停用。", cvs_recipient_rejected: "绿界会拒绝此收件人姓名或手机，请联系买家。",
      cvs_environment_mismatch: "此订单的付款环境与绿界连接不同。", cvs_amount_exceeds: "金额超过超商上限。",
      print_unsupported: "OK超商没有可列印的托运单，请到门市出示代码。",
      ecpay_shows_movement: "绿界显示此寄件已有动态，请勿放弃；请等待或到后台确认。", ecpay_trade_found: "绿界已有这笔寄件，现已显示为已建单。",
      ecpay_probe_failed: "绿界不接受这些密钥，请检查商店代号、密钥与账户类型。", invalid_sender: "寄件人姓名或手机被拒绝。",
      ecpay_environment_not_allowed: "此部署不允许该绿界环境。", invalid_settings: "取货设置被拒绝，请检查上限。",
      not_pay_at_pickup: "这不是取货付款订单。", not_shipped: "请先记录出货。", collection_state_changed: "取货付款状态已变更，请重新读取订单确认。",
      not_cancellable: "此订单已无法在此取消。", cvs_attempt_in_flight: "可能已有绿界寄件，请先处理。", parcel_not_returned: "包裹尚未显示为已退回。",
      version_changed: "内容在你读取后已变更，请重新读取订单后重试。", version_conflict: "内容在你读取后已变更，请重新加载后重试。",
      idempotency_conflict: "此请求与先前的请求冲突，请重新读取订单后重试。",
    },
  },
  "zh-TW": {
    chains: { cvs_711: "7-ELEVEN", cvs_familymart: "全家", cvs_hilife: "萊爾富", cvs_okmart: "OK超商" },
    save: "儲存", saving: "儲存中…", retry: "重試", retrySame: "重試相同請求", cancel: "取消", close: "關閉",
    copy: "複製", copied: "已複製", copyFailed: "複製失敗，請選取文字後手動複製。", loading: "載入中…",
    unavailable: "此區塊暫時無法載入，請重試。", noPermission: "此帳號沒有修改這些設定的權限。",
    uncertain: "結果尚未確認。重試會安全地送出相同請求，或重新載入。",
    ecpayTitle: "綠界物流",
    ecpayIntro: "連接你自己的綠界物流帳戶後，買家可在綠界地圖選擇門市，你也可以直接建立超商寄件。未連接時，買家自行填寫門市，由你自己寄出。",
    ecpayNone: "尚未連接。", ecpayEnv: "環境", ecpayEnvBadge: { SANDBOX: "測試（沙盒）", LIVE: "正式" },
    ecpayMode: "帳戶類型", ecpayModes: { C2C: "店到店（C2C）", B2C: "企業到店（B2C）" },
    ecpayMerchantID: "綠界特店編號", ecpayHashKey: "HashKey", ecpayHashIV: "HashIV",
    ecpaySenderName: "寄件人姓名（最多 10 字）", ecpaySenderPhone: "寄件人手機（09xxxxxxxx）",
    ecpaySecretsNote: "金鑰只會送出一次，之後不再顯示。要更換請重新輸入。",
    ecpayConnect: "連接並檢查", ecpayRotate: "更換金鑰", ecpayChange: "更換連接",
    ecpayRotateWarn: "請在沒有「已建單到取貨」之間的寄件時更換：綠界只保留一組有效金鑰，更換後舊寄件的狀態通知將無法驗證。",
    ecpayEnabled: "已對買家啟用", ecpayDisabled: "未啟用", ecpayEnable: "啟用", ecpayDisable: "停用",
    ecpayQualified: "已通過綠界檢查", ecpayNotQualified: "尚未檢查", ecpayOkVerified: "OK超商已驗證", ecpayOkPending: "OK超商待驗證",
    ecpayStatusURL: "狀態通知網址（唯讀）", ecpayStatusHint: "請把此網址填入綠界後台的物流狀態通知網址。",
    ecpayInvalid: "請檢查特店編號、兩組金鑰與寄件人資料。", ecpaySaved: "連接已儲存。", ecpayEnabledDone: "設定已儲存。",
    cvsTitle: "超商取貨", cvsIntro: "選擇買家可用的超商品牌，以及是否允許取貨付款。",
    cvsChains: "提供的超商", cvsPayAtPickup: "允許取貨付款", cvsMaxTWD: "單筆取貨付款上限（NT$，1–20000）",
    cvsMaxOpen: "同時允許的未取貨付款訂單數（1–500）",
    cvsPayNote: "款項由你透過自己的管道或綠界代收，本站不經手資金。",
    cvsInvalid: "請檢查上限：單筆 NT$1–20000、未取貨訂單 1–500；開啟取貨付款需設定上限。", cvsSaved: "取貨設定已儲存。",
    modeLabel: "模式", modeManual: "手動（自行寄出）", modeApi: "API（綠界）",
    modeApiHint: "綠界連接通過檢查並啟用後，超商取貨服務才能選用。",
    secTitle: "門市取貨", secLoadFailed: "無法載入取貨區塊。", sourceLabel: "門市來源",
    manualOnly: "買家自填的門市無法由綠界建立寄件，請用出貨表單自行出貨。",
    createButton: "建立超商寄件", createTitle: "建立超商寄件",
    createConfirm: (days) =>
      days === null
        ? "綠界將從你的綠界帳戶餘額扣運費；請在有效期限內交寄。"
        : `綠界將從你的綠界帳戶餘額扣運費；請在 ${days} 天內交寄。`,
    createSubmit: "建立並扣運費", createDone: "已送出寄件，結果稍後顯示在這裡。", createNotEligible: "此訂單目前的狀態不能建立超商寄件。",
    code: "寄件代碼", codeMissing: "此處沒有代碼，請到綠界後台查看。",
    printButton: "列印託運單", printThermal: "A6 熱感應尺寸", printHint: "會在新分頁開啟綠界的託運單頁面。",
    printUnsupported: "OK超商沒有可列印的託運單，請到門市出示代碼。",
    attemptTitle: "第幾次寄件", state: "狀態", updated: "更新時間（UTC）", goods: "商品金額", collect: "代收金額",
    events: "時間線", noEvents: "尚無事件。",
    shipmentStates: {
      REQUESTED: "已送出", UNKNOWN: "結果未確認", FAILED: "失敗", ABANDONED: "已放棄", CREATED: "已建單",
      AT_DC: "已到物流中心", AT_STORE: "已到店", PICKED_UP: "已取貨", UNCLAIMED: "逾期未取",
    },
    alerts: {
      duplicate_label_risk: "已放棄或失敗的寄件收到了綠界的後續通知，請到綠界後台確認是否有重複的託運單。",
      collection_conflict: "綠界的代收回報與你記錄的不一致，請核對訂單。",
    },
    alertGeneric: "綠界回報了需要留意的事項。",
    unknownBanner: "綠界未確認建單結果。請先到綠界後台確認，再決定是否重新建單，不要直接重複建立。",
    failedBanner: "綠界沒有建立寄件，也沒有扣款。可以重試，或用下方表單自行出貨。",
    refundedWarn: "已退款，請勿交寄。", manualButton: "改用手動出貨", manualTitle: "改用手動出貨",
    manualConfirm: "這會放棄綠界寄件，讓你記錄自己的出貨。若託運單其實已建立，之後再使用可能造成包裹重複。",
    manualChecked: "我已到綠界後台確認此訂單沒有託運單。", manualSubmit: "放棄並自行出貨",
    manualDone: "已放棄綠界寄件，請在下方記錄你自己的出貨。", tradeFound: "綠界已有這筆寄件，現已顯示為已建單。",
    payTitle: "取貨付款", payState: "收款狀態",
    payStates: {
      PENDING: "等待取貨時付款", COLLECTED: "已取貨付款", RETURNED: "未取貨·已退回",
      REFUNDED_OFFLINE: "已在本站外退款", CANCELLED: "已取消·庫存已釋放", RESTOCKED: "已退回·庫存已恢復",
    },
    payNote: "本站不經手取貨付款的款項。請記錄實際情況；退款在本站外進行。",
    collected: "已收款", returned: "已退回", refundedOffline: "已線下退款",
    cancelOrder: "取消訂單並釋放庫存", restockOrder: "已收回包裹，恢復庫存",
    confirmTitle: "請確認",
    confirmCollected: "記錄買家已取貨並付款？此處無法撤銷。",
    confirmReturned: "記錄包裹未被取走並已退回？庫存需另行恢復。",
    confirmRefundedOffline: "記錄你已在本站外退款給買家？款項不經過本站。",
    confirmCancel: "取消這筆未出貨訂單並釋放庫存？買家的取貨訂單將結束。",
    confirmRestock: "包裹已回到你手上，現在恢復庫存？此操作無法撤銷。",
    confirmSubmit: "確認", payDone: "已儲存，訂單顯示伺服器狀態。",
    printTabTitle: "列印門市託運單", printTabOpening: "正在開啟綠界託運單頁面…", printTabManual: "若頁面沒有開啟，請按下按鈕。",
    printTabOpen: "開啟託運單頁面", printTabFailed: "無法準備託運單，請關閉此分頁後從訂單重試。",
    printTabSignedOut: "請先在訂單頁重新登入，再重新開啟此分頁。", printTabBad: "此連結無效，請從訂單頁開啟。",
    errors: {
      not_shippable: "此訂單目前的狀態不能出貨。", no_cvs_destination: "此訂單沒有經綠界核對的門市，綠界無法建立寄件。",
      connection_unavailable: "綠界連接不存在或已停用。", cvs_recipient_rejected: "綠界會拒絕此收件人姓名或手機，請聯絡買家。",
      cvs_environment_mismatch: "此訂單的付款環境與綠界連接不同。", cvs_amount_exceeds: "金額超過超商上限。",
      print_unsupported: "OK超商沒有可列印的託運單，請到門市出示代碼。",
      ecpay_shows_movement: "綠界顯示此寄件已有動態，請勿放棄；請等待或到後台確認。", ecpay_trade_found: "綠界已有這筆寄件，現已顯示為已建單。",
      ecpay_probe_failed: "綠界不接受這些金鑰，請檢查特店編號、金鑰與帳戶類型。", invalid_sender: "寄件人姓名或手機被拒絕。",
      ecpay_environment_not_allowed: "此部署不允許該綠界環境。", invalid_settings: "取貨設定被拒絕，請檢查上限。",
      not_pay_at_pickup: "這不是取貨付款訂單。", not_shipped: "請先記錄出貨。", collection_state_changed: "取貨付款狀態已變更，請重新讀取訂單確認。",
      not_cancellable: "此訂單已無法在此取消。", cvs_attempt_in_flight: "可能已有綠界寄件，請先處理。", parcel_not_returned: "包裹尚未顯示為已退回。",
      version_changed: "內容在你讀取後已變更，請重新讀取訂單後重試。", version_conflict: "內容在你讀取後已變更，請重新載入後重試。",
      idempotency_conflict: "此請求與先前的請求衝突，請重新讀取訂單後重試。",
    },
  },
};

// Merchant-facing text for an error code: this unit's list first, then the orders copy's, then its default.
export function logisticsError(c: LogisticsCopy, orders: { errors: Record<string, string> }, code: string): string {
  return c.errors[code] ?? orders.errors[code] ?? orders.errors.default;
}
