// Copy for the admin orders page and its refund/shipment/export sections (BFF orders* -> Go merchantorders).
// Carrier display names follow refund-fulfilment-ui Q3; refund state labels follow stripe-refund-v1 §7.1 (UI paragraph).
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Orders",
  subtitle: "Review saved orders and their frozen checkout details.",
  store: "Store",
  filter: "Order status",
  refresh: "Refresh",
  loading: "Loading orders…",
  detailLoading: "Loading order details…",
  empty: "No orders match this status in this store.",
  signedOut: "Sign in to view orders.",
  forbidden: "This account does not have permission to read orders.",
  notFound: "This order is unavailable in the selected store.",
  unavailable: "Orders are temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  previous: "Previous page",
  next: "Next page",
  pageCount: "Orders on this page",
  order: "Order",
  created: "Created (UTC)",
  total: "Total",
  commercial: "Order status",
  payment: "Payment status",
  fulfillment: "Fulfillment",
  work: "Payment work",
  test: "Test environment",
  expand: "Show order details",
  collapse: "Hide order details",
  items: "Items",
  product: "Product",
  unit: "Unit price",
  quantity: "Quantity",
  amount: "Line total",
  subtotal: "Items subtotal",
  discount: "Discount",
  shipping: "Shipping",
  shippingTax: "Shipping tax",
  tax: "Tax",
  grandTotal: "Order total",
  recipient: "Receiving details",
  name: "Recipient",
  phone: "Phone",
  method: "Delivery method",
  address: "Address",
  pickupName: "Pickup store",
  pickupCode: "Store code",
  snapshot: "Saved checkout details; store selection and merchant attestation do not confirm current carrier eligibility.",
  exportCsv: "Export unshipped (CSV)",
  exportHint: "In your spreadsheet, import the phone, postal code and pickup code columns as text so leading zeros are kept. Each file holds at most 1000 orders; if more are unshipped, ship or export again for the rest.",
  sectionLoading: "Loading…",
  sectionUnavailable: "This section could not be loaded. Try again.",
  close: "Close",
  refundTitle: "Refund",
  refundCaptured: "Captured",
  refundRefunded: "Refunded",
  refundInProgress: "In progress",
  refundRefundable: "Refundable",
  refundNone: "No refunds yet.",
  refundColAmount: "Amount",
  refundColReason: "Reason",
  refundColStatus: "Status",
  refundColRequested: "Requested (UTC)",
  refundColStripe: "Stripe refund ID",
  refundRefresh: "Refresh status",
  refundRefreshed: "Status refresh requested. The list updates from the server.",
  refundRefreshLater: "Refreshed too recently. Try again in a few seconds.",
  refundButton: "Refund…",
  refundDialogTitle: "Refund this order",
  refundAmount: "Refund amount",
  refundAmountHint: (max: string, whole: boolean) =>
    `Up to ${max}${whole ? "; whole dollars only" : ""}.`,
  refundAmountInvalid: (max: string, whole: boolean) =>
    `Enter an amount above zero and up to ${max}${whole ? " in whole dollars" : ""}.`,
  refundReason: "Reason",
  refundContinue: "Review refund",
  refundConfirmTitle: "Confirm refund",
  refundConfirm: (amount: string, currency: string) =>
    `Refund ${amount} (${currency}) to the buyer's original payment method? A refund cannot be undone once sent to Stripe.`,
  refundBack: "Back",
  refundSubmit: "Confirm refund",
  refundSending: "Sending…",
  refundDone: "Refund requested. The list below shows the server state.",
  refundUncertain: "The result is not known yet. Retry sends the identical request safely, or close and check the list.",
  refundRetry: "Retry the same request",
  refundReasons: {
    requested_by_customer: "Requested by customer",
    duplicate: "Duplicate charge",
  },
  refundStates: {
    REQUESTED: "Processing",
    SUBMITTING: "Processing",
    PENDING: "Processing",
    SUCCEEDED: "Refunded",
    FAILED: "Failed",
    CANCELED: "Canceled",
    REJECTED: "Rejected",
    UNKNOWN: "Needs support",
  },
  failureReasons: {
    lost_or_stolen_card: "Card reported lost or stolen",
    expired_or_canceled_card: "Card expired or canceled",
    charge_for_pending_refund_disputed: "Charge disputed while the refund was pending",
    insufficient_funds: "Insufficient funds",
    declined: "Declined by the card issuer",
    merchant_request: "Canceled at the merchant's request",
    unknown: "Unknown reason",
    first_send_rejected: "Rejected by Stripe",
    external_refund_detected: "Not sent: a refund made outside this system was detected",
    send_window_closed: "Not sent: the send window closed",
  },
  shipTitle: "Shipment",
  shipHint: "Records the shipment you arranged yourself. It does not create a carrier label or track delivery.",
  shipNone: "Not shipped yet.",
  shipNotEligible: "This order cannot be marked shipped in its current payment or fulfillment state.",
  shipCarrier: "Carrier",
  shipCarrierName: "Carrier name",
  shipTracking: "Tracking number",
  shipLink: "Tracking link",
  shipUrl: "Tracking link (optional, https)",
  shipNote: "Internal note (optional, never shown to the buyer)",
  shipMark: "Mark shipped",
  shipRecorded: "Recorded (UTC)",
  shipCorrect: "Correct",
  shipCorrectSave: "Save correction",
  shipVoid: "Void",
  shipVoidTitle: "Void this shipment",
  shipVoidReason: "Void reason",
  shipVoidConfirm: "Void shipment",
  cancel: "Cancel",
  shipSending: "Saving…",
  shipUncertain: "The result is not known yet. Retry sends the identical request safely, or reload the order.",
  shipRetry: "Retry the same request",
  shipDone: "Shipment saved. The order shows the server state.",
  shipInvalidTracking: "Tracking number: 1–64 letters, digits, spaces or hyphens.",
  shipInvalidUrl: "Tracking link must be a plain https address without a port or credentials.",
  shipCarrierNameRequired: "Enter the carrier name (1–80 characters).",
  shipNoteTooLong: "The note is limited to 200 characters.",
  shipHistory: "Shipment history",
  shipHistoryEmpty: "No shipment records.",
  shipVersion: "Version",
  shipStatus: { SHIPPED: "Shipped", VOIDED: "Voided" },
  shipBy: "Recorded by",
  shipNoteLabel: "Note",
  voidReasons: {
    wrong_order: "Wrong order",
    wrong_tracking: "Wrong tracking number",
    not_dispatched: "Parcel was not dispatched",
    other: "Other",
  },
  carriers: {
    seven_eleven_cvs: "7-ELEVEN",
    familymart_cvs: "FamilyMart",
    hilife_cvs: "Hi-Life",
    okmart_cvs: "OK mart",
    sf_express: "SF Express",
    chunghwa_post: "Chunghwa Post",
    other: "Other",
  },
  errors: {
    refundable_changed: "The refundable amount changed. Review the new amount and try again.",
    exceeds_refundable: "The amount is more than what can still be refunded.",
    amount_step: "This currency only allows whole-dollar refund amounts.",
    not_refundable: "This payment cannot be refunded from here.",
    refund_blocked_review: "This payment is under review, so a refund is blocked. Contact support.",
    refund_limit: "This payment has reached its refund limit.",
    version_changed: "The shipment changed since you loaded it. Reload the order and try again.",
    not_shippable: "This order cannot be shipped in its current state.",
    invalid_carrier: "The carrier details are not valid.",
    invalid_tracking: "The tracking number is not valid.",
    invalid_url: "The tracking link is not valid.",
    void_requires_shipped: "Only a shipped record can be corrected or voided.",
    invalid_void: "The void request is not valid.",
    forbidden: "This account does not have permission for this action.",
    unauthorized: "Sign in again to continue.",
    not_found: "This order is unavailable in the selected store.",
    conflict: "This request conflicts with an earlier one. Reload the order and try again.",
    rate_limited: "Too many requests. Try again in a few seconds.",
    retry_later: "Temporarily unavailable. Try again.",
    default: "The request could not be completed. Reload the order and try again.",
  },
  statuses: {
    all: "All",
    DRAFT: "Draft",
    AWAITING_PAYMENT: "Awaiting payment",
    CONFIRMED: "Confirmed",
    CANCELLED: "Cancelled",
    shipped: "Shipped",
    unshipped: "Ready to ship",
    MERCHANT_SHIPPED: "Shipped by seller",
    PARTIALLY_REFUNDED: "Partially refunded",
    REFUNDED: "Refunded",
    MANUAL_UNASSIGNED: "Not assigned",
    PAID_ALLOCATION_FAILED: "Allocation needs review",
    NOT_STARTED: "Not started",
    PENDING: "Pending",
    AUTHORIZED: "Authorized · not captured",
    CAPTURED: "Captured",
    REVIEW_REQUIRED: "Review required",
    NONE: "None",
    READY: "Ready for payment work",
    home: "Home delivery",
    cvs_711: "7-ELEVEN pickup",
    cvs_familymart: "FamilyMart pickup",
    cvs_hilife: "Hi-Life pickup",
    cvs_okmart: "OK mart pickup",
    PROVIDER_LABEL_CREATED: "Carrier label created",
    cvs_pending: "Label created, not yet dropped",
  },
  // taiwan-cvs-logistics-v1 §16: payment mode, pay-at-pickup state and where the pickup store came from.
  payMode: "Payment mode",
  payModes: { card: "Card", pay_at_pickup: "Pay at pickup" },
  collectionLabel: "Pay-at-pickup status",
  collectionStates: {
    PENDING: "Waiting for pickup payment",
    COLLECTED: "Paid at pickup",
    RETURNED: "Not collected · returned",
    REFUNDED_OFFLINE: "Refunded outside this site",
    CANCELLED: "Cancelled · stock released",
    RESTOCKED: "Returned · stock restored",
  },
  sourceLabel: "Store source",
  pickupSources: {
    ecpay_directory: "Chosen on the ECPay store map (checked against the store list)",
    buyer_entered: "Store entered by the buyer (not verified; check it on the chain's site before shipping)",
    merchant_attested: "Attested by the seller",
  },
};
export type OrdersCopy = typeof en;

export const ordersCopy: Record<Locale, OrdersCopy> = {
  en,
  "zh-CN": {
    title: "订单", subtitle: "查看已保存订单与结账时的固定资料。", store: "店铺", filter: "订单状态",
    refresh: "刷新", loading: "正在读取订单…", detailLoading: "正在读取订单详情…",
    empty: "该店铺在此状态下没有订单。", signedOut: "请登录后查看订单。",
    forbidden: "当前账号没有读取订单的权限。", notFound: "所选店铺中无法读取此订单。",
    unavailable: "订单暂时无法读取，请重试。", noStore: "没有获授权的店铺。", retry: "重试",
    previous: "上一页", next: "下一页", pageCount: "本页订单数", order: "订单",
    created: "创建时间（UTC）", total: "总额", commercial: "订单状态", payment: "付款状态",
    fulfillment: "履约", work: "付款待办", test: "测试环境", expand: "展开订单详情", collapse: "收起订单详情",
    items: "商品明细", product: "商品", unit: "单价", quantity: "数量", amount: "小计",
    subtotal: "商品小计", discount: "优惠", shipping: "运费", shippingTax: "运费税",
    tax: "税额", grandTotal: "订单总额", recipient: "收货资料", name: "收件人", phone: "手机",
    method: "取货方式", address: "地址", pickupName: "取货门店", pickupCode: "店号",
    snapshot: "历史结账快照；选店与商家确认不代表当前承运资格已确认。",
    exportCsv: "导出未发货订单（CSV）",
    exportHint: "在表格软件中，请将手机、邮递区号与取货店号列以文本导入，以保留开头的 0。每个文件最多 1000 笔订单；若未发货订单更多，请发货后再次导出。",
    sectionLoading: "读取中…", sectionUnavailable: "此部分暂时无法读取，请重试。", close: "关闭",
    refundTitle: "退款", refundCaptured: "已扣款", refundRefunded: "已退款", refundInProgress: "处理中",
    refundRefundable: "可退款", refundNone: "尚无退款。", refundColAmount: "金额", refundColReason: "原因",
    refundColStatus: "状态", refundColRequested: "申请时间（UTC）", refundColStripe: "Stripe 退款编号",
    refundRefresh: "刷新状态", refundRefreshed: "已请求刷新状态，列表将以服务器为准更新。",
    refundRefreshLater: "刚刚已刷新过，请几秒后再试。",
    refundButton: "退款…", refundDialogTitle: "为此订单退款", refundAmount: "退款金额",
    refundAmountHint: (max: string, whole: boolean) => `最多 ${max}${whole ? "；仅限整数元" : ""}。`,
    refundAmountInvalid: (max: string, whole: boolean) => `请输入大于零且不超过 ${max} 的金额${whole ? "（整数元）" : ""}。`,
    refundReason: "原因", refundContinue: "核对退款", refundConfirmTitle: "确认退款",
    refundConfirm: (amount: string, currency: string) => `确认将 ${amount}（${currency}）退回买家原付款方式？退款一旦提交至 Stripe 即无法撤销。`,
    refundBack: "返回", refundSubmit: "确认退款", refundSending: "发送中…",
    refundDone: "已提交退款申请，下方列表为服务器状态。",
    refundUncertain: "结果尚未确认。重试会安全地发送相同请求，或关闭后查看列表。", refundRetry: "重试相同请求",
    refundReasons: { requested_by_customer: "买家要求", duplicate: "重复扣款" },
    refundStates: {
      REQUESTED: "处理中", SUBMITTING: "处理中", PENDING: "处理中", SUCCEEDED: "已退款",
      FAILED: "失败", CANCELED: "已取消", REJECTED: "已拒绝", UNKNOWN: "需要支持",
    },
    failureReasons: {
      lost_or_stolen_card: "卡片挂失或被盗", expired_or_canceled_card: "卡片已过期或已注销",
      charge_for_pending_refund_disputed: "退款处理期间该笔款项被争议", insufficient_funds: "余额不足",
      declined: "发卡行拒绝", merchant_request: "应商家要求取消", unknown: "原因不明",
      first_send_rejected: "Stripe 拒绝", external_refund_detected: "未发送：检测到系统外已退款",
      send_window_closed: "未发送：发送时限已过",
    },
    shipTitle: "出货", shipHint: "记录您自行安排的出货，不会产生物流面单或追踪送达。", shipNone: "尚未出货。",
    shipNotEligible: "此订单在目前的付款或履约状态下不能标记为已出货。",
    shipCarrier: "物流商", shipCarrierName: "物流商名称", shipTracking: "追踪单号",
    shipLink: "追踪链接", shipUrl: "追踪链接（选填，https）", shipNote: "内部备注（选填，买家看不到）", shipMark: "标记为已出货",
    shipRecorded: "记录时间（UTC）", shipCorrect: "更正", shipCorrectSave: "保存更正", shipVoid: "作废",
    shipVoidTitle: "作废此出货记录", shipVoidReason: "作废原因", shipVoidConfirm: "作废出货", cancel: "取消",
    shipSending: "保存中…", shipUncertain: "结果尚未确认。重试会安全地发送相同请求，或重新读取订单。",
    shipRetry: "重试相同请求", shipDone: "出货记录已保存，订单显示服务器状态。",
    shipInvalidTracking: "追踪单号：1–64 个字母、数字、空格或连字符。",
    shipInvalidUrl: "追踪链接须为不含端口与账号的 https 地址。", shipCarrierNameRequired: "请填写物流商名称（1–80 个字符）。",
    shipNoteTooLong: "备注最多 200 个字符。", shipHistory: "出货记录历史", shipHistoryEmpty: "没有出货记录。",
    shipVersion: "版本", shipStatus: { SHIPPED: "已出货", VOIDED: "已作废" }, shipBy: "记录者", shipNoteLabel: "备注",
    voidReasons: { wrong_order: "订单错误", wrong_tracking: "追踪单号错误", not_dispatched: "包裹未寄出", other: "其他" },
    carriers: {
      seven_eleven_cvs: "7-ELEVEN 交货便", familymart_cvs: "全家 店到店", hilife_cvs: "莱尔富", okmart_cvs: "OK mart",
      sf_express: "顺丰速运", chunghwa_post: "中华邮政", other: "其他",
    },
    errors: {
      refundable_changed: "可退款金额已变更，请核对新金额后重试。", exceeds_refundable: "金额超过剩余可退款金额。",
      amount_step: "此币种的退款金额只能是整数元。", not_refundable: "此笔付款无法在此退款。",
      refund_blocked_review: "此笔付款正在核对，退款已被拦截，请联系支持。", refund_limit: "此笔付款已达退款次数上限。",
      version_changed: "出货记录在您读取后已变更，请重新读取订单后重试。", not_shippable: "此订单目前的状态不能出货。",
      invalid_carrier: "物流商资料无效。", invalid_tracking: "追踪单号无效。", invalid_url: "追踪链接无效。",
      void_requires_shipped: "只有已出货的记录才能更正或作废。", invalid_void: "作废请求无效。",
      forbidden: "当前账号没有此操作的权限。", unauthorized: "请重新登录后继续。", not_found: "所选店铺中无法读取此订单。",
      conflict: "此请求与先前的请求冲突，请重新读取订单后重试。", rate_limited: "请求过多，请几秒后再试。",
      retry_later: "暂时无法使用，请重试。", default: "请求未能完成，请重新读取订单后重试。",
    },
    statuses: {
      all: "全部", DRAFT: "草稿", AWAITING_PAYMENT: "待付款", CONFIRMED: "已确认", CANCELLED: "已取消",
      shipped: "已出货", unshipped: "待出货", MERCHANT_SHIPPED: "商家已出货", PARTIALLY_REFUNDED: "部分退款", REFUNDED: "已退款",
      MANUAL_UNASSIGNED: "待分配", PAID_ALLOCATION_FAILED: "分配异常待核对", NOT_STARTED: "尚未开始",
      PENDING: "处理中", AUTHORIZED: "已授权·未扣款", CAPTURED: "已扣款", REVIEW_REQUIRED: "待核对",
      NONE: "无", READY: "待处理", home: "宅配", cvs_711: "7-ELEVEN 取货", cvs_familymart: "全家取货",
      cvs_hilife: "莱尔富取货", cvs_okmart: "OK超商取货", PROVIDER_LABEL_CREATED: "已建立物流单", cvs_pending: "已建单·待交寄",
    },
    payMode: "付款方式", payModes: { card: "信用卡", pay_at_pickup: "取货付款" },
    collectionLabel: "取货付款状态",
    collectionStates: {
      PENDING: "等待取货付款", COLLECTED: "已取货付款", RETURNED: "未取货·已退回",
      REFUNDED_OFFLINE: "已在本站外退款", CANCELLED: "已取消·库存已释放", RESTOCKED: "已退回·库存已恢复",
    },
    sourceLabel: "门店来源",
    pickupSources: {
      ecpay_directory: "已从绿界门市地图选取（已与门市名单核对）",
      buyer_entered: "买家自填门店（未验证，出货前请到超商官网核对）",
      merchant_attested: "卖家已确认",
    },
  },
  "zh-TW": {
    title: "訂單", subtitle: "查看已儲存訂單與結帳時的固定資料。", store: "商店", filter: "訂單狀態",
    refresh: "重新整理", loading: "正在讀取訂單…", detailLoading: "正在讀取訂單詳情…",
    empty: "此商店在該狀態下沒有訂單。", signedOut: "請登入後查看訂單。",
    forbidden: "此帳號沒有讀取訂單的權限。", notFound: "所選商店中無法讀取此訂單。",
    unavailable: "訂單暫時無法讀取，請重試。", noStore: "沒有獲授權的商店。", retry: "重試",
    previous: "上一頁", next: "下一頁", pageCount: "本頁訂單數", order: "訂單",
    created: "建立時間（UTC）", total: "總額", commercial: "訂單狀態", payment: "付款狀態",
    fulfillment: "履約", work: "付款待辦", test: "測試環境", expand: "展開訂單詳情", collapse: "收起訂單詳情",
    items: "商品明細", product: "商品", unit: "單價", quantity: "數量", amount: "小計",
    subtotal: "商品小計", discount: "折扣", shipping: "運費", shippingTax: "運費稅",
    tax: "稅額", grandTotal: "訂單總額", recipient: "收貨資料", name: "收件人", phone: "手機",
    method: "取貨方式", address: "地址", pickupName: "取貨門市", pickupCode: "店號",
    snapshot: "歷史結帳快照；選店與商家確認不代表目前承運資格已確認。",
    exportCsv: "匯出未出貨訂單（CSV）",
    exportHint: "在試算表軟體中，請將手機、郵遞區號與取貨店號欄位以文字匯入，以保留開頭的 0。每個檔案最多 1000 筆訂單；若未出貨訂單更多，請出貨後再次匯出。",
    sectionLoading: "讀取中…", sectionUnavailable: "此部分暫時無法讀取，請重試。", close: "關閉",
    refundTitle: "退款", refundCaptured: "已扣款", refundRefunded: "已退款", refundInProgress: "處理中",
    refundRefundable: "可退款", refundNone: "尚無退款。", refundColAmount: "金額", refundColReason: "原因",
    refundColStatus: "狀態", refundColRequested: "申請時間（UTC）", refundColStripe: "Stripe 退款編號",
    refundRefresh: "重新整理狀態", refundRefreshed: "已要求重新整理狀態，列表將以伺服器為準更新。",
    refundRefreshLater: "剛剛已重新整理過，請幾秒後再試。",
    refundButton: "退款…", refundDialogTitle: "為此訂單退款", refundAmount: "退款金額",
    refundAmountHint: (max: string, whole: boolean) => `最多 ${max}${whole ? "；僅限整數元" : ""}。`,
    refundAmountInvalid: (max: string, whole: boolean) => `請輸入大於零且不超過 ${max} 的金額${whole ? "（整數元）" : ""}。`,
    refundReason: "原因", refundContinue: "核對退款", refundConfirmTitle: "確認退款",
    refundConfirm: (amount: string, currency: string) => `確認將 ${amount}（${currency}）退回買家原付款方式？退款一旦送出至 Stripe 即無法撤銷。`,
    refundBack: "返回", refundSubmit: "確認退款", refundSending: "送出中…",
    refundDone: "已送出退款申請，下方列表為伺服器狀態。",
    refundUncertain: "結果尚未確認。重試會安全地送出相同請求，或關閉後查看列表。", refundRetry: "重試相同請求",
    refundReasons: { requested_by_customer: "買家要求", duplicate: "重複扣款" },
    refundStates: {
      REQUESTED: "處理中", SUBMITTING: "處理中", PENDING: "處理中", SUCCEEDED: "已退款",
      FAILED: "失敗", CANCELED: "已取消", REJECTED: "已拒絕", UNKNOWN: "需要支援",
    },
    failureReasons: {
      lost_or_stolen_card: "卡片掛失或遭竊", expired_or_canceled_card: "卡片已過期或已註銷",
      charge_for_pending_refund_disputed: "退款處理期間該筆款項遭爭議", insufficient_funds: "餘額不足",
      declined: "發卡行拒絕", merchant_request: "應商家要求取消", unknown: "原因不明",
      first_send_rejected: "Stripe 拒絕", external_refund_detected: "未送出：偵測到系統外已退款",
      send_window_closed: "未送出：送出時限已過",
    },
    shipTitle: "出貨", shipHint: "記錄您自行安排的出貨，不會產生物流面單或追蹤送達。", shipNone: "尚未出貨。",
    shipNotEligible: "此訂單在目前的付款或履約狀態下不能標記為已出貨。",
    shipCarrier: "物流商", shipCarrierName: "物流商名稱", shipTracking: "追蹤單號",
    shipLink: "追蹤連結", shipUrl: "追蹤連結（選填，https）", shipNote: "內部備註（選填，買家看不到）", shipMark: "標記為已出貨",
    shipRecorded: "記錄時間（UTC）", shipCorrect: "更正", shipCorrectSave: "儲存更正", shipVoid: "作廢",
    shipVoidTitle: "作廢此出貨記錄", shipVoidReason: "作廢原因", shipVoidConfirm: "作廢出貨", cancel: "取消",
    shipSending: "儲存中…", shipUncertain: "結果尚未確認。重試會安全地送出相同請求，或重新讀取訂單。",
    shipRetry: "重試相同請求", shipDone: "出貨記錄已儲存，訂單顯示伺服器狀態。",
    shipInvalidTracking: "追蹤單號：1–64 個字母、數字、空格或連字號。",
    shipInvalidUrl: "追蹤連結須為不含連接埠與帳號的 https 網址。", shipCarrierNameRequired: "請填寫物流商名稱（1–80 個字元）。",
    shipNoteTooLong: "備註最多 200 個字元。", shipHistory: "出貨記錄歷史", shipHistoryEmpty: "沒有出貨記錄。",
    shipVersion: "版本", shipStatus: { SHIPPED: "已出貨", VOIDED: "已作廢" }, shipBy: "記錄者", shipNoteLabel: "備註",
    voidReasons: { wrong_order: "訂單錯誤", wrong_tracking: "追蹤單號錯誤", not_dispatched: "包裹未寄出", other: "其他" },
    carriers: {
      seven_eleven_cvs: "7-ELEVEN 交貨便", familymart_cvs: "全家 店到店", hilife_cvs: "萊爾富", okmart_cvs: "OK mart",
      sf_express: "順豐速運", chunghwa_post: "中華郵政", other: "其他",
    },
    errors: {
      refundable_changed: "可退款金額已變更，請核對新金額後重試。", exceeds_refundable: "金額超過剩餘可退款金額。",
      amount_step: "此幣別的退款金額只能是整數元。", not_refundable: "此筆付款無法在此退款。",
      refund_blocked_review: "此筆付款正在核對，退款已被攔截，請聯絡支援。", refund_limit: "此筆付款已達退款次數上限。",
      version_changed: "出貨記錄在您讀取後已變更，請重新讀取訂單後重試。", not_shippable: "此訂單目前的狀態不能出貨。",
      invalid_carrier: "物流商資料無效。", invalid_tracking: "追蹤單號無效。", invalid_url: "追蹤連結無效。",
      void_requires_shipped: "只有已出貨的記錄才能更正或作廢。", invalid_void: "作廢請求無效。",
      forbidden: "此帳號沒有此操作的權限。", unauthorized: "請重新登入後繼續。", not_found: "所選商店中無法讀取此訂單。",
      conflict: "此請求與先前的請求衝突，請重新讀取訂單後重試。", rate_limited: "請求過多，請幾秒後再試。",
      retry_later: "暫時無法使用，請重試。", default: "請求未能完成，請重新讀取訂單後重試。",
    },
    statuses: {
      all: "全部", DRAFT: "草稿", AWAITING_PAYMENT: "待付款", CONFIRMED: "已確認", CANCELLED: "已取消",
      shipped: "已出貨", unshipped: "待出貨", MERCHANT_SHIPPED: "商家已出貨", PARTIALLY_REFUNDED: "部分退款", REFUNDED: "已退款",
      MANUAL_UNASSIGNED: "待分配", PAID_ALLOCATION_FAILED: "分配異常待核對", NOT_STARTED: "尚未開始",
      PENDING: "處理中", AUTHORIZED: "已授權·未扣款", CAPTURED: "已扣款", REVIEW_REQUIRED: "待核對",
      NONE: "無", READY: "待處理", home: "宅配", cvs_711: "7-ELEVEN 取貨", cvs_familymart: "全家取貨",
      cvs_hilife: "萊爾富取貨", cvs_okmart: "OK超商取貨", PROVIDER_LABEL_CREATED: "已建立物流單", cvs_pending: "已建單·待交寄",
    },
    payMode: "付款方式", payModes: { card: "信用卡", pay_at_pickup: "取貨付款" },
    collectionLabel: "取貨付款狀態",
    collectionStates: {
      PENDING: "等待取貨付款", COLLECTED: "已取貨付款", RETURNED: "未取貨·已退回",
      REFUNDED_OFFLINE: "已在本站外退款", CANCELLED: "已取消·庫存已釋放", RESTOCKED: "已退回·庫存已恢復",
    },
    sourceLabel: "門市來源",
    pickupSources: {
      ecpay_directory: "已從綠界門市地圖選取（已與門市名單核對）",
      buyer_entered: "買家自填門市（未驗證，出貨前請至超商官網核對）",
      merchant_attested: "賣家已確認",
    },
  },
};
