import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Live Studio", subtitle: "Local MOCK rehearsal only. Nothing here publishes to a platform.",
  store: "Store", noStore: "No authorized store is available.", newScene: "New scene", scenes: "Scenes",
  empty: "No scenes yet. Create a draft to plan one.", loading: "Loading scenes…", detailLoading: "Loading scene…",
  name: "Scene name", schedule: "Scheduled time (UTC, optional)", pickSchedule: "Choose scheduled date and time (UTC)", aspect: "Canvas ratio", wide: "16:9 · landscape", tall: "9:16 · portrait",
  editor: "Scene settings", editorHint: "Save the programme before checking rehearsal authority.",
  version: "Programme version", savedAt: "Last saved (UTC)", unsaved: "Unsaved changes", newDraft: "New unsaved scene",
  create: "Create draft", save: "Save draft", saving: "Saving…", select: "Select a scene to edit it.",
  rehearsal: "MOCK rehearsal", localOnly: "Local workflow check only; this does not publish a real stream.",
  prepared: "Prepared rehearsal authority", noPrepared: "No current prepared authority. An authorized internal fixture must prepare it before rehearsal can start.",
  expiredPrepared: "Prepared authority expired. Refresh the scene; a new authority must be prepared outside this page.",
  preparedUntil: "Valid until (UTC)", destinations: "Prepared destinations", unverified: "Public status unverified",
  observed: "Persisted media observation", noAttemptTitle: "Not started", noAttempt: "No rehearsal attempt has been started.",
  operation: "Operation", resource: "Media resource", transport: "Transport observation", noTransport: "Not observed",
  statusAt: "Last status update (UTC)", cleanup: "Cleanup required", stopRequested: "Stop requested", escalated: "Operator follow-up required",
  yes: "Yes", no: "No", start: "Start MOCK rehearsal", stop: "Request stop", working: "Submitting…",
  refresh: "Refresh facts", readOnly: "Read-only access. Draft edits and rehearsal controls are unavailable.",
  notDraftEditable: "Scene settings can be edited only while the scene is a draft.",
  dirty: "Discard unsaved scene changes?", titleInvalid: "Enter a scene name of 1–200 characters without leading/trailing spaces.",
  scheduleInvalid: "Enter a valid UTC time from year 2000 through 2199, or leave it blank.",
  signedOut: "Sign in again to open Studio.", forbidden: "You no longer have access to this scene.",
  notFound: "This scene is unavailable in the selected store.", unavailable: "Studio data is temporarily unavailable. Refresh and try again.",
  conflict: "The saved scene or rehearsal authority changed. Refresh the facts before another action.",
  invalid: "The request was rejected. Check the fields and refresh the scene.",
  uncertain: "The result is unknown. Refresh persisted facts; retry uses the same request key.",
  retrySame: "Retry same request", previous: "Previous page", next: "Next page", noMore: "End of scenes",
  claims: "Keyword claims",
  state: { DRAFT: "Draft", READY: "Ready", STARTING: "Starting", RUNNING: "Running", STOPPING: "Stopping", ENDED: "Ended", FAILED: "Failed" },
  operationState: { READY: "Queued", DISPATCHING: "Dispatching", UNKNOWN: "Unknown", ACKNOWLEDGED: "Acknowledged", SUCCEEDED: "Completed", FAILED_FINAL: "Failed", CANCELLED: "Cancelled", BLOCKED_POLICY: "Blocked by policy", STALE_BINDING: "Binding changed" },
  resourceState: { UNOBSERVED: "Unobserved", OBSERVED: "Observed locally", TERMINAL: "Terminal" },
  provider: { facebook: "Facebook", instagram: "Instagram" },
};
export type StudioCopy = typeof en;
export const studioCopy: Record<Locale, StudioCopy> = {
  en,
  "zh-CN": {
    title: "直播工作室", subtitle: "仅供本地 MOCK 模拟演练，不会在平台公开直播。",
    store: "店铺", noStore: "没有获授权的店铺。", newScene: "新建场次", scenes: "场次",
    empty: "暂无场次。先建立草稿来规划直播。", loading: "正在读取场次…", detailLoading: "正在读取场次…",
    name: "场次名称", schedule: "计划时间（UTC，可选）", pickSchedule: "选择计划日期和时间（UTC）", aspect: "画幅", wide: "16:9 · 横屏", tall: "9:16 · 竖屏",
    editor: "场次设置", editorHint: "先保存节目，再核对模拟演练授权。",
    version: "节目版本", savedAt: "最后保存（UTC）", unsaved: "尚未保存的修改", newDraft: "尚未保存的新场次",
    create: "建立草稿", save: "保存草稿", saving: "正在保存…", select: "选择场次后编辑。",
    rehearsal: "模拟演练", localOnly: "仅检查本地流程；不会在任何平台公开直播。",
    prepared: "已准备模拟授权", noPrepared: "当前没有可用的模拟授权。须由获授权的内部准备流程提供，才能开始演练。",
    expiredPrepared: "模拟授权已过期。请刷新场次；新的授权须在本页之外准备。",
    preparedUntil: "有效期至（UTC）", destinations: "准备的目的地", unverified: "公开状态未验证",
    observed: "已持久化的媒体观察", noAttemptTitle: "尚未开始", noAttempt: "尚未启动模拟演练。",
    operation: "操作", resource: "媒体资源", transport: "传输观察", noTransport: "尚未观察到",
    statusAt: "状态更新时间（UTC）", cleanup: "需要回收", stopRequested: "已请求停止", escalated: "需要人工跟进",
    yes: "是", no: "否", start: "开始模拟演练", stop: "请求停止", working: "正在提交…",
    refresh: "刷新事实", readOnly: "当前为只读权限，无法编辑草稿或控制演练。",
    notDraftEditable: "仅草稿状态的场次可编辑设置。",
    dirty: "放弃尚未保存的场次修改？", titleInvalid: "请输入 1–200 字的场次名称，首尾不要留空格。",
    scheduleInvalid: "请输入 2000–2199 年的有效 UTC 时间，或留空。",
    signedOut: "请重新登录后进入工作室。", forbidden: "当前已无权查看此场次。",
    notFound: "所选店铺中无法读取此场次。", unavailable: "工作室暂时无法读取，请刷新后重试。",
    conflict: "已保存场次或演练授权发生变化。请先刷新事实，再操作。",
    invalid: "请求未被接受，请检查字段并刷新场次。",
    uncertain: "提交结果暂无法确认。请刷新持久化事实；重试会使用同一个请求键。",
    retrySame: "按原请求重试", previous: "上一页", next: "下一页", noMore: "已到最后一页",
    claims: "评论口令登记",
    state: { DRAFT: "草稿", READY: "就绪", STARTING: "启动中", RUNNING: "运行中", STOPPING: "停止中", ENDED: "已结束", FAILED: "失败" },
    operationState: { READY: "待处理", DISPATCHING: "分派中", UNKNOWN: "结果未知", ACKNOWLEDGED: "已确认", SUCCEEDED: "已完成", FAILED_FINAL: "最终失败", CANCELLED: "已取消", BLOCKED_POLICY: "被策略阻止", STALE_BINDING: "绑定已变化" },
    resourceState: { UNOBSERVED: "未观察到", OBSERVED: "本地已观察到", TERMINAL: "已终止" },
    provider: { facebook: "Facebook", instagram: "Instagram" },
  },
  "zh-TW": {
    title: "直播工作室", subtitle: "僅供本機 MOCK 模擬演練，不會在平台公開直播。",
    store: "商店", noStore: "沒有獲授權的商店。", newScene: "新增場次", scenes: "場次",
    empty: "尚無場次。先建立草稿規劃直播。", loading: "正在讀取場次…", detailLoading: "正在讀取場次…",
    name: "場次名稱", schedule: "預定時間（UTC，選填）", pickSchedule: "選擇預定日期和時間（UTC）", aspect: "畫面比例", wide: "16:9 · 橫向", tall: "9:16 · 直向",
    editor: "場次設定", editorHint: "先儲存節目，再核對模擬演練授權。",
    version: "節目版本", savedAt: "最後儲存（UTC）", unsaved: "尚未儲存的變更", newDraft: "尚未儲存的新場次",
    create: "建立草稿", save: "儲存草稿", saving: "正在儲存…", select: "選擇場次後編輯。",
    rehearsal: "模擬演練", localOnly: "僅檢查本機流程；不會在任何平台公開直播。",
    prepared: "已準備模擬授權", noPrepared: "目前沒有可用的模擬授權。須由獲授權的內部準備流程提供，才能開始演練。",
    expiredPrepared: "模擬授權已過期。請重新整理場次；新授權須在本頁之外準備。",
    preparedUntil: "有效期限（UTC）", destinations: "準備的目的地", unverified: "公開狀態未驗證",
    observed: "已持久化的媒體觀察", noAttemptTitle: "尚未開始", noAttempt: "尚未啟動模擬演練。",
    operation: "作業", resource: "媒體資源", transport: "傳輸觀察", noTransport: "尚未觀察到",
    statusAt: "狀態更新時間（UTC）", cleanup: "需要回收", stopRequested: "已要求停止", escalated: "需要人工跟進",
    yes: "是", no: "否", start: "開始模擬演練", stop: "要求停止", working: "正在提交…",
    refresh: "重新整理事實", readOnly: "目前為唯讀權限，無法編輯草稿或控制演練。",
    notDraftEditable: "僅草稿狀態的場次可編輯設定。",
    dirty: "放棄尚未儲存的場次變更？", titleInvalid: "請輸入 1–200 字的場次名稱，首尾不要留空白。",
    scheduleInvalid: "請輸入 2000–2199 年的有效 UTC 時間，或留白。",
    signedOut: "請重新登入後進入工作室。", forbidden: "目前已無權檢視此場次。",
    notFound: "所選商店中無法讀取此場次。", unavailable: "工作室暫時無法讀取，請重新整理後重試。",
    conflict: "已儲存場次或演練授權發生變化。請先重新整理事實，再操作。",
    invalid: "請求未被接受，請檢查欄位並重新整理場次。",
    uncertain: "提交結果暫無法確認。請重新整理持久化事實；重試會使用同一個請求鍵。",
    retrySame: "以原請求重試", previous: "上一頁", next: "下一頁", noMore: "已到最後一頁",
    claims: "留言關鍵字登記",
    state: { DRAFT: "草稿", READY: "就緒", STARTING: "啟動中", RUNNING: "運行中", STOPPING: "停止中", ENDED: "已結束", FAILED: "失敗" },
    operationState: { READY: "待處理", DISPATCHING: "分派中", UNKNOWN: "結果未知", ACKNOWLEDGED: "已確認", SUCCEEDED: "已完成", FAILED_FINAL: "最終失敗", CANCELLED: "已取消", BLOCKED_POLICY: "受政策阻止", STALE_BINDING: "綁定已變更" },
    resourceState: { UNOBSERVED: "未觀察到", OBSERVED: "本機已觀察到", TERMINAL: "已終止" },
    provider: { facebook: "Facebook", instagram: "Instagram" },
  },
};
