#!/usr/bin/env bash
# depmap.sh — generate docs/engineering/dependency-map.md from the Go build graph.
#
# Why: hand-written "who calls what" docs rot. This map is derived from `go list`,
# so it is always true for the commit it was generated at; CI runs `depmap.sh --check`
# and fails when the committed file is stale (PROCESS.md §5).
#
# For each package under livecommerce/: its one-line package doc, the internal packages it
# imports, the third-party modules it imports, and the internal packages that import it.
# Standard-library imports are omitted (noise).
#
# Usage: bash scripts/dev/depmap.sh          # rewrite the file
#        bash scripts/dev/depmap.sh --check  # exit 1 if the file would change
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
out=docs/engineering/dependency-map.md
module="$(GOTOOLCHAIN=go1.27.1 go list -m)"

tmp="$(mktemp)"
GOTOOLCHAIN=go1.27.1 go list -f '{{.ImportPath}}{{"\t"}}{{.Doc}}{{"\t"}}{{join .Imports " "}}' ./... |
  python3 -c '
import sys
module = sys.argv[1]
rows = []
for line in sys.stdin:
    path, doc, imports = (line.rstrip("\n").split("\t") + ["", ""])[:3]
    rows.append((path, doc, imports.split()))
known = {p for p, _, _ in rows}
importers = {p: [] for p in known}
for p, _, imps in rows:
    for i in imps:
        if i in importers:
            importers[i].append(p)
short = lambda p: p[len(module) + 1:] if p.startswith(module + "/") else p
print("# Go dependency map (generated — do not edit)\n")
print("Generated by `scripts/dev/depmap.sh` from `go list ./...`. CI fails when stale.")
print("Internal = packages in this module; third-party = everything outside the module")
print("and the standard library. See `docs/engineering/dependencies.md` for why each")
print("third-party module was admitted.\n")
for p, doc, imps in sorted(rows):
    internal = sorted(short(i) for i in imps if i in known)
    third = sorted({i for i in imps if i not in known and "." in i.split("/")[0]})
    print(f"## `{short(p)}`\n")
    print((doc or "(no package doc — add one: PROCESS.md §5)") + "\n")
    print("- Depends on (internal): " + (", ".join(f"`{i}`" for i in internal) or "—"))
    print("- Depends on (third-party): " + (", ".join(f"`{i}`" for i in third) or "—"))
    print("- Used by: " + (", ".join(f"`{short(i)}`" for i in sorted(importers[p])) or "— (entry point or unused)"))
    print()
' "$module" > "$tmp"

if [[ "${1:-}" == --check ]]; then
  if ! cmp -s "$tmp" "$out"; then
    echo "depmap: $out is stale; run: bash scripts/dev/depmap.sh" >&2
    diff -u "$out" "$tmp" | head -40 >&2 || true
    rm -f "$tmp"; exit 1
  fi
  rm -f "$tmp"; echo "depmap: up to date"; exit 0
fi
mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
echo "depmap: wrote $out"
